### ISSUE TITLE
[Android][Chrome][v2.0-Beta9] Unable to generate HAR

### ISSUE THREAD

**Issue by aniket-21** [lightbody/browsermob-proxy#100]
Below is my simple code. I am able to generate HAR for iOS Safari but on Android it just time outs

//Create HAR File
            mobProxyServer.newHar("abc");

            d1 = new Date();

            //Open website
            driver.get("http://m.att.com");

            d2 = new Date();

            long diff = d2.getTime() - d1.getTime();
            //long diffSeconds = diff ;

            System.out.print(diff + "/n");

            //get and save HAR
            try {
                mobProxyServer.waitForNetworkTrafficToStop(100, 30000);
            }
            catch(RuntimeException e){}
            Har har = mobProxyServer.getHar();

            FileOutputStream fHarFile = new FileOutputStream("test_" + i + ".har");
            har.writeTo(fHarFile);

**Comment by jekh** [comment]
I'd try this again with the latest code in master, which has fixed the SSL issues that beta-9 had. If you still have the same issue, can you give some additional information about where you're seeing the timeouts?

**Comment by jekh** [comment]
Closing. Please reopen if you still experience issues with the 2.0.0 version.
