### ISSUE TITLE
I am using Browser Mob[browsermob-proxy-2.0-beta-6] + Selenium Webdriver 2.42.1 + Chrome Driver with Chrome 38.0.2125.101.[Win 7]  With below snippet Browser keeps refreshing the page.

### ISSUE THREAD

**Issue by UnnatiShukla** [lightbody/browsermob-proxy#105]
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from browsermobproxy import Server
from selenium import webdriver

server=Server('C:\Python27\Lib\site-packages\\browsermob-proxy-2.0-beta-6\\bin\\browsermob-proxy.bat')
server.start()

proxy=server.create_proxy()

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--proxy-server={0}".format(proxy.proxy))

browser = webdriver.Chrome(executable_path="E:\\chromedriver.exe",chrome_options = chrome_options,service_args=["--verbose", "--log-path=E:\\trace.log"])

proxy.new_har("CS")

browser.get("https://falcon.crowdstrike.com/")
har=proxy.har
print har

Any input will be a great help!

**Comment by jekh** [comment]
@UnnatiShukla Did you fix this problem? If not, try running against the latest code in master (beta-6 is a very old version).

**Comment by jekh** [comment]
Closing this old issue. Please reopen if you still experience issues with the 2.0.0 release.
