### ISSUE TITLE
SSL connection not working using Browsermob-proxy 2.0-beta-9 and Selenium 2.43.1

### ISSUE THREAD

**Issue by prullo-01** [lightbody/browsermob-proxy#108]
I'm trying to use BMP embedded with Selenium 2.43.1 and Firefox 32.0.3 in a Java test, but it fails to connect to SSL connections with the message: "The connection to the server was reset while the page was loading".
However plain HTTP connections work correctly.

Here is the minimum code that can show the issue:

```
ProxyServer server = new ProxyServer(PROXY_PORT);
server.start();

FirefoxProfile profile = new FirefoxProfile();
profile.setAcceptUntrustedCertificates(true);
profile.setAssumeUntrustedCertificateIssuer(true);
profile.setPreference("network.proxy.http", "localhost");
profile.setPreference("network.proxy.http_port", PROXY_PORT);
profile.setPreference("network.proxy.ssl", "localhost");
profile.setPreference("network.proxy.ssl_port", PROXY_PORT);
profile.setPreference("network.proxy.type", 1);
profile.setPreference("network.proxy.no_proxies_on", "");

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(FirefoxDriver.PROFILE, profile);
capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

WebDriver driver = new FirefoxDriver(capabilities);

driver.get("https://www.google.com/");
```
If I use the BMP 2.0-beta-9 standalone version (that is embedding Selenium 2.37.1) and Selenium 2.43.1 for the test, it works correctly with both HTTP plain and SSL connections.

If I try to use BMP 2.0-beta-9 embedded with Selenium 2.37.1 and Firefox 32.0.3, I get a blank page: probably that version of Selenium has problems in driving the latest version of Firefox.

I tried also using the Proxy object calling server.seleniumProxy() instead of using the profile, but it doesn't work neither.

The code above should work with both embedded and standalone versions.

**Comment by thibaut-sticky** [comment]
Hi,

Sorry to refresh this topic, but have you any workaround to made work bmp with https request?

**Comment by jekh** [comment]
BMP generally does work with HTTPS requests. What is the issue you're running into?

**Comment by thibaut-sticky** [comment]
Here my simple test

```JAVA
import net.lightbody.bmp.proxy.ProxyServer;

import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Test {

    @org.junit.Test
    public void test() throws Exception {
        ProxyServer server = new ProxyServer(9090);
        server.start();
        Proxy proxy = server.seleniumProxy();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, proxy);
        WebDriver driver = new ChromeDriver(capabilities);
        driver.get("https://google.fr");
        Thread.sleep(10000)
        server.stop();
        driver.quit();
    }
}
```

Instead of the Google home page, I got

>The connection was reset
The connection to the server was reset while the page was loading.
The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer's network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

Same result with FirefoxDriver.

**Comment by jekh** [comment]
I just ran the test code with FirefoxDriver without any problem. Can you paste the console output from the test?

**Comment by thibaut-sticky** [comment]
So, I'm using ArchLinux with the latest jdk8

The log you ask:

```
janv. 23, 2015 10:15:17 AM net.sf.uadetector.internal.data.DataBuilder addPatternToDevice
INFOS: No pattern available for 'Other'.
janv. 23, 2015 10:15:17 AM net.sf.uadetector.internal.data.DataBuilder addPatternToDevice
INFOS: No pattern available for 'Personal computer'.
janv. 23, 2015 10:15:17 AM net.lightbody.bmp.proxy.jetty.http.HttpServer doStart
INFOS: Version Jetty/5.1.x
janv. 23, 2015 10:15:17 AM net.lightbody.bmp.proxy.jetty.util.Container start
INFOS: Started HttpContext[/,/]
janv. 23, 2015 10:15:17 AM net.lightbody.bmp.proxy.jetty.http.SocketListener start
INFOS: Started SocketListener on 0.0.0.0:9090
janv. 23, 2015 10:15:17 AM net.lightbody.bmp.proxy.jetty.util.Container start
INFOS: Started net.lightbody.bmp.proxy.jetty.jetty.Server@4c3e4790
janv. 23, 2015 10:15:17 AM net.sf.uadetector.datastore.AbstractUpdateOperation isUpdateAvailable
INFOS: Can not check for an updated version. Are you sure you have an established internet connection?
Starting ChromeDriver (v2.10) on port 7246
Only local connections are allowed.
[0,708][WARNING]: PAC support disabled because there is no system implementation
janv. 23, 2015 10:15:26 AM net.lightbody.bmp.proxy.jetty.util.Credential <clinit>
INFOS: Checking Resource aliases
janv. 23, 2015 10:15:26 AM net.lightbody.bmp.proxy.jetty.http.SocketListener start
INFOS: Started SocketListener on 0.0.0.0:32940
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.util.Log info
INFOS: org.apache.http.NoHttpResponseException: google.fr failed to respond when requesting https://google.fr/
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.util.ThreadedServer run
INFOS: Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=32940]]
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.http.SocketListener stop
INFOS: Stopped SocketListener on 0.0.0.0:32940
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.util.ThreadedServer run
INFOS: Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=9090]
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.http.SocketListener stop
INFOS: Stopped SocketListener on 0.0.0.0:9090
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.util.Container stop
INFOS: Stopped HttpContext[/,/]
janv. 23, 2015 10:15:27 AM net.lightbody.bmp.proxy.jetty.util.Container stop
INFOS: Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@4c3e4790
```

As you can see, there is this log in particular:
>INFOS: org.apache.http.NoHttpResponseException: google.fr failed to respond when requesting https://google.fr/

**Comment by jekh** [comment]
Make sure you're using the latest code from master, not an old released version. We'll have a new release soon. It looks like you might be on an earlier version, since uadetector doesn't eaglerly initialize anymore unless you enable HAR capture.

**Comment by thibaut-sticky** [comment]
OK I will wait for this version. For deployment reason, I have to use only the maven repo.

**Comment by 15daniel10** [comment]
@jekh can you please explain how do I install the latest master snapshot to my local eclipse maven repo? 
I have downloaded the .rar file (from https://github.com/webmetrics/browsermob-proxy) and opened the archive.. from this point I'm stuck. never done it before and I can't find an information on how i'ts done.

Thanks ahead

**Comment by jekh** [comment]
The latest version (2.0.0) is available on Maven Central. You can also build from source as explained at the [bottom of the readme file on the main github page](https://github.com/lightbody/browsermob-proxy#creating-the-batch-files-from-source).

FYI -- post these sorts of questions to the Google Groups mailing list. Try not to hijack an unrelated issue.

**Comment by jekh** [comment]
I'm going to close this issue, but please feel free to reopen if this is still a problem.
