### ISSUE TITLE
open https error Certificates 

### ISSUE THREAD

**Issue by stevenliuit** [lightbody/browsermob-proxy#127]
hi,
I open https sites
INFO  n.l.b.p.http.BrowserMobHttpClient - javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints when requesting https://www.xxx.com 
but i open other https sites no issues;
this is my code：

		ProxyServer proxyServer = null;
		PhantomJSDriverService pjsService = null;
		TestRun testRun = null;
		try {
			InetAddress localHost = InetAddress.getByName("127.0.0.1");
			proxyServer = new ProxyServer(9090);
			proxyServer.setLocalHost(localHost);
			proxyServer.start();  
			proxyServer.setCaptureHeaders(true);
			proxyServer.clearDNSCache();
		}catch(Exception ex){
			ex.printStackTrace();
		}
	

I use the browser configured proxy sites open:
Oops.
Something went wrong. 

Firefox can't load this page for some reason.

Try Again 

I add the cybervillainsCA.cer to the browser
I sent you mail

**Comment by jekh** [comment]
@stevenliuit Is this issue solved for you now? Are you ok to close this issue?

**Comment by stevenliuit** [comment]
@jekh yes,This issue has been resolved.
you can edit:c:\Program Files (x86)\Java\jre7\lib\security\java.security

Then look for this line:
jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 1024

comment it out like this:
#jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 1024

**Comment by jekh** [comment]
Thank you, Steven. I'll close this issue.

One note of caution for anybody who uses this fix -- it allows less secure encryption algorithms to be used with the JVM. I would not recommend using it as a general remedy.

**Comment by stevenliuit** [comment]
But if you try to change browsermob-proxy code that does not work, I guess. Because the site is too long certificate encryption, and encryption certificates jdk is not such a long length of support.
