### ISSUE TITLE
Tentative date for 2.0-beta-10 Release.

### ISSUE THREAD

**Issue by jatinkapoor** [lightbody/browsermob-proxy#129]
@lightbody
Hi Patrick  , 
When do you plan to release the next version  of BrowserMob Proxy (Beta - 10). We use browsermob proxy in our project as a maven dependency and we would like to have the latest code with the fixes you have made lately. The last version was released almost a year back and after that a lot of modifications have gone into this project that we want to incorporate.

Regards,
-
Jatin

**Comment by jekh** [comment]
The no-longer-tentative date for 2.0.0 is TODAY! It's out :)
