### ISSUE TITLE
Har.writeTo(), extra '\u0000'

### ISSUE THREAD

**Issue by DareBoost** [lightbody/browsermob-proxy#133]
Hi!

When I convert a HAR object into a String (using the `writeTo(Writer)` method) i have extra characters '\u0000' at the end of some data.

It seems to occurs only for multi-part POST request.

When I print `harEntry.getRequest().getPostData().getText()` the text looks ok:
```
 -----------------------------18791545241988276220449128850
Content-Disposition: form-data; name="thomorderParam[website_BlockAction_submit][cartb_4][Order]"

VALIDER MON PANIER
-----------------------------18791545241988276220449128850--

```

But when I print it from `writeTo()` method or directly by using `Json.toJson()` I got this : 
```
{"mimeType":"multipart/form-data;
boundary=---------------------------18791545241988276220449128850",
"params":null,
"text":"-----------------------------18791545241988276220449128850\r\nContent-Disposition: form-data; name=\"thomorderParam[website_BlockAction_submit][cartb_4][Order]\"\r\n\r\nVALIDER MON PANIER\r\n-----------------------------18791545241988276220449128850--\r\n
\u0000\u0000\u0000\u0000
```

and many more '\u0000'.

Any thought ?

**Comment by jekh** [comment]
@DareBoost Did this resolve your issue? If so are you ok to close this issue?

**Comment by jekh** [comment]
Closing as resolved by PR #139.

**Comment by DareBoost** [comment]
Thanks, sorry for this late answer, we totally passed up our last github notifications.
(btw, thank you for moving forward the project, we hope to be back soon for some PRs)

**Comment by jekh** [comment]
No problem. Excited to see some more features implemented!
