### ISSUE TITLE
Future BrowserMob Proxy interface

### ISSUE THREAD

**Issue by jekh** [lightbody/browsermob-proxy#148]
I'm looking to get comments from @nite23 and others on the future BMP interface that will define the contract between the REST API and BMP core. I've created a first draft of the interface with inline comments [here](https://github.com/jekh/browsermob-proxy/compare/interface-design).

There are a few renamed methods and minor signature changes vs. the ProxyServer class in the 2.0 beta line, along with a couple new methods. All of the changes should be marked in the file. Most should be uncontroversial. 

One major omission is the request/response interceptor methods. They are specific to the implementation used, and so cannot be shared between the Jetty and LP implementations. They are going to be one of the (hopefully few) breaking changes when moving to LP.

**Comment by roydekleijn** [comment]
this is a first suggestions for the interface: https://github.com/roydekleijn/browsermob-proxy/blob/javaclient/src/main/java/net/lightbody/bmp/proxy/IProxyServer.java

maybe we can take it from here?

**Comment by nite23** [comment]
Here's my input...
https://github.com/nite23/browsermob-proxy/commit/e12a9d9758acebf503d279dfda3296bcfbf6ebab

**Comment by jekh** [comment]
@nite23 Thank you! I added some comments directly into the diff (hopefully everyone else can see them, too).

@roydekleijn Thanks for taking a stab at it -- would you like to take a look at @nite23's diff and add/review comments?

**Comment by jekh** [comment]
Now that the new interface is merged and in use, I'm going to close this issue. We can open a new issue to track future enhancements/updates to the new interface.
