### ISSUE TITLE
2.0 branch created for 2.0.0 release

### ISSUE THREAD

**Issue by jekh** [lightbody/browsermob-proxy#151]
I've created a new 2.0 branch. Once @oazmon updates PR #147 to merge to this branch, I feel confident skipping a beta/RC release and proceeding straight to 2.0.0. The 2.0 release has been in beta for a very long time and I think it's very well tested and stable. If there are any defects we can always create a 2.0.1+ release. Since work against 2.0 should be limited to critical bug fixes only, getting a stable candidate to Central seems like the right thing to do.

**Comment by nite23** [comment]
Thanks. Releasing beta-10 ASAP is fine, but before we do the 2.0.0, at the very least I'd like to get #153 fixed.

**Comment by jekh** [comment]
It'll be a few days at least before we can get a release together. I'd like to aim for Friday but I'm flexible. The sooner the better -- once we get a 2.0.0 into Central, more people will start using it and reporting defects against it. For any "critical" defects, we can always do a 2.0.1+ release, there's really no harm. And for less-critical defects, we can aim to fix them in 2.1, which will still be compatible with the 2.0 API.

Do you think #153 is high enough priority to push back the release? The current behavior has been in all released versions for a few years. (Not to say we shouldn't fix it of course!)

**Comment by oazmon** [comment]
I don¹t think this can be fixed and validated by Friday. Furthermore, in
most cases code does not arrive for Performance Testing before it passes
functional testing.
So these timeouts should not occur . However, as there is an effort to
push-left the testing, we can expect to see an increase in early perf
testing. 
Thanks,
Omer Azmon

From:  jekh <notifications@github.com>
Reply-To:  lightbody/browsermob-proxy
<reply+002fe11e614b45ee659f573ed8341287f7fcbaad6dd8b45092cf0000000110de6d779
2a169ce034deb83@reply.github.com>
Date:  Monday, January 26, 2015 at 13:02
To:  lightbody/browsermob-proxy <browsermob-proxy@noreply.github.com>
Cc:  "Omer Azmon," <omer@azmon.org>
Subject:  Re: [browsermob-proxy] 2.0 branch created for 2.0.0 release (#151)


It'll be a few days at least before we can get a release together. I'd like
to aim for Friday but I'm flexible. The sooner the better -- once we get a
2.0.0 into Central, more people will start using it and reporting defects
against it. For any "critical" defects, we can always do a 2.0.1+ release,
there's really no harm. And for less-critical defects, we can aim to fix
them in 2.1, which will still be compatible with the 2.0 API.

Do you think #153 <https://github.com/lightbody/browsermob-proxy/issues/153>
is high enough priority to push back the release? The current behavior has
been in all released versions for a few years. (Not to say we shouldn't fix
it of course!)

‹
Reply to this email directly or view it on GitHub
<https://github.com/lightbody/browsermob-proxy/issues/151#issuecomment-71537
574> .

**Comment by jekh** [comment]
I'll close this since 2.0.0 is released, and 2.1.0 is now in master.
