### ISSUE TITLE
Timed-out requests are recorded with incorrect duration

### ISSUE THREAD

**Issue by nite23** [lightbody/browsermob-proxy#153]
If a request times-out, it is recorded in HAR with 0ms timings and code -998. 
Proxy log shows this:
INFO 01/26 17:34:32 n.l.b.p.h.BrowserMo~ - org.apache.http.conn.HttpHostConnectException: Connection to http://10.0.0.1 refused when requesting http://10.0.0.1/

This exception should be caught, and HAR timing adjusted accordingly. There will probably be a similar issue with other connection failure modes.

Resulting HAR:
````json
{
	"log":{
		"comment":"",
		"version":"1.2",
		"creator":{
			"name":"BrowserMob Proxy",
			"comment":"",
			"version":"2.0"
		},
		"browser":{
			"name":"cURL",
			"comment":"",
			"version":"7.39.0"
		},
		"pages":[{
			"id":"Page 1",
			"comment":"",
			"pageTimings":{"comment":""},
			"startedDateTime":"2015-01-26T17:33:31.280+0000","title":""
		}],
		"entries":[{
			"comment":"",
			"time":0,
			"startedDateTime":"2015-01-26T17:34:32.428+0000",
			"cache":{},
			"pageref":"Page 1",
			"request":{
				"method":"GET",
				"comment":"",
				"headers":[],
				"url":"http://10.0.0.1/",
				"queryString":[],
				"httpVersion":"HTTP",
				"headersSize":0,
				"cookies":[],
				"bodySize":0
				},
			"response":{
				"content":{"size":0,"comment":"","mimeType":""},
				"comment":"",
				"headers":[],
				"httpVersion":"HTTP",
				"headersSize":0,
				"redirectURL":"",
				"statusText":"NO RESPONSE",
				"status":-998,
				"cookies":[],
				"bodySize":0
			},
			"timings":{
				"comment":"",
				"blocked":9,
				"dns":0,
				"connect":0,
				"ssl":0,
				"send":0,
				"wait":0,
				"receive":0
			}
		}]
	}
}
````

**Comment by jekh** [comment]
This is a good issue to track. It might not be a simple fix, though -- and in fact it might actually be WAD. The [HAR spec](https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html) is silent on what to record if a connection fails. I don't think it's really designed for that scenario; it is supposed to record "HTTP transactions", so I think connection failures are just outside the realm of what the HAR creators were thinking.

All I mean by that is that we're in uncharted territory and it's kind of up to us to determine what _should_ go into the HAR for connection failures and other error conditions where the spec is silent. I think the main question to answer is:
- What do other HAR creators do in this case? i.e. when Firefox or Chrome write a HAR with connection failures, what do their entries, response, and timings elements look like?

We should probably aim to implement whatever browsers and other tools do in this situation.

As a secondary concern, we should also aim to follow the spec as closely as possible, but that may get tricky. For example, the spec says that timings.send, timings.wait, and timings.receive are mandatory fields, but they really have no meaning in this error scenario. So what should they be? 0 is not accurate, and unlike other fields, -1 is _not_ a valid value for them. And what about timings.connect? That is optional and can be -1 ("does not apply"), but should it be? Perhaps it should be the amount of time we _tried_ to connect before timing out. That doesn't exactly meet the spec's requirements, but it's close to the spirit of the specification.

**Comment by jekh** [comment]
This should be fixed in the LittleProxy implementation, so I'm going to close the issue. Please feel free to reopen if you see any anomalies in timed-out requests in the HAR.
