### ISSUE TITLE
Central Repository deployment

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#164]
Is it possible for this project to be in central repository? I am using this as a library in my projects, but its a big pain in the butt manually uploading the artifact to our internal repo, not to mention the managing the dependencies of this project as well.

Thanks.

**Comment by jekh** [comment]
It most definitely is in Central! The [releases page](https://github.com/lightbody/browsermob-proxy/releases) has details.

**Comment by breinjhel** [comment]
Oh sorry I havent noticed it was added. My bad. Thanks jekh
