### ISSUE TITLE
Firefox 35 and Selenium 2.44

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#167]
Hi guys,

I get a proxy error when running my automation using latest firefox version 35.0.1 and selenium 2.44. If I run it using firefox 31 it works just fine. 

Im using latest BMP release 2.0.0

Any advice?

Thanks

**Comment by breinjhel** [comment]
It seems that using the localhost as proxy hostname does not work anymore for firefox. I changed it to 0.0.0.0 and it worked fine

**Comment by jekh** [comment]
Can you paste the code you're using to create the ProxyServer instance and wire up the proxy for Firefox?

**Comment by breinjhel** [comment]
server = new ProxyServer(bmpPort);
server.start();
server.setCaptureHeaders(true);
server.waitForNetworkTrafficToStop(20000, 45000);
server.setCaptureContent(true);

firefoxProfile = new FirefoxProfile();
firefoxProfile.setPreference("intl.accept_languages", locale);
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.BROWSER, Level.ALL);
capabilities.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);
capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
firefoxProfile.setAcceptUntrustedCertificates(true);
firefoxProfile.setAssumeUntrustedCertificateIssuer(false);
binary = new FirefoxBinary(new File(mac_firefox));
driver = new FirefoxDriver(binary, firefoxProfile, capabilities);

**Comment by jekh** [comment]
I don't see anything there that looks suspicious. Are you able to run the tests in the BrowserTest class (version 2.1, in master)? They use localhost and work for me on Linux using Selenium 2.44 and Firefox 35.0.1.
