### ISSUE TITLE
How to disable System.err logs

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#174]
Hi,

Im using BMP as embedded mode in my project and every time I open up proxy servers I see so many system.err logs which makes my logs messy. Is there an option to disable those? Or as an improvement bmp should use a logging framework. 

Thanks.

**Comment by jekh** [comment]
What errors are you seeing? There shouldn't be a large number of STDERR statements -- in fact there should be none. BMP uses slf4j as its logging facade, and stand-alone mode uses JDK logging. There is a [Logging](https://github.com/lightbody/browsermob-proxy#logging) section in the readme that has details on logging, and you can edit the standalone logging configuration in the bmp-logging.conf file after unzipping the release zip.

**Comment by breinjhel** [comment]
Feb 13, 2015 2:51:41 PM net.lightbody.bmp.proxy.jetty.http.HttpServer doStart
INFO: Version Jetty/5.1.x
Feb 13, 2015 2:51:41 PM net.lightbody.bmp.proxy.jetty.util.Container start
INFO: Started HttpContext[/,/]
Feb 13, 2015 2:51:41 PM net.lightbody.bmp.proxy.jetty.http.SocketListener start
INFO: Started SocketListener on 0.0.0.0:59588
Feb 13, 2015 2:51:41 PM net.lightbody.bmp.proxy.jetty.util.Container start
INFO: Started net.lightbody.bmp.proxy.jetty.jetty.Server@51c8530f
Feb 13, 2015 2:51:45 PM net.lightbody.bmp.proxy.jetty.util.Credential <clinit>
INFO: Checking Resource aliases
Feb 13, 2015 2:51:46 PM net.lightbody.bmp.proxy.jetty.http.SocketListener start
INFO: Started SocketListener on 0.0.0.0:59613

Feb 13, 2015 2:51:46 PM net.lightbody.bmp.proxy.jetty.util.ThreadedServer run
INFO: Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=59613]]
Feb 13, 2015 2:51:47 PM net.lightbody.bmp.proxy.jetty.http.SocketListener stop
INFO: Stopped SocketListener on 0.0.0.0:59613
Feb 13, 2015 2:51:47 PM net.lightbody.bmp.proxy.jetty.util.ThreadedServer run
INFO: Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=59588]
Feb 13, 2015 2:51:47 PM net.lightbody.bmp.proxy.jetty.http.SocketListener stop
INFO: Stopped SocketListener on 0.0.0.0:59588
Feb 13, 2015 2:51:47 PM net.lightbody.bmp.proxy.jetty.util.Container stop
INFO: Stopped HttpContext[/,/]
Feb 13, 2015 2:51:47 PM net.lightbody.bmp.proxy.jetty.util.Container stop
INFO: Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@51c8530f

**Comment by breinjhel** [comment]
Is there a way to modify the log level for the embedded version? Im using logback and i added its class name but it doesnt work

**Comment by jekh** [comment]
Those aren't System.err statements, they are normal logging statements. You can control the level of the logging as you normally would in any java application. If you want to squelch all of these statements, you can set the logger for net.lightbody.bmp to WARN. Logback has a number of different configuration mechanisms, so you'll have to see the [logback website](http://logback.qos.ch/) for details.

**Comment by Assarin** [comment]
Can somebody give example for log4j framework please. How to disable embedded bmp logging?
