### ISSUE TITLE
More documentation for testing SSL sites

### ISSUE THREAD

**Issue by soulgalore** [lightbody/browsermob-proxy#188]
Hi @jekh , 
first: I love that you and the rest has taken over the project and keep browsermobproxy alive. Thanks!

I have problems setting up Browsermobproxy running with SSL, capturing SSL traffic. I would really like a step by step guide in the docs for get it to work with Selenium and Firefox/Chrome.  

Best
Peter

**Comment by jekh** [comment]
Hi @soulgalore -- Thanks for your kind words! I'm happy to see people are making use of BMP.

As for the SSL problems you're having, what issues are you seeing? SSL should "just work" with BMP.

**Comment by soulgalore** [comment]
Hi @jekh thanks. I think I'm missing something basic :)

I run on Mac OS X and use a nodejs wrapper for Selenium. When I run Firefox the HAR file only contains OCSP requests like http://ocsp.digicert.com/? 

I've tried installing the cybervillainsCA.cer and tried with Chrome but then I don't get any requests in the HAR.

**Comment by soulgalore** [comment]
closing this, my mistake, I've missed setting up the proxy for https in Selenium, that's why the OCSP requests was visible (HTTP).
