### ISSUE TITLE
Please add support for modification of response content

### ISSUE THREAD

**Issue by afoleypp** [lightbody/browsermob-proxy#19]
Please see https://groups.google.com/forum/#!searchin/browsermob-proxy/Javascript/browsermob-proxy/w-xttP8NO_g/c9KiKc0nA0cJ for initial request. 

It would be useful to be able to, when using bmp, intercept the html response and edit it to, in a specific test case, inject javascript to record all JS errors as the browser loads the html. 

Thanks
Andrew

**Comment by jekh** [comment]
This should now be supported with LittleProxy!
