### ISSUE TITLE
Modifying POST body via HTTP Request Interceptor

### ISSUE THREAD

**Issue by gempesaw** [lightbody/browsermob-proxy#194]
Hey, very appreciative of the recent improvements y'all have made with 2.0.0 getting out, and eagerly awaiting LittleProxy as well! Thanks much for your hard work. 

I'm trying to use BMP to intercept HTTP requests and modify the POST body on the fly for XSS testing - basically, I'd like to put `<script>alert('hi')</script>` as one of my body parameters, instead of whatever it's supposed to be. 

```js
// turn this safe payload 
{ body: "safe body" } 
// into a dangerous one
{ body: "<script>alert('yikes')</script>" }
```

I'm cURLing a JS payload to to `/:proxy/interceptor/request` since I'm using Perl, which means I've been digging into Rhino a little bit. I was looking into [BrowsermobHttpRequest.java](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpRequest.java) and I tried using [setRequestBody](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpRequest.java), but it didn't seem to have any impact on the request. There's an ignored failing [test][] from #18 that is supposed to exercise this functionality, but I don't think its expected functionality was ever implemented, and apparently it causes the connection to hang.

[test]: https://github.com/lightbody/browsermob-proxy/blob/33d90d86e1bb14d28a94a3da8b8278fb8fef27f5/browsermob-core/src/test/java/net/lightbody/bmp/proxy/MailingListIssuesTest.java#L120

For the time being, I think I'm going to try capturing all the headers and content on the requests, and try to duplicate the request manually from the HAR, unless we can get this method to work. 

Any idea if it's possible for me to conditionally modify the POST body contents like that ? I'm planning to filter my interceptor based on the URI of the request, which I think I can get, but I'm mostly just having trouble exploring what I can do via Rhino.

Thanks again!

**Comment by jekh** [comment]
As you note, the current implementation is not very reliable when it comes to manipulating request/response bodies. I don't know how to reliable do that with the Jetty implementation. The LittleProxy implementation should allow you to do this fairly easily, though. I'll be opening a PR to add the LP module "soon", so if you can wait a few more days, you should be able to leverage that.

**Comment by gempesaw** [comment]
just saw the little proxy PR is making progress. yaaaaay :D

**Comment by jekh** [comment]
The LittleProxy PR is now merged. Interceptors aren't yet supported via the REST API unfortunately, but the functionality now exists using LittleProxy to modify POST bodies.

**Comment by gempesaw** [comment]
awesome, thanks for the update!

**Comment by jekh** [comment]
Good news! The REST API/standalone mode now works with LittleProxy. I updated the README.md file with information on [enabling LittleProxy in standalone mode](https://github.com/lightbody/browsermob-proxy#rest-api) and [using the LittleProxy interceptors with the REST API](https://github.com/lightbody/browsermob-proxy#rest-api-interceptors-with-littleproxy) (there's a new /filter endpoint).

Can you give that a try and see if it solves your issue? It would also be a huge help if you reported any issues you do find when LittleProxy is enabled :)

**Comment by gempesaw** [comment]
Cool! A small batch of my tests for proxy use worked fine with littleproxy, and I'm going to put it through its paces tonight with our entire test suite that uses the proxy, maybe 500 tests.

**Comment by jekh** [comment]
FYI -- I added originalRequest as a parameter on these filters, so your code may break when you pull from master.

**Comment by gempesaw** [comment]
Ah, thanks for the heads up! Just finished using the LittleProxy backed standalone version to manipulate request headers as in your example in the readme, no problems at all. :)

**Comment by gempesaw** [comment]
Hey, I'm going to close this because it's probably not going to be on my radar any time soon. As mentioned, the header manipulation worked and was much smoother to work with, thanks to the additional notes in the readme. In case I run into issues manipulating the post body, which I don't expect, I'll re-open a ticket specifically for the littleproxy impl. :)
