### ISSUE TITLE
Using custom certificate for SSL - Two MITM machines

### ISSUE THREAD

**Issue by jchuong** [lightbody/browsermob-proxy#198]
Hi, I am using BMP for testing where I have my tests running through the BMP proxy on one machine, remapHosts to the second machine, where I have some other logging being done, where the traffic then goes to a website.  I want both BMP and the second machine to be able to log the traffic passing through.

Now, I have a .pem file installed on the second machine (Ubuntu machine), and the machine running BMP (OSX Yosemite).  Now, I have tried to replace the files in sslSupport `cybervillainsCA.jks` and `cybervillains.cer` with my pem file converted with `keytool` and `openssl` (manual build).  However, when I run my test with this (Selenium with Safari), I get the 

`Cannot Verify Server Identity` pop-up with the issuer name still coming from `CyberVillains.com`.

Is there something I am missing?  The files have been replaced with my certificate on my machines, so where is Cybervillains coming from?

Thanks!

**Comment by jchuong** [comment]
Somewhat related: https://github.com/lightbody/browsermob-proxy/issues/121

I figured out that the subject name/issuer name is just generated in BMP so that's a non-issue, but it seems that BMP is generating a new RSA pair rather than using my own private key, which might be the issue.

**Comment by jchuong** [comment]
Figured out the problem(s) via a bunch of debugging.  I'll leave a small description for those of you in the future reading this. 

First of all, BMP uses Selenium's `CyberVillains.cer` and `CyberVillains.jks` from the JAR (ie maven users), so I had to replace the files and rebuild Selenium from source (can use new files, just have to change constant names in BMP see `KeyStoreManager.java`).

Furthermore, CyberVillains.jks has two entries: a `trustedCertEntry` with alias `signingCert` and `PrivateKeyEntry` with alias `signingcertprivkey`.  Again, aliases are defined in `KeyStoreManager.java`, which corresponds to these entries.  Also note that the aliases are case insensitive.  With a .pem file, I had the certificate and private key in it, but adding the .cer (DER encoded file, file type doesn't matter) only added a trustedCertEntry, so I followed http://cunning.sharp.fm/2008/06/importing_private_keys_into_a.html
 and converted my .pem to a PKCS12 file, and imported it, then renamed the alias:
http://stackoverflow.com/questions/3483121/can-i-change-the-alias-of-my-key
Thus, I replaced the constants and added my JKS to Selenium.

Finally, `remapHosts()` affects `wireUpSslWithCyberVilliansCA()` in `BrowserMobProxyHandler.java`, since I was remapping multiple domains to my second machine, the order of remapHosts() mattered;  the domain you want to test should be the first remapHosts(), so that originalHosts().get(0) is the website you are connecting to.

**Comment by jekh** [comment]
Wow! Thank you @jchuong for this detailed analysis. I'm sorry I wasn't able to help you with this; I have such little experience with custom certs (and SSL in general) that I'm useless. 

I think using custom certificates is a fairly common issue for users, and it's one that I'd like BMP to support. Do you have a diff, or a branch on github, that has the code changes you made to Selenium and/or BMP to support using custom certs? If you're interested in creating a PR, that would be even better :) But if not, I'd like to examine the changes and see if there's some way to add an option to specify a certificate file to use.

I'm going to reopen this issue in order to track it. I'd like it to eventually make it into the LittleProxy integration (currently PR #199) as well.

**Comment by jchuong** [comment]
What I did was to touch the minimal amount of bmp/Selenium by adding my own .cer and .jks and renamed the constants in `KeyStoreManager.java`.  The one thing to add is in `SeleniumProxyHandler.java`, there is a hard coded value for `cyberVillains.jks` in `wireUpSslWithCyberVilliansCA()`; although I use this method name still with my custom keystore.  Just add a getter for `KeyStoreManager._caPrivateKeystore` and that is all I did.  Nothing else I did can be turned into a PR since it's just hard coded to my own certificate and aliases :)  It's kind of up to you to decide how to read some sort of configuration file for this, and perhaps not read the .jks from Selenium.

**Comment by jekh** [comment]
This functionality is now out-of-the-box supported with LittleProxy and the BMP beta-4 release. See the MITM module documentation for information on using your own root certificate and private key with BMP: https://github.com/lightbody/browsermob-proxy/tree/master/mitm#using-a-custom-certification-authority

@jchuong - if this is working for you, I'll go ahead and close this issue. Thanks for your help with the investigation and testing!
