### ISSUE TITLE
SSL proxying needs to manage tmp files

### ISSUE THREAD

**Issue by seanmerrigan** [lightbody/browsermob-proxy#200]
The /tmp folder is getting filled with seleniumSslSupport* folders, to the point that the file system runs out of inodes and crashes.

**Comment by jekh** [comment]
This is resolved in master. Temp files are automatically cleaned up when the proxy shuts down. Give the latest code a try and see if that solves your issue.

**Comment by jekh** [comment]
I'm going to close, but please reopen if this isn't fixed in master for you.
