### ISSUE TITLE
Maven dependency to browsermob-core does not works

### ISSUE THREAD

**Issue by selenUser** [lightbody/browsermob-proxy#202]
<dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core</artifactId>
        <version>2.1.0-beta-1-SNAPSHOT</version>
        <scope>test</scope>
    </dependency>

**Comment by jekh** [comment]
The 2.1 version is not yet deployed to Central, so you need to run `mvn clean install` locally before using it. Alternatively, I have deployed the 2.1.0-beta-1-SNAPSHOT version to the sonatype snapshots repository, so you can include it if you add the snapshots repository tag to your pom:

```xml
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```
