### ISSUE TITLE
%u unicode encoding in url

### ISSUE THREAD

**Issue by romovs** [lightbody/browsermob-proxy#206]
It would be nice if browsermob-proxy supported the %uHHHH style of Unicode encoding in URLs. Unfortunately this non-standard relic is still widely used, especially in the corporate segment :disappointed:

**Comment by jekh** [comment]
If the original request from the client only contains the escaped characters, BrowserMob Proxy will interpret and proxy the requests as expected. It should also capture the characters properly in the HAR, although it won't attempt to decode them (they will still appear as %uHHHH). Are you experiencing any issues with this?

**Comment by romovs** [comment]
Seems like this is not directly related to %u style of encoding but more to how BMP handles URLs.
Closing this in favour of #207 which discusses the underlying issue.
