### ISSUE TITLE
SSL proxying needs to manage tmp files

### ISSUE THREAD

**Issue by npierreyves** [lightbody/browsermob-proxy#210]
The /tmp folder is getting filled with seleniumSslSupport* folders, to the point that the file system runs out of inodes and crashes. When you stop the server with ProxyServer.stop (); should be deleted temporary files ;)

**Comment by jekh** [comment]
Duplicate #200

**Comment by npierreyves** [comment]
If I'm not mistaken #200 -related fix is a Runtime.getRuntime () . addShutdownHook(...) . So it cleans on closing or crash JVM. But, if I call ServerProxy.stop() and I keep my program live, should be a way to clean the seleniumSslSupport records ?

**Comment by jekh** [comment]
That's true, the shutdown hook fires when the JVM shuts down, not when BMP stop()s. In theory, BMP can reuse the impersonated certificates across subsequent start()s. If you need to remove the temp files after stop()ing BMP but before the JVM shuts down, I'd recommend writing some code to do that after you call stop().

**Comment by npierreyves** [comment]
Okay, but in my case I can have several BMP started. And I have no way to retrieve the list of folders " seleniumSslSupport " created for the specific instance that I stopped. Will there a way to have this information ? I look in the code but the list of files is not accessible through class fields or handler or something like that ! Tank for you availability ;)

**Comment by jekh** [comment]
There isn't a way to access that list, really. What is the motivation to start multiple instances of BMP? Generally one instance is sufficient, unless you have particular HAR capture needs.

If you switch to the LittleProxy implementation of BMP, you won't run into the /tmp files issue, since LittleProxy isn't yet capable of impersonating certificates.

**Comment by npierreyves** [comment]
Thank you for your reply ;)
I need more because I BMP instance uses several instance of selenium in parallel and each of isntances uses a different proxy authenticated. And I need to use certificates because I have access to https site .
