### ISSUE TITLE
Allow removing the 'Via' header

### ISSUE THREAD

**Issue by romovs** [lightbody/browsermob-proxy#213]
Since some servers/clients behave differently when `Via` field is present in the request/reply headers, it could be useful to have an option for turning it off.

**Comment by jekh** [comment]
Good news: it turns out you can already do this. LittleProxy's proxyToServerRequest() filter method is called after the Via header has been added, so you can add a filter that removes it. You can't use BMP's `addRequestFilter()` method, since it fires when the response is received from the client. But BMP fully exposes LittleProxy's powerful but verbose (and slightly confusing) filter mechanism for exactly this sort of scenario. This code would allow you to remove the Via header on requests:
```java
        proxy.addLastHttpFilterFactory(new HttpFiltersSourceAdapter() {
            @Override
            public HttpFilters filterRequest(HttpRequest originalRequest) {
                return new HttpFiltersAdapter(originalRequest) {
                    @Override
                    public HttpResponse proxyToServerRequest(HttpObject httpObject) {
                        if (httpObject instanceof HttpRequest) {
                            ((HttpRequest) httpObject).headers().remove(HttpHeaders.Names.VIA);
                        }
                        return null;
                    }
                };
            }
        });
```

Similar code will work to remove Via from responses as well, overriding the `proxyToClientResponse()` method instead of proxyToServerRequest.

**Comment by romovs** [comment]
Oh that's great. Thank you!

**Comment by euala** [comment]
I switch on debug level:
`<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration debug="true" xmlns:log4j='http://jakarta.apache.org/log4j/'>
    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n" />
        </layout>
    </appender>
    <appender name="file" class="org.apache.log4j.RollingFileAppender">
        <param name="append" value="false" />
        <param name="maxFileSize" value="10MB" />
        
        <param name="file" value="log/common.txt" />
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern"
                   value="%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n" />
        </layout>
    </appender>
    <root>
        <level value="DEBUG" />
        <appender-ref ref="console" />
        <appender-ref ref="file" />
    </root>
</log4j:configuration>
`

And run simple code:
`import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Selenide.screenshot;

import io.netty.handler.codec.http.HttpHeaders;
import io.netty.handler.codec.http.HttpObject;
import io.netty.handler.codec.http.HttpRequest;
import io.netty.handler.codec.http.HttpResponse;
import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;
import net.lightbody.bmp.core.har.Har;
import net.lightbody.bmp.proxy.CaptureType;
import net.lightbody.bmp.proxy.auth.AuthType;
import org.littleshoot.proxy.HttpFilters;
import org.littleshoot.proxy.HttpFiltersAdapter;
import org.littleshoot.proxy.HttpFiltersSourceAdapter;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.zip.CRC32;
import java.util.zip.Checksum;

import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;
import static com.codeborne.selenide.WebDriverRunner.setProxy;

public class Router1 {

    public static void main(String[] args){
// start the proxy
        BrowserMobProxy proxy = new BrowserMobProxyServer();
        proxy.addLastHttpFilterFactory(new HttpFiltersSourceAdapter() {
            @Override
            public HttpFilters filterRequest(HttpRequest originalRequest) {
                return new HttpFiltersAdapter(originalRequest) {
                    @Override
                    public HttpResponse proxyToServerRequest(HttpObject httpObject) {
                        if (httpObject instanceof HttpRequest) {
                            ((HttpRequest) httpObject).headers().remove(HttpHeaders.Names.VIA);
                        }
                        return null;
                    }
                };
            }
        });
        proxy.start(44444);
        proxy.autoAuthorization ("test", "admin", "admin", AuthType.BASIC);
        // get the Selenium proxy object
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

        // configure it as a desired capability
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        // start the browser up
        WebDriver driver = new ChromeDriver(capabilities);

        // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
        proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

        proxy.newHar("index.har");

        //
        driver.get("http:/test/index.html");

        // get the HAR data
        Har har = proxy.getHar();

        // обработка полученных данных
        try {
            File file = new File("log/index.json");
            if (!file.exists()) {
                file.createNewFile();
            }
            FileOutputStream fos = new FileOutputStream(file);
            try {
                har.writeTo(fos);
            }
            finally {
                fos.close();
            }
        }
        catch (IOException e) {
            // обработка ошибки
            e.printStackTrace();
        }

        driver.quit();
        proxy.stop();
    }`

At log count of "Via: 1.1 browsermobproxy" without 
> proxy.addLastHttpFilterFactory(new HttpFiltersSourceAdapter() {
            @Override
            public HttpFilters filterRequest(HttpRequest originalRequest) {
                return new HttpFiltersAdapter(originalRequest) {
                    @Override
                    public HttpResponse proxyToServerRequest(HttpObject httpObject) {
                        if (httpObject instanceof HttpRequest) {
                            ((HttpRequest) httpObject).headers().remove(HttpHeaders.Names.VIA);
                        }
                        return null;
                    }
                };
            }
        });
is 144, with this code - 36.
Does server receive HttpHeaders.Names.VIA in any cases?

**Comment by AlexStanovsky** [comment]
I removed the VIA header as suggested. But i am seeing that i still recieve it in the response.
Is there a way to remove any traces of browsermob, so servers will not be able to know the request come from the proxy ?

**Comment by LionelBergen** [comment]
Removing the header as suggested does Not work. Other headers do, but not 'Via'. Testing using this url: https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending
It clearly shows the 'via' value.
