### ISSUE TITLE
I want to use the latest ResponseFilter interface

### ISSUE THREAD

**Issue by NozomiIto** [lightbody/browsermob-proxy#222]
According to the [README](https://github.com/lightbody/browsermob-proxy#littleproxy-interceptors) and [ResponseFilter.java](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/filters/ResponseFilter.java), ResponseFilter.filterResponse method has 3 argument, but filterResponse method defined on my local  2.1.0-beta-1-SNAPSHOT jar of browsermob-proxy
( https://oss.sonatype.org/content/repositories/snapshots/net/lightbody/bmp/browsermob-core/
 and https://oss.sonatype.org/content/repositories/snapshots/net/lightbody/bmp/browsermob-proxy/ ) has 2 argument.

I think these SNAPSHOT jars are not the latest, and I want to use the SNAPSHOT jar for the latest master..
Or should I see other SNAPSHOT repository?

**Comment by jekh** [comment]
I just uploaded the latest, so give it another try.

**Comment by NozomiIto** [comment]
It works. Thank you!
