### ISSUE TITLE
Update to maven dependency needed.

### ISSUE THREAD

**Issue by rradford-csid** [lightbody/browsermob-proxy#224]
This isn't working for me, I can't resolve the artifact, or find that SNAPSHOT package:
```
    <dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core-littleproxy</artifactId>
        <version>2.1.0-beta-1-SNAPSHOT</version>
        <scope>test</scope>
    </dependency>
```
I'm excited to use the new interface, when I can.
Amazing project, thanks for the great work!

**Comment by jekh** [comment]
This is actually a duplicate of #211. See the discussion there. Enough people are confused that I'll add some explanatory text when beta-1 is released.
