### ISSUE TITLE
Failed to load page with Selenium proxy and ResponseFilter

### ISSUE THREAD

**Issue by NozomiIto** [lightbody/browsermob-proxy#233]
I run simple webDriver test with Selenium proxy and ResponseFilter:

```Java
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Proxy;

// ...

BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start();
proxy.addResponseFilter(new ResponseFilter() {

        @Override
        public void filterResponse(HttpResponse response, HttpMessageContents contents, HttpRequest originalRequest) {
                System.out.println("do nothing");
        }
});
Proxy seProxy = ClientUtil.createSeleniumProxy(proxy);
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, seProxy);
WebDriver driver = new FirefoxDriver(capabilities);
driver.get("http://amazon.com");
```

When executes this test, WebDriver instance fails to load "http://amazon.com".
The screenshot is below:

![screen shot 2015-05-18 at 12 56 50](https://cloud.githubusercontent.com/assets/4276719/7674210/689263b0-fd5d-11e4-939d-5f8a4901cfca.png)

I use the latest SNAPSHOT.

```xml
<dependency>
  <groupId>net.lightbody.bmp</groupId>
  <artifactId>browsermob-core</artifactId>
  <version>2.1.0-beta-1-SNAPSHOT</version>
</dependency>
<dependency>
  <groupId>net.lightbody.bmp</groupId>
  <artifactId>browsermob-core-littleproxy</artifactId>
  <version>2.1.0-beta-1-SNAPSHOT</version>
</dependency>  
```

This code works well if commenting out `capabilities.setCapability(CapabilityType.PROXY, seProxy);`.
Is there any problem in my code?

**Comment by jekh** [comment]
The first thing to try is to remove the browsermob-core dependency. The browsermob-core-littleproxy dependency is sufficient for using BMP+LP, and it avoids pulling in some troublesome transitive dependencies.

Second, try building your project again with `mvn clean install -U`. I just uploaded the latest build to the snapshot repository, and it contains some important recent bugfixes. (Assuming you are pulling in BMP from the snapshot repo. If you are building yourself, pull the latest, rebuild BMP, then rebuild your project.)

If neither of those solve your issue, can you paste the log output from your application when you run it?

**Comment by NozomiIto** [comment]
Thanks for your quick replay.

I tried your first and second advices at the same time, and now it works in my environment.
Many thanks for your advice!

**Comment by jekh** [comment]
Glad you got it working! I'll close this issue.
