### ISSUE TITLE
Traffic does not go through the upstream proxy

### ISSUE THREAD

**Issue by mediga** [lightbody/browsermob-proxy#235]
Hi All,

I wrote a simple test case where i want browsermob to route the traffic through an upstream proxy (Charles proxy).  Does not look like upstream proxy settings are getting picked up. Here is the code.

Any idea what's wrong with my test case?

import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.UnknownHostException;

import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;
import net.lightbody.bmp.core.har.HarEntry;
import net.lightbody.bmp.core.har.HarPostDataParam;
import net.lightbody.bmp.proxy.CaptureType;

import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TestBMPV4 {

	private static final String URL = "https://www.google.com";
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		//upstream proxy: charles proxy
		System.setProperty("http.proxyHost", "127.0.0.1");
		System.setProperty("http.proxyPort", "8888");
		
	    BrowserMobProxy server = new BrowserMobProxyServer();
	    InetAddress inetaddress=null;
		try {
			inetaddress = InetAddress.getByName("localhost");
		} catch (UnknownHostException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

	    server.start(8989,inetaddress);
	    server.setHarCaptureTypes(CaptureType.getAllContentCaptureTypes());
	       
	    server.newHar();
	  
	    WebDriver driver =    createWebDriver();
	    
	    driver.get(URL);

	  //  driver.quit();
	  //  server.stop();

	}

	
	 private static WebDriver createWebDriver(){
		 
	       String httpProxy = "127.0.0.1:8989";
	        // configure it as a desired capability
	        DesiredCapabilities capabilities = new DesiredCapabilities();
	       
	        FirefoxProfile profile = new FirefoxProfile();
	        profile.setAcceptUntrustedCertificates(true);
	        profile.setAssumeUntrustedCertificateIssuer(true);              
	        profile.setPreference("network.proxy.share_proxy_settings", true);
	       
	       
	        Proxy proxyManual = new Proxy();
	        proxyManual.setProxyType(Proxy.ProxyType.MANUAL);
	        proxyManual.setHttpProxy(httpProxy);
	          
	  	   capabilities.setCapability(CapabilityType.PROXY, proxyManual);     
	      
	       // profile.setPreference("network.proxy.no_proxies_on", "");        
	      
	      capabilities.setCapability(FirefoxDriver.PROFILE,profile);

	      capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
	    
	        // start the browser up
	        WebDriver driver = new FirefoxDriver(capabilities);
	        return driver;
	    }
	
	
}

**Comment by mediga** [comment]
Never mind, got it working by setting the upstream proxy using 

 InetSocketAddress inetsockaddr = new InetSocketAddress("127.0.0.1", 8888);
server.setChainedProxy(inetsockaddr);

Setting the upstream proxy using java system properties did not work.

**Comment by mediga** [comment]
not getting the har logs with 

server.setChainedProxy(inetsockaddr);

any other option to set the upstream proxy and also get the har logs for http/https pages?

**Comment by jekh** [comment]
For HTTP requests, you should receive HAR logs with the upstream proxy. However, HTTPS requests will not appear in the HAR logs, because LittleProxy cannot currently MITM HTTPS requests when there is a chained proxy. I hope to address that issue in the "not-too-distant future", but it likely will not be until BMP and/or LP implement better MITM support.

One thing to note about chained proxies: you have to set the chained proxy _before_ calling start(). This isn't obvious, so I'll add an "is started?" check, similar to what we do setConnectTimeout() and a few other pre-start() methods. Your code would look something like:
```java
BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.setChainedProxy(...address...);
proxy.start();
```

Also, I did notice that you're not setting the https proxy in the Selenium proxy object. Since you're using a chained proxy you won't be able to capture HAR data for HTTPS requests anyway, but if you still want them to go through the proxy, make sure to add:
```java
//[...]
proxyManual.setProxyType(Proxy.ProxyType.MANUAL);
proxyManual.setHttpProxy(httpProxy);
proxyManual.setHttpsProxy(httpProxy);
```

**Comment by jekh** [comment]
Hi @mediga - this issue seems to be the same as reported in issue #121. Would you be okay if we closed this issue and tracked the status of the "Chained Proxy + HTTPS + MITM" issue in #121?

**Comment by mediga** [comment]
Makes sense , thank you

**Comment by leslyarun** [comment]
@jekh I used the following code for corporate proxy :

```InetSocketAddress inetsockaddr = new InetSocketAddress("proxy.cognizant.com", 6050);
	  proxy.setChainedProxy(inetsockaddr);

      proxy.start();
```

But when my selenium tests starts, it randomly chooses some port no. for proxy server. 
Pls help me

**Comment by jekh** [comment]
@leslyarun - You should open a new issue for your question, and include more information about how you're configuring your Selenium test.
