### ISSUE TITLE
How to configure proxy for mobile app

### ISSUE THREAD

**Issue by karunakaranvrv** [lightbody/browsermob-proxy#237]
@jekh 

I am writing automation test for mobileweb and Android/iOS app.

Proxy code used in mobileweb:-

ProxyServer proxyServer = new ProxyServer(4444);
proxyServer.start();    

Proxy proxy = proxyServer.seleniumProxy();
DesiredCapabilities capabillities = DesiredCapabilities.firefox();
capabillities.setCapability(CapabilityType.PROXY, proxy);
capabillities.setCapability("version", "5");
capabillities.setCapability("platform", Platform.XP);
this.driver = new RemoteWebDriver(
        new URL("http://myname:xxxxxx@ondemand.saucelabs.com:80/wd/hub"),
        capabillities);

I can able to setup proxy for mobileweb test. How can i do the same for mobile app testing. 

Is above code supports mobile app?

Kindly respond me.

**Comment by jekh** [comment]
That's a question for the mobile application vendor. The proxy will work with HTTP requests from any source. If you have a mobile application that is making HTTP requests, you'll need to configure the application to point to a running BrowserMob Proxy instance.

**Comment by jekh** [comment]
I'm going to go ahead and close this, but please feel free to re-open if you're unable to get mobile apps to connect to BMP.

**Comment by jatinkapoor** [comment]
Hi @karunakaranvrv,  were you able to find a solution for this?  I am trying something similar . If you were able to find the resolution for this , can you please share the configuration.
