### ISSUE TITLE
BrowserMob Proxy 2.1.0-beta-1 released

### ISSUE THREAD

**Issue by selenUser** [lightbody/browsermob-proxy#252]
I updated my POM.xml with

<dependency>
            <groupId>net.lightbody.bmp</groupId>
            <artifactId>browsermob-proxy</artifactId>
            <version>2.1.0-beta-1</version>
            <scope>test</scope>
        </dependency>

but can not create instance BrowserMobProxy. not founding class

![browsermob proxy](https://cloud.githubusercontent.com/assets/10746158/7909582/ec982322-0855-11e5-88b7-4957ec578dc6.jpg)

**Comment by npierreyves** [comment]
I updated my POM.xml also with :
```xml
<dependency>
            <groupId>net.lightbody.bmp</groupId>
            <artifactId>browsermob-proxy</artifactId>
            <version>2.1.0-beta-1</version>
</dependency>
```
but no artifacts available !

Version 2.1.0 not available : http://mvnrepository.com/artifact/net.lightbody.bmp/browsermob-proxy
Just POM is available : http://search.maven.org/#artifactdetails%7Cnet.lightbody.bmp%7Cbrowsermob-proxy%7C2.1.0-beta-1%7Cpom

**Comment by jekh** [comment]
The artifactId has changed in 2.1.0. For the legacy implementation, use `browsermob-core`. To use the LittleProxy implementation, use `browsermob-core-littleproxy`.
