### ISSUE TITLE
2 requests to the same URL - one record at har

### ISSUE THREAD

**Issue by tav1313** [lightbody/browsermob-proxy#254]
I run URL, which in turn produces 2 (POST) requests to the same URL, but with different post data,
HAR.getLog().getEntries() contains record for only one request - any suggestions?

**Comment by jekh** [comment]
If there are two separate POSTs, the har should record two separate entries. Can you give more details on how you're making the requests, and what output you're seeing in the logs and the har?

**Comment by tav1313** [comment]
hm. it seems firebug draws 2 POST requests, while chrome(and IE also) puts one POST request only.
I suggest close the issue - firebug feature\ bug))
