### ISSUE TITLE
External proxy ?

### ISSUE THREAD

**Issue by chandon** [lightbody/browsermob-proxy#263]
Is it possible to specify an external proxy to browsermob-proxy (because i don't have a direct access to the internet, only through an external proxy) ? 
Thanks

**Comment by jekh** [comment]
Yes, you can. Use BrowserMobProxy.setChainedProxy(...). One thing to note, however: MITM is not available with a chained proxy, so you will not be able to intercept or capture HTTPS traffic in the HAR. (HTTPS traffic will still be routed through BMP, and http traffic will be captured/intercepted as usual.) This is an unfortunate limitation of our current MITM mechanism, which will be improved in a future beta release.

**Comment by chandon** [comment]
In fact, i want to be able change the "remoteHost" of the chainedProxy after the proxy is started, but it's not possible with little proxy... so i'm to modifying littleproxy to do it

**Comment by jekh** [comment]
Since this issue is so old, I'll go ahead and close it. It should be possible to do this using the `BrowserMobProxyServer.setChainedProxyManager(...)` method. Feel free to reopen if you're still still having issues.

**Comment by teocns** [comment]
Is this available for Python?
