### ISSUE TITLE
'started' flag is not set to false after stopping BrowserMobProxyServer

### ISSUE THREAD

**Issue by valfirst** [lightbody/browsermob-proxy#264]
Version: 2.1.0-beta-1
'started' flag is not set to false after stopping BrowserMobProxyServer.

Run of the following code:
```java
BrowserMobProxy proxyServer = new BrowserMobProxyServer();
proxyServer.start();
proxyServer.stop();
proxyServer.start();
```
throws exception:

```
ERROR org.littleshoot.proxy.impl.DefaultHttpProxyServer - Uncaught throwable
java.lang.IllegalStateException: Proxy server is already started. Not restarting.
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:280) ~[browsermob-core-littleproxy-2.1.0-beta-1.jar:?]
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:358) ~[browsermob-core-littleproxy-2.1.0-beta-1.jar:?]
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:369) ~[browsermob-core-littleproxy-2.1.0-beta-1.jar:?]
```

**Comment by jekh** [comment]
This is actually works-as-(currently) designed. BMP is not currently meant (at least not the LittleProxy implementation) to be stopped and restarted.

Here's a quote from a google groups post on the subject:
> Here's how isStarted() and isStopped() work:

> 1. Before the proxy is started, both isStarted() and isStopped() return false.
2. After starting the proxy, isStarted() returns true and isStopped() returns false.
3. After stopping the proxy, both isStarted() and isStopped() return true.

>The meaning of isStarted() is not "is the proxy currently running?" but rather "was the proxy started at some point?". Perhaps we can consider adding an isRunning() or isActive() method that returns true only if the proxy is started and has not stopped.

As a work-around, you could just stop the old proxy server and create a new one:
```java
BrowserMobProxy proxyServer = new BrowserMobProxyServer();
proxyServer.start();
proxyServer.stop();
proxyServer = new BrowserMobProxyServer();
proxyServer.start();
```

I'm curious, what is your use case for stopping and restarting the proxy?

**Comment by valfirst** [comment]
@jekh , thank you for your answer!

> I'm curious, what is your use case for stopping and restarting the proxy?
I use BMP in my WebUI tests (based on Selenium WebDriver). I have a set of test suites. User may choose different suites and run them sequentially. I don't have control (at least for now) how many test suites are running, so I start BMP before each suite and stop it after test suite finish. Maybe I need to revise may runner and find a way to start BMP before all suites and stop it only when all runs are finished.

The provided workaround works for me at least for now. So I think you or I can close this issue if you don't need to do anything within this issue.
