### ISSUE TITLE
need a way of overriding the location/name of bmp-logging.properties

### ISSUE THREAD

**Issue by adamgoucher** [lightbody/browsermob-proxy#269]
I'm installing BMP via Chef and would like to put my properties file in /etc/browsermob/logging.properties but the path to bmp-logging.properties is relative to the current directory. There should be an override commandline value to specify a location for this file.

**Comment by jekh** [comment]
Standalone mode uses log4j 2, so you can specify the logging properties file by defining the `log4j.configurationFile` JVM property when running BMP:

```sh
./browsermob-proxy -Dlog4j.configurationFile=/etc/browsermob/logging.properties -port 9090 --use-littleproxy true
```

That isn't spelled out anywhere in the readme currently. I'd welcome a PR with more detailed instructions for the logging section, if you're interested.
