### ISSUE TITLE
WhiteList and BlackList are not working with the new BrowserMobProxy

### ISSUE THREAD

**Issue by josemoO** [lightbody/browsermob-proxy#279]
The Urls that match the blacklist or the Urls that do not match the whitelist do not return, the browser timeouts waiting for an answer of those Urls.

I am using Maven, Windows 7 64bits, Java 1.8, TestNG, Selenium 2.46 and browsermob-core-littleproxy 2.1.0-beta-1.

I prepared a sample maven project with the case to reproduce this issue, but it seems that I can't upload it, so here you have my TestNG test case:

package test.whiteList;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;

import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;

import org.openqa.selenium.By;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class WhiteListTest {

	private WebDriver driver;
	private BrowserMobProxy proxyServer;
	
	@BeforeMethod
	public void setUp() throws UnknownHostException {		
		
		// Set up the BrowserMob proxy in order to block the calls to Google Ads that some times block the browser
		proxyServer = new BrowserMobProxyServer();				
		
		// This are the patterns of our sites, in real life there are more...
		List<String> allowUrlPatterns = new ArrayList<String>();
		allowUrlPatterns.add("https?://.*(newhomesource.com)+.*");
		
		// All the URLs that are not from our sites are blocked and a status code of 403 is returned
		proxyServer.whitelistRequests(allowUrlPatterns, 404);
		
		proxyServer.start(9091, InetAddress.getLocalHost());
		
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		// get the Selenium proxy object
		Proxy proxy = ClientUtil.createSeleniumProxy(proxyServer);
		capabilities.setCapability(CapabilityType.PROXY, proxy);
				
		driver = new FirefoxDriver(capabilities);
	}

	@Test
	public void test() {

		driver.get("http://www.newhomesource.com");
		
		// Do a search
		driver.findElement(By.id("SearchText")).sendKeys("Austin, tx area");
		
		driver.findElement(By.id("HomeSearchBtn")).click();
	}
	
	@AfterTest
	public void cleamUp(){
		driver.quit();
		
		proxyServer.stop();
	}
}

And this is the content of my pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>WhiteListExample</name>
	<properties>
		<suite.xml.file>testsuite.xml</suite.xml.file>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.46.0</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8</version>
		</dependency>
		<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-core-littleproxy</artifactId>
			<version>2.1.0-beta-1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>18.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.1</version>
		</dependency>
	</dependencies>
	<build>
		<directory>${project.basedir}/${output_folder}</directory>
		<outputDirectory>${project.build.directory}/classes</outputDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<reuseForks>false</reuseForks>
					<forkCount>1</forkCount>
					<testFailureIgnore>true</testFailureIgnore>
					<suiteXmlFiles>
						<suiteXmlFile>${suite.xml.file}</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
</project>

Thanks in advance for all your work, BrowserMob proxy is a great tool, and the whitelist and blacklist an important feature and I have to say that I am glad the development of browsermob proxy continues after a time without releases. Please let me know if you need more information.

Thanks,
Jose

**Comment by jekh** [comment]
This issue was fixed by PR #261 and PR #273, which are now in master. There is one outstanding issue I want to get fixed before beta-2 is released, but it will most likely be released to Central within the next few days.

**Comment by jekh** [comment]
Beta-2 is out! Update your pom and that should fix your issue.

**Comment by josemoO** [comment]
Hi jekh,
It is working great now! Thank you!

**Comment by jekh** [comment]
Awesome, thanks for testing!
