### ISSUE TITLE
Proxy Sets Random Port

### ISSUE THREAD

**Issue by jsl303** [lightbody/browsermob-proxy#281]
I use BMP 2.1.0-beta-2-SNAPSHOT and selenium-firefox-driver 2.46.0.
Even if I set 
proxy.setHttpProxy("localhost:4397");
After it opens the Firefox, if I go to options - advance - network - proxy settings
"Both http and ssl are set to one random port.
Then if I go to site with ssl, I get
400 The plain HTTP request was sent to HTTPS port
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.4.2
Is this BMP problem or selenium?
Thanks,

**Comment by jekh** [comment]
Hi @jsl303. If you're using Selenium with BMP, you don't need to create the Selenium Proxy object yourself. You can use BMP's ClientUtil to do it for you. There's an [example in the readme](https://github.com/lightbody/browsermob-proxy#using-with-selenium).

If you do want to create the Proxy object yourself, and you want to use it for HTTP and HTTPS traffic, you'll need to call `proxy.setSslProxy("proxyhost:proxyport")` with appropriate values.

**Comment by jsl303** [comment]
Jason, thanks for the reply.
Here is my setup.
BrowserMobProxy server = new BrowserMobProxyServer();
server.start(4997);
Proxy proxy = ClientUtil.createSeleniumProxy(server);
proxy.setHttpProxy("localhost:4997");
proxy.setSslProxy("localhost:4998");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability(CapabilityType.PROXY, proxy);
capabilities.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);
driver = new FirefoxDriver(capabilities);
After it opens the Firefox, if I go to options - advance - network - 
proxy settings, Both http and ssl are set to one random port that I 
didn't specify.
When I go to site with ssl, I get
400 The plain HTTP request was sent to HTTPS port
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.4.2
Any suggestion on why it is causing that problem?
Thanks for your help,

JL

**Comment by jekh** [comment]
When you use ClientUtil.createSeleniumProxy, you don't need to set the proxy ports explicitly. Have you tried following the example in the readme that I referred to earlier? Does that work?

**Comment by jsl303** [comment]
The reason I wanted to try different port was because Nginx complains 
about sending plain over ssl.
However, 2.1.0-beta-3 seemed to fix that.
Thanks,

**Comment by kcheung00** [comment]
The example in readme does not work. There are two proxy.

    // start the proxy
    BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0);

    // get the Selenium proxy object
    Proxy proxy = ClientUtil.createSeleniumProxy(proxy);

Even I change to the following; it still doesn't work. Just launch the firefox and failed to connect to the proxy.

Here is what I change:
    // start the proxy
    BrowserMobProxy server = new BrowserMobProxyServer();
    server.start(0);

    // get the Selenium proxy object
    Proxy proxy = ClientUtil.createSeleniumProxy(server);

**Comment by jekh** [comment]
Since the original issue seems to be resolved, I'll go ahead and close this.
