### ISSUE TITLE
Response not recorded for interrupted(?) requests

### ISSUE THREAD

**Issue by romovs** [lightbody/browsermob-proxy#285]
HAR produced using the following steps doesn't contain responses for some of the requests:

- Go to http://www.golden7.com
- Wait for the page to load and close the browser
- Fetch the HAR

One of the requests to zopim.com:443 with an URL similar to https://ie12.zopim.com:443/s/W/xdds/J-2N2dL+-TR-o2np/p/1437408446575 will have its response missing.

By the looks of it it seems to happen when an active request is cancelled by the client (those zopim.com requests take awfully long to complete, which is an expected behaviour actually).
Perhaps it would be better to omit info about client-side interrupted requests entirely from the HAR? If it's indeed due to that and not something else..

**Comment by jekh** [comment]
When I recently added the error handling to the HAR capture, I didn't explicitly test connection interruptions, though response timeouts should be handled properly. Does the HAR file fail to validate or load with HAR viewers because it's missing responses?

**Comment by romovs** [comment]
Yeah pretty much everything fails to parse it properly. It isn't marked as optional in the HAR spec either so I guess it's mandatory to include it.

> I'm thinking we could either include an error code for "response interrupted" or "no response received"

Even better! :)

**Comment by jekh** [comment]
@romovs - I just merged a fix for this. Would you mind testing your scenario against the code in master?

**Comment by romovs** [comment]
It's working great now. Thanks!
