### ISSUE TITLE
serverToProxyResponseReceiving executed before proxyToServerRequestSent

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#293]
We are experimenting some weird time measures in the generated har. When the proxy VM runs in the same Amazon EC2 zone that the application VM, some "wait" timings are crazy. We have investigated a little bit and we have discovered that it is caused due to the method HarCaptureFilter.serverToProxyResponseReceiving is executed before than the HarCaptureFilter.proxyToServerRequestSent when it is suposed to be "sent" before "receiving".

Below there are logs of two resources confirming it:

Heimdal: serverToProxyResponseReceiving-> responseReceiveStartedNanos:89544849957324; sendFinishedNanos:0;url:http://52.28.125.187/prestashop/themes/default-bootstrap/css/modules/blockcategories/blockcategories.css
Heimdal: proxyToServerRequestSent-> sendFinishedNanos:89544864881136;url:http://52.28.125.187/prestashop/themes/default-bootstrap/css/modules/blockcategories/blockcategories.css

Heimdal: serverToProxyResponseReceiving-> responseReceiveStartedNanos:89544837484755; sendFinishedNanos:0;url:http://52.28.125.187/prestashop/themes/default-bootstrap/css/autoload/highdpi.css
Heimdal: proxyToServerRequestSent-> sendFinishedNanos:89544847430805;url:http://52.28.125.187/prestashop/themes/default-bootstrap/css/autoload/highdpi.css

We have "fixed" the problem just introducing an if : 

if (sendFinishedNanos > 0){
        	harEntry.getTimings().setWait(responseReceiveStartedNanos - sendFinishedNanos, TimeUnit.NANOSECONDS);
        }

Regards,

**Comment by jekh** [comment]
@jpereira06 - this looks like the same issue as reported by @romovs in #288. I'll give an update there.

**Comment by jpereira06** [comment]
Perfect! Thanks for the fixing!
