### ISSUE TITLE
LittleProxy -> chainedProxy (user/password)

### ISSUE THREAD

**Issue by npierreyves** [lightbody/browsermob-proxy#294]
I tried a lot of time and I can not find how to pass a user / password for chainedProxy with LittleProxy (enterprise proxy or private proxy for exemple ). 
I even watched as one would do it straight with LittleProxy ( net.lightbody.bmp : littleproxy : 1.1.0-beta-BMP -7) , just to see but I found nothing !

does anyone just tell me how to proceed ?

Thanks.

**Comment by leslyarun** [comment]
Even I want to know how to use corporate proxy in BrowserMobProxy 2.1.0-beta-2. 
Someone pls help us. 
Normally Im using a proxy address and port no to access internet. Some Pls tel me how to configure it

**Comment by jekh** [comment]
Authentication with an upstream proxy isn't currently explicitly supported, although encryption is. It seems like a useful feature, and we can add it to the backlog. I'd welcome any PRs that implement this in the meantime.

@leslyarun - Corporate proxies that do not require authentication are supported using BrowserMobProxy.setChainedProxy().

**Comment by leslyarun** [comment]
@jekh Yes, it requires Authentication . I need to provide a username/password. It will very useful, if such kind of support is provided

**Comment by npierreyves** [comment]
Anyway this feature is mandatory for Browsermod -proxy can pass completely on LitteProxy . I confience Jason and the community to find a solution to this problem ; ) Thank for your work.

**Comment by Jonxxx** [comment]
It's very useful feature for me too. As a temporary solution you might do following:
```
BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.setChainedProxy(new InetSocketAddress("proxy.yourcompany.ru", 8080));
String authParam = "login:password";
authParam = new String(Base64.encodeBase64(authParam.getBytes()));
proxy.addHeader("Proxy-Authorization", "Basic " + authParam);
```
But littleproxy cut out the header as it is hop by hop header. Therefore you need to modify the static field that contains these headers:
```
static {
        try
        {
            Field field = ProxyUtils.class.getDeclaredField("SHOULD_NOT_PROXY_HOP_BY_HOP_HEADERS");
            field.setAccessible(true);
            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
            field.set(null, ImmutableSet.of(
                "Connection".toLowerCase(Locale.US), "Proxy-Authenticate".toLowerCase(Locale.US),
                "TE".toLowerCase(Locale.US), "Trailer".toLowerCase(Locale.US), "Upgrade".toLowerCase(Locale.US),
                new String[]{"Keep-Alive".toLowerCase(Locale.US)}));
        }
        catch (Throwable e)
        {
            throw new RuntimeException(e);
        }
    }
```
It's working for me perfectly.

**Comment by jekh** [comment]
@Jonxxx - That is a very clever solution. Although I think it might be a bit more complicated than necessary. You can force BMP/LP to add the header pretty easily, using the LittleProxy HttpFilters objects. It's a bit more verbose than the BrowserMobProxy.addRequestFilter(...) method, but it's still pretty simple:

```java
proxy.addLastHttpFilterFactory(new HttpFiltersSourceAdapter() {
            @Override
            public HttpFilters filterRequest(HttpRequest originalRequest) {
                return new HttpFiltersAdapter(originalRequest) {
                    @Override
                    public HttpResponse proxyToServerRequest(HttpObject httpObject) {
                        if (httpObject instanceof HttpRequest) {
                            String base64auth = new String(Base64.encodeBase64("login:password".getBytes()));
                            ((HttpRequest) httpObject).headers().add(HttpHeaders.Names.PROXY_AUTHORIZATION, "Basic " + base64auth);
                            
                        }

                        return super.proxyToServerRequest(httpObject);
                    }
                };
            }
        });
```

In fact, that's probably how we're going to implement basic auth in BMP+LP, so if you would like to submit a PR adding a new ProxyAuthorizationFilter, that would help get this feature out quicker.

**Comment by toxzic** [comment]
Hi guys!

Any updates with upstream proxy auth feature?

**Comment by jekh** [comment]
None yet, but it will make it in before the 2.1.0 final release. Most likely 1 more beta before that.

**Comment by jekh** [comment]
@toxzic - 2.1.0 is out and upstream proxy Basic auth has been implemented. Feel free to reopen if you still have issues.
