### ISSUE TITLE
Capturing Network Traffic from Mobile Devices : Embedded Mode.

### ISSUE THREAD

**Issue by jatinkapoor** [lightbody/browsermob-proxy#300]
@jekh, @lightbody 
I am creating a proxy on my local system using BrowserMob Proxy Standalone mode , and I am pointing the network traffic from my mobile device through that proxy.  It is working for me in a standalone mode using the following steps.

1)	browsermob-proxy.bat -port 9090
2)	curl –X POST http://localhost:9090/proxy   {this returns the port on which the proxy listens}
 I configure the proxy address and the port returned in step 2 on my mobile device.
3)	Set up a new HAR – using -  curl -X PUT -d http://localhost:9090/proxy/8081/har
4)	Do stuff on the mobile apps.
5)	Grab the HAR / JSON data using - curl -X GET http://localhost:9090/proxy/8081/har

But in case of Browser Mob Proxy embedded mode I am not able to do so as I am not sure on which port the proxy is actually listening.  Is there a way to find out which port should I configure on my phone to start capturing network traffic from it.   <Note both my system and mobile devices are on same network.>
Following is my code –
String  PROXY_HOST = "127.0.0.1";
Proxy proxy	= new Proxy();	
ProxyServer server = new ProxyServer(9095);
server.start();			 
String proxyString = PROXY_HOST + ":" + 9095;
proxy.setHttpProxy(proxyString);
proxy.setSslProxy(proxyString);
server.newHar("mylife");

//Perform actions on Mobile Device.  In this case since it is not connected to the correct port, there is no network connectivity.
Har har = server.getHar();
HarLog log = har.getLog();
List<HarEntry> entries = new CopyOnWriteArrayList<HarEntry>(log.getEntries());
for (HarEntry entry : entries){
		System.out.println(entry.getRequest().getUrl());
}
server.stop();

When I check the – “netstat –an “on my machine I can see there are multiple sockets opened by Browser Mob Proxy. How to figure out which port should I need to connect.  

Any help would be much appreciated.

**Comment by jekh** [comment]
The method you are looking for is [BrowserMobProxy#getPort()](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java#L86). If you create the Selenium proxy object using the recommended ClientUtil.createSeleniumProxy() method, it will all be handled automatically, but you can still use BrowserMobProxy.getPort() to determine the port for non-Selenium clients.

**Comment by jekh** [comment]
Since this hasn't been updated in a while but the question has been answered, I'll go ahead and close this.

**Comment by sanjayahuja** [comment]
@jatinkapoor @lightbody , Could you please share more details here that was it possible to capture network traffic for mobile app if yes then kindly share the code.

**Comment by jekh** [comment]
I have not done this, but there's no reason you shouldn't be able to. You will need to configure your mobile app to point to your running proxy instance. Every mobile app and platform is different, so you'll need to consult the documentation for your specific platform for how to configure your proxy settings.

**Comment by sanjayahuja** [comment]
@Jekh, I have tried about code and did many work arounds but getting below error. This is working with web testing with selenium/firefox but not with appium.
 beforeMethod(com.BrowserMob.TestLinMedia)  Time elapsed: 20.628 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/internal/HasIdentity
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
