### ISSUE TITLE
High instance of "No response received" when running on a Teamcity server

### ISSUE THREAD

**Issue by TheBeardedLlama** [lightbody/browsermob-proxy#301]
Hi guys,
I've written my own wrapper in .Net to get BMP working with my Specflow tests (digression: would you like me to put it up on GitHub as there doesn't seem to be any .Net wrappers for BMP).
I recently upgraded to the new beta, in fact I had to get the latest from master as I was getting a lot of errors that were fixed in response to #285.
When I run my tests on my local, then everything is hunky dory and the proxy manages the responses as expected.
When I run them as part of our Teamcity build, then we get at least 3-4 "No response received" errors per run. There is no perceivable pattern in that it is not the same tests that always fail.
I'm not quite sure what information you require to look into this, so please give me a list of things to get and I'll be happy to oblige.

Cheers,
Steven

**Comment by TheBeardedLlama** [comment]
I have tried again with the new version and the problem is still there

**Comment by jekh** [comment]
Sorry for the late reply here. As you can imagine, this is a difficult issue to debug. Do you know how many simultaneous requests you're making? The default number of outgoing worker threads is 8, and until beta-3 it wasn't possible to change that (now there is a withThreadConfiguration(...) method). If you are making a very large number of requests, it is possible that some of the requests timed out while waiting for other requests to finish.

Is it possible for you to get the logs from the proxy to see what the exceptions were?

**Comment by TheBeardedLlama** [comment]
Ah, simultaneous requests is something I had not considered! I will have a look at that when I'm back in the office in a couple of weeks.
What logs would you like me to send? Where would I find them/turn them on/etc?

**Comment by jekh** [comment]
The logs I'd be interested in are the LittleProxy logs from the box running on the proxy server (i.e. NOT the server running the browser/other HTTP client, if that is different). 

How are you running LittleProxy? If you're including it in your app, LP will log using the application logger. If you're running it from the jar file, well... I just realized that LP doesn't initialize log4j properly when running the shaded jar. I'll put together a PR to fix that, since app logs are pretty important when troubleshooting issues.

**Comment by TheBeardedLlama** [comment]
We're running BMP using the .bat file in a windows environment, so I'm not quite sure where that fits into the options you presented... any ideas?

**Comment by jekh** [comment]
The logs are on the console where you run the browsermob-proxy.bat file. I realize this is not ideal, so I merged a change to also output to a file called `bmp.log`. If you're still using beta-3, replace the `bin/conf/bmp-logging.yaml` file on your machine with the [latest version](https://raw.githubusercontent.com/lightbody/browsermob-proxy/master/browsermob-dist/src/main/resources/bmp-logging.yaml).

I'm hoping that the log will contain the exceptions that occur when you're running on the Teamcity server, which will help narrow the investigation significantly.

**Comment by TheBeardedLlama** [comment]
Thank you for the update, I will look into that once I'm back in the office

**Comment by TheBeardedLlama** [comment]
I'm back in the office. Updated the yaml with the latest version. The log file generated fine.
However, the client's ITS geniuses have blocked uploads to github, so I will upload the file when I get home...

**Comment by TheBeardedLlama** [comment]
So I can't attach the file for some reason...

So here's a link to it on my dropbox:
https://dl.dropboxusercontent.com/u/59709160/bmp.log

**Comment by TheBeardedLlama** [comment]
Hey, does the log contain the information you require or do I need to run it again?

**Comment by jekh** [comment]
This is a rather old issue, so I'll go ahead and close it. If you still experience any issues, I'd suggest using 2.1.0. "An existing connection was forcibly closed by the remote host" generally means that the remote server closed the connection (or something in between you and the remote server).

**Comment by TheBeardedLlama** [comment]
:(
