### ISSUE TITLE
Unable to record the network calls for HTTPS pages - Chrome Browser (Using Selenium 2.47)

### ISSUE THREAD

**Issue by Manojkumar13** [lightbody/browsermob-proxy#302]
Unable to record the network calls for HTTPS pages - Chrome Browser (Using Selenium 2.47)

I need to capture the network calls via selenium webdriver in chrome browser. But i could not able to cable capture since it showing SSL connection error ("Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have.")
![upload](https://cloud.githubusercontent.com/assets/6522108/9361480/4817ce0e-46b9-11e5-94d1-54ee70b1dd93.png)

Have searched in most of the forums. But no luck.  Can someone help me out. 

Sample Code:
import java.io.FileOutputStream;
import org.browsermob.core.har.Har;
import org.browsermob.proxy.ProxyServer;
import org.openqa.selenium.By;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Test {

	public static void main(String[] args) throws Exception {

		// start the proxy
		ProxyServer server = new ProxyServer(8080);
		server.start();
		//captures the moouse movements and navigations
		server.setCaptureHeaders(true);
		server.setCaptureContent(true);

		// get the Selenium proxy object
		Proxy proxy = server.seleniumProxy();	
		
		// configure it as a desired capability
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		capabilities.setCapability(CapabilityType.PROXY, proxy);
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		
		System.setProperty("webdriver.chrome.driver",System.getenv("chromeDriver").toString());
		WebDriver driver = new ChromeDriver(capabilities);		
		// create a new HAR with the label "apple.com"
		server.newHar("test.com");	
		driver.get("https://www.google.com");
		Thread.sleep(10000);

		// get the HAR data
		Har har = server.getHar();
		FileOutputStream fos = new FileOutputStream(<Path>);
		har.writeTo(fos);		
		server.stop();
		driver.quit();

	}

}

**Comment by Qwal** [comment]
+1

**Comment by jekh** [comment]
You definitely want to be using the LittleProxy implementation, not the legacy `ProxyServer` class; see the readme on GitHub for details.

I'll go ahead and close this, but please reopen and add BMP log output if you continue to see experience this issue.

**Comment by Manojkumar13** [comment]
Thankss.. It works fine.
