### ISSUE TITLE
trouble when using launch agents

### ISSUE THREAD

**Issue by sixmanguru** [lightbody/browsermob-proxy#304]
Looking for a little advice here. I have a program (let's call it main.py) that sits on a Mac Mini server and utilizes browsermob-proxy.

I can go anywhere from the command line and run a python main.py and the program runs. It opens a broswer, gets data, closes.

If I try to run the same program from a launch agent (aka .plist), it won't run. It doesn't open a browser.

If within command line I go to browsermob-proxy/bin and run it (./browsermob-proxy), then restart the Launch Agent, the LA will now run.... of course now the problem is that now I have to leave that open and running and this will eventually get a memory error Java in about 3 days or so... thoughts?

**Comment by jekh** [comment]
I'm going to close this issue as it is pretty old and hasn't gotten any traction. Feel free to reopen if you're still having issues.
