### ISSUE TITLE
Can not restart BrowserMobProxyServer

### ISSUE THREAD

**Issue by suayipozmen** [lightbody/browsermob-proxy#306]
I start browsermob with
`BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start(0);`

`BrowserMobProxyServer.started` variable is set to true.

after test finished stop browsermob. but `started` variable is not updated to false.
`proxy.stop();`

So you cannot start proxy again but it is not running.

**Comment by jekh** [comment]
That's correct, you cannot restart BMP after it has been stopped. This is by design. Instead, create a new BMP instance and start it.
