### ISSUE TITLE
\ufffd character in network log (encoding problem)

### ISSUE THREAD

**Issue by Wu4m4n** [lightbody/browsermob-proxy#324]
Hi,
I am using selenium (python) with BrowserMob-Proxy. to get all the network activty from an flex app.
Flex use AMF to communicate to the server. (https://en.wikipedia.org/wiki/Action_Message_Format)

This is what I get using BrowserMob:

"\x00\x03\x00\x00\x00\x01\x00\x04null\x00\x03/23\x00\x00\x03\ufffd\n\x00\x00\x00\x01\x11\n\ufffd\x13Oflex.messaging.messages.RemotingMessage"

But in that is incorrect. because a few bytes are not encoding right. Because I see a lot of "\ufffd"

This should be the correct log.
\x00\x03\x00\x00\x00\x01\x00\x04null\x00\x03/26\x00\x00\x03\xB2\x0A\x00\x00\x00\x01\x11\x0A\x81\x13Oflex.messaging.messages.RemotingMessage

This is a bug? or a I am missing something in the setting?

Regards.
Nelson

PD: Sorry for my bad english.

**Comment by jekh** [comment]
What underlying browsermob-proxy implementation are you using? Is there a URL or test case you can create that will allow us to repro this issue?

**Comment by jekh** [comment]
I'm going to close since there hasn't been any update.
