### ISSUE TITLE
Basic Auth not working with Rest API

### ISSUE THREAD

**Issue by sahajamit** [lightbody/browsermob-proxy#325]
Hi,

 I have opened the BMP proxy server using 

sh browsermob-proxy -port 9090

and then started a proxy on the port 9091:

curl -X POST http://localhost:9090/proxy

Then I used the REST api to enable the basic authentication. I have user Chrome's Postman client to hit this post request.

http://localhost:9090/proxy/9091/auth/basic/the-internet.herokuapp.com/

and the request body looks like:

{"username":"admin","password":"admin"}

It return me 200 response code.

But now when I am trying to open this website "http://the-internet.herokuapp.com/basic_auth". It still shows me authentication pop-up.

When I tried the same thing with java, it worked.

Thanks,
Amit.

**Comment by jekh** [comment]
Auto auth isn't currently supported by the LittleProxy implementation (issue #271).  You can use the legacy implementation by specifying `--use-littleproxy false` on the command line, or you can use beta-2 (there was only 1 minor change to legacy in beta-3).

I'll close this since it's a duplicate.

**Comment by sahajamit** [comment]
Thanks with this flag "--use-littleproxy false" it is working fine.
