### ISSUE TITLE
How to get HAR with Safari and IE via browsermob-proxy?

### ISSUE THREAD

**Issue by vladigoal** [lightbody/browsermob-proxy#329]
{
    "log": {
        "comment": "", 
        "entries": [], 
        "version": "1.2", 
        "pages": [
            {
                "pageTimings": {
                    "comment": ""
                }, 
                "comment": "", 
                "title": "http://www.example.co.uk", 
                "id": "http://www.example.co.uk", 
                "startedDateTime": "2015-09-30T19:00:58.134+03:00"
            }
        ], 
        "creator": {
            "comment": "", 
            "version": "2.1.0-beta-2-legacy", 
            "name": "BrowserMob Proxy"
        }
    }
}

**Comment by jekh** [comment]
Is there a question here? This appears to be a snippet from a HAR file.

**Comment by vladigoal** [comment]
It is HAR, but I need HAR with captureHeaders and captureContent.

**Comment by jekh** [comment]
You need to enable the capture types you want. See [BrowserMobProxy.setCaptureTypes(...)](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxy.java#L156) or .enableCaptureTypes(...) for details.

**Comment by jekh** [comment]
This question appears to be answered, so I'll close it.
