### ISSUE TITLE
receive value is huge(impossible) in har result sometimes

### ISSUE THREAD

**Issue by chemicwepn** [lightbody/browsermob-proxy#332]
I notice sometimes when I try to generate the har with browsermob-proxy + phantomjs. Some of the receive values in the result are huge. I am use 2.1.0 beta 2 for browsermob-proxy and phantomjs 1.9.8. See example output,

{
      "pageref": "http://yahoo.com",
      "startedDateTime": "2015-10-12T15:38:44.374Z",
      "request": {
        "method": "GET",
        "url": "https://s.yimg.com:443/nn/fp/rsz/101115/images/smush/bokoharam_120x48_1444589770.jpeg.jpg",
        "httpVersion": "HTTP/1.1",
        "cookies": [],
        "headers": [],
        "queryString": [],
        "headersSize": 338,
        "bodySize": 0,
        "comment": ""
      },
      "response": {
        "status": 200,
        "statusText": "OK",
        "httpVersion": "HTTP/1.1",
        "cookies": [],
        "headers": [],
        "content": {"size": 0, "mimeType": "", "comment": ""},
        "redirectURL": "",
        "headersSize": 643,
        "bodySize": 4422,
        "comment": ""
      },
      "cache": {},
      "timings": {
        "comment": "",
        "send": 0,
        "wait": 67,
        "receive": 1783678257,
        "ssl": -1,
        "blocked": -1,
        "dns": -1,
        "connect": -1
      },
      "serverIPAddress": "206.190.60.139",
      "comment": "",
      "time": 1783678325
    }

It is  1783678257ms, about 20 days!! I am not sure where the bug is from, it could be phantomjs or browsermob proxy? Have you seen this before?

**Comment by chemicwepn** [comment]
How does browsermob proxy get the receive value? calculated or gets from phantoms?

**Comment by jekh** [comment]
@chemicwepn: I suggest using beta-3 or later, in which this issue is fixed. I'll close, but please reopen if you continue to have issues.
