### ISSUE TITLE
Url https + set chainedproxy "dynamic"

### ISSUE THREAD

**Issue by npierreyves** [lightbody/browsermob-proxy#333]
Hello,

I test the possibility of giving the destination proxy dynamically by adding a header during the call.
When I call a http url no problem but when calling a https url. I can't find the header to send for select the output proxy.

Client : 
```java
...
HttpHost target= new HttpHost("httpbin.org", 443, "https");
//or HttpHost target= new HttpHost("httpbin.org", 80, "http");
HttpHost proxy= new HttpHost("127.0.0.1", 80, "http");
RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
HttpGet request = new HttpGet("/ip");
request.setConfig(config);
request.addHeader("ChooseProxy", 1);
httpClient.executre(target, request);
...
```

MyBrowserMobProxy :
```java
...
proxyServer = new BrowserMobProxyServer(8080);
proxyServer.setChainedProxyManager((httpRequest, chainedProxies) -> {
      String idProxy = httpRequest.headers().get("ChooseProxy");
...
```

any ideas ?

Thank.

**Comment by jekh** [comment]
Currently it's not possible to MITM HTTPS requests when using a chained proxy. I'm currently working on remedying this, but I don't know when I'll be able to open that PR in LittleProxy.

**Comment by ganskef** [comment]
@jekh Please have a look at this PR https://github.com/adamfisk/LittleProxy/pull/251. It looks very good for me.

**Comment by jekh** [comment]
@npierreyves - give this a try with the latest BMP, which includes the fix @ganskef mentioned. MITM + Chained Proxy should now be working.

**Comment by npierreyves** [comment]
@jekh I tested with version BMP 2.0.1-beta-4. But in the method when I ask the value of the header "ChooseProxy" (for exemple) I did not return :(

**Comment by jekh** [comment]
This should be possible in Embedded Mode now that the `setChainedProxyManager()` method is available on the `BrowserMobProxyServer` class. The LittleProxy ChainedProxyManager will allow you to choose a chained proxy based on the headers in the request.
