### ISSUE TITLE
Embedded mode with RemoteWebDriver, how does it work?

### ISSUE THREAD

**Issue by diemol** [lightbody/browsermob-proxy#335]
Hi,

I am sorry if this has been already asked, but I went through the issues and I could not find an answer.

I am trying to use browserMobProxy (latest release, browsermob-core-littleproxy 2.1.0-beta-3 via maven), the embedded mode with RemoteWebDriver. This means:
* I have my Selenium Java code running on my machine or Jenkins
* I start browserMobProxy with:
 * ```BrowserMobProxy browserMobProxy = new BrowserMobProxyServer(); ```
 * ```browserMobProxy.start();```
* then I create a proxy with: 
 * ```Proxy seleniumProxy = ClientUtil.createSeleniumProxy(browserMobProxy);```
* and finally I add this proxy to the capability:
 * ```capability.setCapability(CapabilityType.PROXY, seleniumProxy);```
* I run it against a Selenium Grid (1 hub + 4 nodes, Ubuntu 14, with Firefox latest, Chrome 45, Selenium 2.47, Chromedriver 2.20). In the Selenium Grid (neither nodes nor hub) there is no standalone browserMobProxy installed.

I have already tried the previous code locally with Firefox and Chrome and it works. Locally means that the Selenium Java code is running on my machine and the browser too.

So, the question is, can I run the tests against the Selenium Grid using RemoteWebDriver and only with the embedded browserMobProxy? Or do I need to install a standalone browserMobProxy in a machine that is reachable for the grid (or in the grid).

If it is possible to do it only with the embedded proxy, I would be really happy if you guys could provide a simple example.

I hope the question was easy to understand,

Thank you,

**Comment by jekh** [comment]
There's no reason it shouldn't work against the grid. You'll want to make sure that the machine running your Selenium tests (workstation, jenkins box, etc.) is reachable from the grid. You may also have to override the hostname in the `seleniumProxy` object to be a hostname or IP address that is reachable from the grid.

Can you paste some logs that show the issue?

**Comment by diemol** [comment]
OK, I will ensure first those two things and I will let you know.
Thank you,

**Comment by diemol** [comment]
After ensuring that the machine running the tests is reachable, and more importantly, overriding the hostname of the proxy object, I see that it works from the Grid as well.

So, I'll proceed to close the issue then.

Thanks for your help,
