### ISSUE TITLE
Is browsermob-proxy the right choice for tunneling traffic through another proxy?

### ISSUE THREAD

**Issue by PatrickHuetter** [lightbody/browsermob-proxy#341]
I'm using selenium to crawl some websites. I also use different http-proxies for that. Some of them need authentication (credentials). This worked fine with phantomjs. Now i want to use google chrome with chromedriver but chrome doesn't support proxies with credentials (via the chrome.switches configuration).

After some research i thought i could use littleProxy to create a local proxy without credentials which tunnels the traffic to a public proxy with credentials and use the local proxy as proxy within chrome. 
That would be also possible with https://github.com/sjitech/proxy-login-automator i think but as my technology stack is mostly java based i think littleProxy would be the better proxy software for that.

I've seen that browsermob-proxy is using littleProxy and has some selenium integration. Maybe i don't need any feature of this integration but maybe this integration makes some things more easy in collaboration with selenium. So my question is: Is my intend possible like described? What would you choose? LittleProxy or browsermob-proxy?

PS. I'm crawling with multiple threads simultaneously so i have to start many local proxies on different ports. So it's a requirement for me that this is easy possible with the proxy-software.

**Comment by jekh** [comment]
Hi @PatrickHuetter. BMP does indeed use LittleProxy behind the scenes, and it contains a few convenience methods that make common tasks a lot easier (such as capturing traffic into a HAR file). The choice of which to use depends a lot on your use case: are you trying to embed the proxy in a Java application, or are you using the proxy mostly for testing/debugging purposes? And, importantly, what type of authentication with the upstream proxy do you need?

**Comment by jekh** [comment]
Since there's been no update, I'll go ahead and close this issue. Please comment if you still have questions.
