### ISSUE TITLE
Missing org/openqa/ in browsermob-dist-2.1.0-beta-3.jar

### ISSUE THREAD

**Issue by stavanmehta** [lightbody/browsermob-proxy#342]
I am trying to use browsermob-dist-2.1.0-beta-3.jar with Python. But while setting up "Class.forName("net.lightbody.bmp.BrowserMobProxyServer")" it is giving error message "java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: org/openqa/selenium/Proxy".
I checked .jar content and noticed that org/openqa/ directory is missing.

**Comment by jekh** [comment]
Can you paste the complete stack trace?

**Comment by stavanmehta** [comment]
@jekh I resolved this issue by adding Selenium Webdriver .jar to class path and then it is able to access org/openqa/selenium/Proxy.
So, even when we create a maven project if we add selenium pom as dependency it works fine. 
But what I feel is, borwsermobproxy project is already having selenium dependency and if you can package it with distributed .jar then user doesn't need to additionally add selenium jar.
