### ISSUE TITLE
The har File in Safari doesn't have any data

### ISSUE THREAD

**Issue by AlinaHeinson** [lightbody/browsermob-proxy#343]
This is my code:

        int port = 10000;
        server = new BrowserMobProxyServer();
        server.start(port);
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(server);
        //  pr.setProxyType(Proxy.ProxyType.MANUAL); 
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        driver = new SafariDriver(capabilities);

        server.newHar("myHar");
        driver.get("http://www.google.com");
        Har har = server.getHar();
        Assert.assertTrue(har.getLog().getEntries().size() > 0);

In chrome, the har file contains several entries, as expected. in Safari - it is completely empty.although the webpage opens and everything seemed fine. 

Is there some fix or workaround to get the har file to work in safari? 
I am using Safari Version 6.2.8 (8537.85.17.9.1) on OSX 10.8.5. 

Thanks,
Alina

**Comment by jekh** [comment]
It sounds like Selenium is having a problem configuring Safari to use a proxy. To test that, try configuring Safari to use the proxy using the standard Safari proxy configuration.

**Comment by jekh** [comment]
Closing this since there has been no update.
