### ISSUE TITLE
Problem of merged HAR information

### ISSUE THREAD

**Issue by digicom1978** [lightbody/browsermob-proxy#344]
Hello!

I am trying to use browsermob-proxy to generate HAR files.

My configuration is launching two instances of same spec.js, and each instance launches one IE browser with different port, and generates one har file.

However, the generated data is merged into one file.

For example, if each file is supposed to have 5 requests, then one file has 9~10 requests, and the other has 0~1 request.
With Chrome, and Firefox, it is OK. Both browsers generate a different file respectively.
Only IE merges the result into one file.

Each instance makes their own proxy to start with different port in its beforeEach function.

	beforeEach(function (done) {
                ...
		browser.controlFlow().execute(function () {
			var proxy = new Proxy();

			browser.params.proxy = proxy;
			Q.ninvoke(proxy, 'start', port) // make this port to be called dynamically
				.then(
					function (data) {
						console.log('data', data);
					}, 
					function () {
						console.log('start failed');
					});
			});

			browser.controlFlow().execute(function () {
				browser.params.proxy.startHAR( port, 'test', done);
			});
			}
		);

	});

Any advice would be appreciated.

Thanks.

**Comment by jekh** [comment]
If the HAR capture works with Chrome and Firefox but not with IE, I suspect it is an IE issue. What version of IE are you using? I know at least some (possibly all) versions of IE don't support profiles properly, and will end up using the system proxy settings for all instances of the browser.

**Comment by jekh** [comment]
Since there's been no update, I'll close this issue.
