### ISSUE TITLE
Har file only returned partial entries

### ISSUE THREAD

**Issue by BlueStalker** [lightbody/browsermob-proxy#345]
I am using selenium remote driver to do some front-end testing.  During the increasing of load, I got some error logs happened in net.lightbody.bmp.proxy.http.RequestInfo, "Got a negative receiving time ... for URL ...", And It seemed that when I call proxeServer.getHar(), the har file just returns partial entries. (comparing with normal run, there misses some entries).

Is there some known issues on this and any resolutions?

**Comment by jekh** [comment]
Can you paste the BMP logs, as well as code you use to create the proxy and some steps to reproduce? We need more information to help.

**Comment by jekh** [comment]
Since there's been no update, I'll close this issue.
