### ISSUE TITLE
Broken link to cert file

### ISSUE THREAD

**Issue by madoni** [lightbody/browsermob-proxy#362]
[SSL Support section](https://github.com/lightbody/browsermob-proxy#ssl-support) -> Install the ca-certificate-rsa.cer file in your browser ....

Looks like this file is located at https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/resources/sslSupport/ca-certificate-rsa.cer

**Comment by jekh** [comment]
It is broken! Sorry about that, thank you for noticing it. I've updated the link!
