### ISSUE TITLE
Dynamically configure upstream proxy from pac file

### ISSUE THREAD

**Issue by madoni** [lightbody/browsermob-proxy#366]
Hi,
I am currently working on a project that needs to run inside the corporate network.
As in most case, the proxy is configured using a `pac` file.
For some tests, that need to run on internally hosted sites, the requests don't need to go through the corporate proxy but at the same time there are other requests (for external scripts etc.) to externally hosted servers that utilize the proxy server.
I have configured my code to work with external sites using `chainedProxy`, but this doesn't work with internal sites. Toggling it off is not an option, as mentioned above, these internal sites reference external assets.
Is there a way for the chained proxy to use the system network settings?

I came across this project, [proxy-vole](https://code.google.com/p/proxy-vole/) that seems to be the answer, but have no idea how to configure it in the browsermob context.
Is this something that can be incorporated in the browsermob implementation?
Any direction would be appreciated!

**Comment by jekh** [comment]
It is possible to use different proxies depending on the request. The BrowserMobProxyServer class has a setChainedProxyManager(...) method, which lets you specify a LittleProxy ChainedProxyManager. Using the ChainedProxyManager you can inspect the HttpRequest and populate the Chained Proxy queue with the proxy or proxies you'd like to use for a specific request.

I don't know anything about proxy-vole, but if that library lets you discover proxy settings, you could take those settings and use them in the ChainedProxyManager to configure a ChainedProxy for BMP to use.

Hope that helps!

**Comment by madoni** [comment]
Thanks @jekh ... will give that shot!

**Comment by jekh** [comment]
Since there hasn't been an update, I'll close this issue. Please open a new issue if you have problems using the ChainedProxyManager.
