### ISSUE TITLE
modify DEFAULT_MAXIMUM_REQUEST_BUFFER_SIZE

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#372]
is there any way to modify DEFAULT_MAXIMUM_REQUEST_BUFFER_SIZE and DEFAULT_MAXIMUM_RESPONSE_BUFFER_SIZE through configuration in order to avoid modifying source code?

**Comment by jekh** [comment]
It's very easy to do through when using custom filters in embedded mode, but not when running with the REST API. What's your use case? I'm amenable to adding an option for the REST API.

**Comment by jpereira06** [comment]
I'm running embedded mode wit selenium

**Comment by jekh** [comment]
Oh great, in that case it's very easy to configure. By default, `addRequestFilter(...)` is implemented like this:
```java
    @Override
    public void addRequestFilter(RequestFilter filter) {
        addFirstHttpFilterFactory(new RequestFilterAdapter.FilterSource(filter));
    }
```
The RequestFilterAdapter has another constructor that takes a buffer size, so you just need to do this:
```java
proxyServer.addFirstHttpFilterFactory(new RequestFilterAdapter.FilterSource(filter, 16777216)); // or whatever buffer size you want
```

The solution for ResponseFilter is analogous.

**Comment by jpereira06** [comment]
Thanks!

**Comment by eyal919** [comment]
@jekh 
I'm getting the same but i'm using REST API, can you please suggest how to do it with REST API as well?
Thank you

**Comment by NelsonChang** [comment]
@jekh  I'm also interested in any solutions to custom filters size. I wonder how to do it with Rest API.
Thank you so much!
