### ISSUE TITLE
Configure browser mob to use corporate proxy

### ISSUE THREAD

**Issue by gdrajhasekarun** [lightbody/browsermob-proxy#376]
Could you please help me with sample code to set up browsermob proxy behind the corporate network.

**Comment by jekh** [comment]
For simple chained proxy configuration, you can use BrowserMobProxyServer#setChainedProxy(...). If your corporate proxy requires authentication, it's much more difficult to configure (and NTLM authentication is not supported). So we'd have to know more about your specific proxy configuration to give any more details.

**Comment by jekh** [comment]
Since there's been no update, I'll close this issue.

**Comment by manzonPanda** [comment]
Hi, I have the same problem with @gdrajhasekarun . Corporate network used proxy.pac file.  I have been struggling for almost a week now. I can't figure it out. Please help me. I really appreaciated your help. Below is my code.

BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.setTrustAllServers(true)
Set<CaptureType> captureTypes = new HashSet<CaptureType>();
captureTypes.add(CaptureType.REQUEST_BINARY_CONTENT);
captureTypes.add(CaptureType.REQUEST_CONTENT);
captureTypes.add(CaptureType.REQUEST_COOKIES);
captureTypes.add(CaptureType.REQUEST_HEADERS);
captureTypes.add(CaptureType.RESPONSE_BINARY_CONTENT);
captureTypes.add(CaptureType.RESPONSE_CONTENT);
captureTypes.add(CaptureType.RESPONSE_COOKIES);
captureTypes.add(CaptureType.RESPONSE_HEADERS);
proxy.enableHarCaptureTypes(captureTypes)
proxy.start(0);

Proxy seleniumProxy = new Proxy();
// configure it as a desired capability
seleniumProxy.setProxyType(Proxy.ProxyType.AUTODETECT);
seleniumProxy.setProxyType(Proxy.ProxyType.PAC)

System.setProperty("webdriver.chrome.driver", DriverFactory.getChromeDriverPath());
ChromeOptions options = new ChromeOptions();
DesiredCapabilities cap = DesiredCapabilities.chrome();
options.setCapability(CapabilityType.PROXY, seleniumProxy);
cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
cap.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
options.merge(cap)

WebDriver driver = new ChromeDriver(cap);
DriverFactory.changeWebDriver(driver)

proxy.newHar("myNewHar");

// get the HAR data
Har har = proxy.getHar();
