### ISSUE TITLE
Curly brace made the request host and port incorrect

### ISSUE THREAD

**Issue by thibaut-sticky** [lightbody/browsermob-proxy#378]
Hi all,

I use browsermob to listen the requests sent by a video player within a browser.
I have a particular check where I assert a domain is well called.

```JAVA
HarEntry currentEntry = ...
String domain = "mydomain.fr";
String currentUrl = currentEntry.getRequest().getUrl();
mydomain.equals(new URI(currentUrl).getHost());
```
It works fine for almost my test, but it failed for one.
After investigation, it appears that `currentEntry.getRequest().getUrl()` returned *http://mydomain.frhttp://mydomain.fr/dt?tv={c:45,d=45}*
As you can see the domain is duplicate. This wrong URL is made here:
```
net.lightbody.bmp.filters.HttpsAwareFiltersAdapter#getFullUrl
net.lightbody.bmp.util.BrowserMobHttpUtil#getHostAndPortFromRequest
```
There is a URISyntaxException due to the curly brace. And as said the comment
 >could not parse the URI, so fall through and return the URI as-is

I know curly brace is not a valid char, but would be possible to handle such case? For instance, instead of do nothing try to encode URL.

Thanks

**Comment by jekh** [comment]
Thanks, @thibaut-sticky. Regardless of how the URL is processed, there definitely shouldn't be a duplicate domain name in the getUrl() call. I'll file this as a bug and hopefully get some time before the next release to look into it.

**Comment by thibaut-sticky** [comment]
In advanced, thanks a lot :+1:

**Comment by jekh** [comment]
@thibaut-sticky - this should be fixed in master now. Let me know if you still have issues with it. Note, however, that you'll still run into issues if you try to parse a URI string with curly braces using java.net.URI. But getFullUrl() will no longer contain the duplicated scheme and host, so you can encode the string it returns according to your needs.

**Comment by thibaut-sticky** [comment]
It works perfectly, thx :+1:

**Comment by jekh** [comment]
Thank you for testing!
