### ISSUE TITLE
Error with command `mvn -DskipTests -P release` 

### ISSUE THREAD

**Issue by realisation** [lightbody/browsermob-proxy#379]
`The requested profile "release" could not be activated because it does not exist.
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
`

Is this essential? I installed maven with brew `brew install maven`

**Comment by jekh** [comment]
This is definitely a configuration issue. Unfortunately I don't have an OS X machine so I can't assist. However, I do know that the maven build does indeed work when run from the project root directory, so you probably just need to hit up google for a guide on configuring maven and java for OS X.
