### ISSUE TITLE
Rewrite response Har content

### ISSUE THREAD

**Issue by Zap4ick** [lightbody/browsermob-proxy#382]
Hello! My issue is to change json response from https site. I see it by getText(), then use setText(), and change its size by setSize and setBodySize. But It seems there is no effect and chrome receives the same old json... Is there a way?

I think maybe the point is that "response.getRawResponse().getEntity().getContentLength()" somehow has old value, but i can't rewrite it :( Or the cause is different at all?

**Comment by jekh** [comment]
What are you using to change the contents? Can you paste some code? Also need the version of BMP, etc.

**Comment by Zap4ick** [comment]
BMP 2.1.0-beta-4 and Selenium 2.50.1

`    public static class ResponseModifier implements ResponseInterceptor {

    @Override
    public void process(BrowserMobHttpResponse response, Har har) {

        String contentType = response.getHeader("Content-Type");

        if (contentType!=null && contentType.startsWith("application/json")){
            response.getEntry().getResponse().getContent().setText(respond);
            response.getEntry().getResponse().getContent().setSize(respond.length());
            response.getEntry().getResponse().setBodySize(respond.length());
            response.getRawResponse().removeHeaders("Content-Length");
            response.getRawResponse().addHeader("Content-Length", ""+respond.length());
        }
    }`

Maybe point is not in Har at all :) All I need is to change the json string in the server response.

**Comment by jekh** [comment]
I see what you're trying to achieve. A couple things will help:

First, don't use the legacy ProxyServer class. Use `BrowserMobProxy` and create an instance of `BrowserMobProxyServer`.

Second, use a filter to modify requests/responses. See the readme for details: https://github.com/lightbody/browsermob-proxy#http-request-manipulation

**Comment by Zap4ick** [comment]
Thanks! It turn out to be far easier than I thought :)

**Comment by jekh** [comment]
@Zap4ick - Glad to hear. Were you able to successfully rewrite the body contents?

**Comment by Zap4ick** [comment]
Yes, I just added a filter and rewrited text content.
