### ISSUE TITLE
Was page deletion implemented? 

### ISSUE THREAD

**Issue by axtens** [lightbody/browsermob-proxy#383]
I noticed that the idea of page deletion was mooted some time ago. Was it implemented? If so, could the documentation on the home page be updated appropriately?

I'm asking because I have a proxy running, a browser open, and a large number of requests passing through over a period of days, each being given an incrementing pageRef. I foresee running out of memory and the proxy manager falling over.

**Comment by axtens** [comment]
Ok, with a bit of fiddling I've realised that 

    var fr = new CSFluentREST("http://localhost:8080/proxy/" + CSSettings.Item("CSPort") + "/har");
    fr.Verb("PUT").Tail("captureContent=true&initialPageRef=" + CSSettings.Item("CSinitialPageRef"));
	HAR = fr.Send().ToString();

is giving me what I want and that filling up the memory isn't going to happen.

Feel free to close/delete this ticket or put it lights as an example of the questions you get when people don't RTFM closely.

**Comment by jekh** [comment]
Deleting by page ref hasn't been implemented (it'll be part of the forthcoming REST API update), but as you note there are a few work-arounds that cover most use cases. You can also use newHar() if you want to completely clear the HAR capture (the method also returns the existing HAR file if you want to save it away somewhere/parse it using a JSON parser).
