### ISSUE TITLE
Documentation: All options in table

### ISSUE THREAD

**Issue by axtens** [lightbody/browsermob-proxy#384]
Please could all GET/PUT/POST/DELETE options be spelled out on the front page. I found it confusing that part of the documentation for the REST interface is described using curl and the remainder as a table of verb-tail/body-description.

**Comment by jekh** [comment]
I agree and I support this completely -- pull requests welcome!

**Comment by axtens** [comment]
Hmmm ... not sure how to do that. Can you post a link to a howto?

**Comment by jekh** [comment]
I don't know about a howto, but googling for github-flavored markdown should give you all the info you need about markdown tables.

**Comment by jekh** [comment]
This was implemented in PR #459, so I'll close this issue.
