### ISSUE TITLE
Rest API for response interceptor

### ISSUE THREAD

**Issue by stavanmehta** [lightbody/browsermob-proxy#389]
HI, 
With little proxy we can use filtering criteria for Request and Response interceptors using Java.
Is there any way where we can use filtering criteria with REST API as well.
Because, we are using python and accessing browsermob features using REST API and I have a scenario like, when I load url, it makes bunch of request, but I just want to intercept response for  particular request.
If it is not available, can you please point me where I can add new method which can support filtering criteria for REST API.

Thanks!
Stavan

**Comment by jekh** [comment]
Yes, you can create Javascript interceptors using the REST API. There are examples in the readme, and a few more advanced Javascript filters in the `FilterTest` class.
