### ISSUE TITLE
Start proxy on each node of grid

### ISSUE THREAD

**Issue by Zap4ick** [lightbody/browsermob-proxy#392]
Hello again!
Is there a way to start BMP locally on each node of selenium grid? I need every browser instance to communicate with local running BMP. It seems that BMP starts on the main machine and all the nodes connect with it. But I need unique response modifications for every test I run. 

I've found some sort of solution in the internet:

`String ipAddress = new NetworkUtils().getIp4NonLoopbackAddressOfThisMachine().getHostAddress();
                        int port = 8071;
                        proxy = ClientUtil.createSeleniumProxy(BrowserMobProxyServerEntity.getProxyServer());
                        proxy.setHttpProxy(ipAddress+":"+port);`

Now it runs like this (2 tests on 2 nodes):
`INFO: Starting proxy at address: 0.0.0.0/0.0.0.0:0
Feb 29, 2016 4:45:16 PM org.littleshoot.proxy.impl.DefaultHttpProxyServer doStart
INFO: Proxy listening with TCP transport
Feb 29, 2016 4:45:16 PM org.littleshoot.proxy.impl.DefaultHttpProxyServer doStart
INFO: Proxy started at address: /0:0:0:0:0:0:0:0:2115`

But it seems it doesn't work properly: one test gets the response filtered by proxy of another test rule.

Another issue i see on grid: node-running test can't see a picture from 3rd-party site. Have no idea and maybe the problem is somewhere else not in BMP, but it runs good locally. Maybe there is something I don't understand yet.

Thanks!

**Comment by jekh** [comment]
This is really more of a Selenium grid question; BMP is capable of running on any machine that has a Java 7+ JVM. What I've seen others do is run BMP where the test (surefire/failsafe/etc.) is running and set the browser's proxy config to point to the test machine, thus routing all HTTP traffic back through the test machine. If you need strict separation between tests, you can run one proxy per test, which isn't ideal but should work (subject to resource constraints).

**Comment by jekh** [comment]
Since this appears to be resolved, I'll close the issue.
