### ISSUE TITLE
error: [Errno 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by vinaybond** [lightbody/browsermob-proxy#394]
I am getting error while using browsermob proxy with robotframework:

This is my request. 
PUT /proxy/8090/har (my BMP process is running on 8080 on my localost)

Error message:
error: [Errno 10053] An established connection was aborted by the software in your host machine

Why BMP has terminated the connection? 

Please let me know if you need any detail.

**Comment by jekh** [comment]
Please don't comment on multiple issues simultaneously to discuss the same problem. Closing in favor of the existing issue.
