### ISSUE TITLE
mimeType is missing

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#395]
After updating to "2.1.0-beta-4" the attribute "response.content.mimeType" is not always being added. It causes an error when reading har with "softwareishard" parser. 

For example, for  http://vikinguard.com, I get the following error:
"log.entries[154].response.content.mimeType	 	is missing and it is not optional"

If for the missing entries I add manually a mimeType, for example text/plain, it works properly.

Thanks!

**Comment by jekh** [comment]
Interesting. Is the `response` an error response? Looking at the code, mimeType should always be populated with a default value if none is specified, but for error responses (connection timeout, etc.) this may not be happening.

**Comment by jpereira06** [comment]
No, the response is not an error response. In my particular case (vikinguard.com), the response nodes without mimeType belong to zopim keep-alive.

Please find attached a sample, where the response nodes without mimeType are marked as "status":333 for easy finding. Please note that default "mimeType":"text/plain" was manually added:

"response":{"status":333,"statusText":"OK","httpVersion":"HTTP/1.1","cookies":[],"headers":[{"name":"Date","value":"Mon, 07 Mar 2016 17:08:01 GMT"},{"name":"Connection","value":"keep-alive"},{"name":"Content-Length","value":"0"}],"content":{"size":0,"comment":"","mimeType":"text/plain"},"redirectURL":"","headersSize":101,"bodySize":0,"comment":""}



[vikinguard.har.zip](https://github.com/lightbody/browsermob-proxy/files/161752/vikinguard.har.zip)

**Comment by jekh** [comment]
Ah okay, thanks for the info. I'll do some debugging and see if I can get a fix in before the next release.

**Comment by jekh** [comment]
@jpereira06 - this should be fixed in master now. Let me know if you still have an issue with it! Thanks for reporting this.

**Comment by jpereira06** [comment]
fixed. Thanks!

**Comment by jekh** [comment]
Thanks for testing!
