### ISSUE TITLE
REST API wrong JSON processing

### ISSUE THREAD

**Issue by bobtuna** [lightbody/browsermob-proxy#400]
I'm writing some NodeJS API client for your awesome utility. I detected JSON parse bug in "headers change" (POST /proxy/[port]/headers) API method.

When I am sending correct JSON object, browsermob-proxy generates exception.
JSON object is `{"version" : 1}`
Exception is `ClassCastException - "java.lang.Integer cannot be cast to java.lang.String`

When I am sending other correct JSON object, browsermob-proxy works perfectly.
JSON object is `{"version" : "1"}`.
Both of this objects are valid JSON objects. As you can see, the difference in using of quotes invokes error.

**Comment by jekh** [comment]
You're right that they're both valid JSON objects, but only the string form conforms to the REST API's contract. JSON numeric types don't make sense when adding HTTP headers, which are all strings. Convert the values to string types and that should solve your problem.

**Comment by bobtuna** [comment]
Thank you.
