### ISSUE TITLE
error: [Errno 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by vinaybond** [lightbody/browsermob-proxy#403]
I am using browsermob proxy with robotframework. I am starting the browsermobproxy and getting a port to start a proxy. I am starting a browser on proxy port give by BMP. For some tests I am getting error message

`error: [Errno 10053] An established connection was aborted by the software in your host machine. `

I tried using timeout

requestTimeout=-1&readTimeout=0&dnsCacheTimeout=0&connectionTimeout=0
/proxy/${port}/timeout

Here ${port} is given BMP on which proxy is created. This is the error I got

`20160314 12:07:38.811 :  FAIL : Request should have succeeded, but was "500 Exception [IllegalStateException - "LittleProxy implementation does not allow changes to connect timeout after proxy has been started"] thrown by event method [public com.google.sitebricks.headless.Reply net.lightbody.bmp.proxy.bricks.ProxyResource.timeout(int,com.google.sitebricks.headless.Request)]  at net.lightbody.bmp.BrowserMobProxyServer.setConnectTimeout(BrowserMobProxyServer.java:870) (See below for entire trace.)".`

I tried using ${port} as 8080 on which BMP application is running but I gave me 404. 

Can someone help here finding out what is going wrong?

-Vinay

**Comment by jekh** [comment]
Please stop opening this same issue over and over. Discussion can continue in #303.
