### ISSUE TITLE
browsermob-proxy:jar:2.1.0-beta-4  not deployed to Maven Central

### ISSUE THREAD

**Issue by dzieciou** [lightbody/browsermob-proxy#405]
Can you please deploy newest version to Maven Central?

http://search.maven.org/#artifactdetails%7Cnet.lightbody.bmp%7Cbrowsermob-proxy%7C2.1.0-beta-4%7Cpom

lists only
* browsermob-proxy-2.1.0-beta-4.pom
* browsermob-proxy-2.1.0-beta-4.pom.asc

and no jars

**Comment by jekh** [comment]
To the contrary, beta-4 is most definitely available on Central. Please see the README displayed at the Github page for usage instructions.
