### ISSUE TITLE
Response Interceptor API call returning 400 with no error message

### ISSUE THREAD

**Issue by AutomatedTester** [lightbody/browsermob-proxy#413]
When upgrading the Python library from B2 to B5 my tests for the interceptor have started failing and returning `400` codes but no meaningful message to say what is going on.

Tests that are failing https://github.com/AutomatedTester/browsermob-proxy-py/blob/master/test/test_client.py#L171

Which calls 

https://github.com/AutomatedTester/browsermob-proxy-py/blob/master/browsermobproxy/client.py#L196

Please can you give me hints on what is wrong here?

**Comment by jekh** [comment]
In beta-4, the default implementation in the standalone/command-line mode changed from the legacy Jetty-based proxy to littleproxy. LP's filters are different from the legacy interceptors, so the REST API endpoint for Javascript filters has changed as well, from /interceptor/... to /filter/... There's a brief synopsis on the README page here: https://github.com/lightbody/browsermob-proxy#rest-api-interceptors-with-littleproxy

I highly recommend using the LP implementation and the new filters. For one thing, the new filters actually work, unlike the old interceptors that were unreliable at best.

**Comment by AutomatedTester** [comment]
I have updated the code in the python code to handle this. Thanks for this.
