### ISSUE TITLE
Bandwidth limit issues with REST API

### ISSUE THREAD

**Issue by Divii** [lightbody/browsermob-proxy#416]
Using  2.1.0-beta-4, specifying --use-littleproxy true, I'm unable to utilize the REST API 

> PUT /proxy/[port]/limit

to limit the bandwidth through the proxy.

`    response = HTTParty.put("#{@browsermob_url}/#{@browsrmob_proxy_port}/limit?downstreamKbps=2&upstreamKbps=2")
`

With the above code, I navigate to [http://www.speedtest.net/](http://www.speedtest.net/), confirm the proxy is in place via the advanced browser network settings, and run the test by clicking the 'Begin Test' button.

The results of the test show that limiting is not occurring.

**Comment by jekh** [comment]
Speedtest.net uses flash, which almost assuredly is not using HTTP requests to test your speed. Try navigating to another site that has a lot of resources to see if it is loading slowly, as expected.

**Comment by jekh** [comment]
Since there's been no update, I'll close this issue.
