### ISSUE TITLE
getPostData Always Null

### ISSUE THREAD

**Issue by baclark774** [lightbody/browsermob-proxy#417]
I have several log requests to retrieve body text data from requests. But whenever I call:

proxyServer.getHar().getLog().getEntries().get(0).getRequest().getPostData();

It always throws a NullPointerException on the getPostData() call, even when there's valid request data being sent.

**Comment by baclark774** [comment]
Also wanted to note that when I do a request filter the data is readily available. Only not available via the log in the getPostData() call.

proxyServer.addRequestFilter((request, contents, messageInfo) -> {
			if (request.getUri().contains(beaconUrl)) {
        		String beaconJson = contents.getTextContents();
        	}
            return null;
        });

**Comment by jekh** [comment]
Did you enable HAR capture and set the REQUEST_CONTENT CaptureType? By default the HAR only captures headers and cookies, to avoid consuming too much memory.

In any case, calling getPostData() should not throw a NPE. Can you paste the stack trace?

**Comment by baclark774** [comment]
Thanks @jekh That was indeed the case. I had my capture type set to RESPONSE_CONTENT and not request. That solved it. But it does appear that it throws a NPR in the event that a user doesn't set that value. The stack is just a NPR on any line where the user calls getPostData.
