### ISSUE TITLE
postData is null for every POST request

### ISSUE THREAD

**Issue by SupersonicShiran** [lightbody/browsermob-proxy#425]
Hey,

When I'm setting the ProxyServer I'm setting HarCaptureTypes of REQUEST_CONTENT and RESPONSE_CONTENT, but the postData I receive is always null and I don't know why.
This is how I'm setting the ProxyServer:

net.lightbody.bmp.BrowserMobProxy mProxyServer = new BrowserMobProxyServer();
mProxyServer.start(8888);
mProxyServer.setHarCaptureTypes(CaptureType.REQUEST_CONTENT);
mProxyServer.setHarCaptureTypes(CaptureType.RESPONSE_CONTENT);

Then I go through all the entries in the Har file:

Har har = mProxyServer.getHar();
            if (har != null) {
                for (HarEntry entry : har.getLog().getEntries()) {
                    if (entry.getRequest().getPostData() != null) {
                        System.out.println(entry.getRequest().getPostData().getText());
                    }
                }
            }

I'm using the latest version of BrowserMob (beta 5). When I tried one of the old versions (beta 1), I was able to get the post data. Can you please advise what should I do?

Thanks!

**Comment by jekh** [comment]
Every call to setHarCaptureTypes replaces the CaptureType with whatever you set it to. You could either use enableHarCaptureType() instead of setHarCaptureType, or set multiple capture types in the same call with setHarCaptureType(REQUEST_CONTENT, RESPONSE_CONTENT).

That should do it for you!

**Comment by p00j4** [comment]
@SupersonicShiran : even I had face similar issue, somehow I guess "setHarCaptureTypes...." are broken now.
this worked for me:
```
 HashSet<CaptureType> enable = new HashSet<CaptureType>();
enable.add(CaptureType.REQUEST_CONTENT);
enable.add(CaptureType.RESPONSE_CONTENT);
 mProxyServer.enableHarCaptureTypes(enable);
```

**Comment by jekh** [comment]
No, setHarCaptureTypes works exactly as documented. See the javadoc and/or the conversation in this thread.

I'll close this issue, since it's resolved now.
