### ISSUE TITLE
Change headers on HTTP reponse through ReponseFilter

### ISSUE THREAD

**Issue by rfpe** [lightbody/browsermob-proxy#426]
Hi,

I would like to change the content-type of a response using a ReponseFilter. 
My implementation looks like this:

```java
proxy.addResponseFilter(new ResponseFilter() {
            @Override
            public void filterResponse(HttpResponse response, HttpMessageContents contents, HttpMessageInfo messageInfo) {

                if (contents.getContentType().equals("application/pdf")) {
                       //I would like to do:
                       contents.setContentType("text/plain");
                 }
...
}
```
Is there any way to accomplish that?
I am using the embedded Java API version 2.1.0-beta-5.

**Comment by jekh** [comment]
Yes, this is quite simple: the `response` object in the filter method contains a `.headers()` method, which allows you to examine and set the headers.

**Comment by rfpe** [comment]
Thank you @jekh! For some reason I didn't notice the `.headers()` method. That worked for me.
