### ISSUE TITLE
No Request Parameters and Response value in Har file 

### ISSUE THREAD

**Issue by p00j4** [lightbody/browsermob-proxy#430]
All I receive is har file with all requests & responses with their corresponding headers but not the Posted parameters and the response value.

Expected: should receive the Parameters passed in request and the response received too, there is har view for 1 of my request:
![image](https://cloud.githubusercontent.com/assets/12966925/14629485/b254ed4e-0624-11e6-9454-e4fae0adc193.png)

I'm using it with selenium, after I reach at the exact page, I store Har like this:
Here is my tried code:
```
Har har = proxyServer.getHar();
FileOutputStream fos = new FileOutputStream(filePath);
har.writeTo(fos);
```
Is  there any variation required to capture the posted payload too?

**Comment by abhishekswain** [comment]
You need to mention what the proxy server (BrowserMobProxy) needs to/have to capture.
Please try with this: (for example)
```
   BrowserMobProxy proxy = new BrowserMobProxyServer();
   proxy.start ( 0);
   HashSet<CaptureType> enable = new HashSet<CaptureType>();
   enable.add(CaptureType.REQUEST_HEADERS);
   enable.add(CaptureType.REQUEST_CONTENT);
   enable.add(CaptureType.RESPONSE_HEADERS);
   proxy.enableHarCaptureTypes(enable);
```

```
enable.add(CaptureType.REQUEST_CONTENT);
enable.add(CaptureType.RESPONSE_CONTENT);
```
These two would capture the payload.

**Comment by p00j4** [comment]
@abhishekswain : yes it helped, thanks. However the file becomes too huge to open and watch, i'm sure there should be a way where I can specifically filter & write only specific calls on file in code, any link to such functions or classes?

**Comment by shahp00ja** [comment]
closing as it works

**Comment by p00j4** [comment]
closing as it works with suggested solution, @jekh : please let me know if I can raise PR to document it, it can save a lot of time for new folks
