### ISSUE TITLE
How to filter/parse har object while receiving itself

### ISSUE THREAD

**Issue by p00j4** [lightbody/browsermob-proxy#431]
https://github.com/lightbody/browsermob-proxy/issues/430#issuecomment-211820248
This returns huge file which is not useful for my case, I want to track only specific request urls. Using which class or functions I can filter these while doing .getHar() itself I get only specific document.
```
Har har = proxyServer.getHar();
FileOutputStream fos = new FileOutputStream(filePath);
har.writeTo(fos);
```

I saw similar thing in https://github.com/lightbody/browsermob-proxy#http-request-manipulation
But wondering how can I integrate same with my above code ?

**This is what I tried:** but I wanted more neat way even before receiving the 'har' object
```
Har har = proxyServer.getHar();
for (HarEntry entry : har.getLog().getEntries()) {
          if (entry.getRequest() != null ) {

				HarRequest request = entry.getRequest();
				String requestUrl = entry.getRequest().getUrl();
				if(requestUrl.contains("MATCHING_CRITERIA")){
					System.out.println(requestUrl);
				         // do blah blah
						}
					}

				}
			}
		}
```

**Comment by jekh** [comment]
My suggestion would be to filter the HAR yourself. You could try to:
- Manipulate the Har object by removing unwanted entries
- Write the HAR to a JSON file and use a third-party utility to manipulate the JSON

BMP doesn't support HAR filtering natively, as it's quite specific to particular use cases.

**Comment by p00j4** [comment]
yes thanks @jekh  makes sense, however it was very useful to have native support since in that case the saved har file is light weight to open and so saves time. Though Yes I completely understand you point of view so yes I have written such parser for my case
