### ISSUE TITLE
Unable to compile from source using maven

### ISSUE THREAD

**Issue by rushi245** [lightbody/browsermob-proxy#438]
Tried to build from source using maven command.
Got following error while building.

[ERROR] Failed to execute goal on project browsermob-core-littleproxy: Could not resolve dependencies for project net.lightbody.bmp:browsermob-core-littleproxy:jar:2.1.0-beta-7-SNAPSHOT: Failure to find net.lightbody.bmp:browsermob-core:jar:tests:2.1.0-beta-7-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

Attaching complete maven log for reference.
[mavenCompile.txt](https://github.com/lightbody/browsermob-proxy/files/234570/mavenCompile.txt)

**Comment by jekh** [comment]
You need to build from the root of the project, not from a subdirectory. See the build instructions at the bottom of the readme file.

**Comment by zrks** [comment]
![image](https://cloud.githubusercontent.com/assets/7746021/14917341/38e80878-0e27-11e6-94d9-daa6c925018f.png)

**Comment by zrks** [comment]
and when adding suggested dep:
![image](https://cloud.githubusercontent.com/assets/7746021/14917506/0afd3626-0e28-11e6-9d97-22f8ea770aeb.png)

**Comment by jekh** [comment]
@zrks - Not sure what you're up to there, but the steps to build from source are pretty simple: First `git clone https://github.com/lightbody/browsermob-proxy.git`, then `mvn clean install -P release`. No changes or manual alterations necessary.

**Comment by jekh** [comment]
Since the build works consistently on Windows and Linux, including in our travis-ci environment, I'm going to close this. I don't have an OS X machine to test on, but I can't see any reason why there would be issues in that environment. If anybody has any OS X-specific problems, feel free to reopen.
