### ISSUE TITLE
BrowserMob 2.1.0-beta-6 jar missing in Maven Central repo

### ISSUE THREAD

**Issue by dzieciou** [lightbody/browsermob-proxy#440]
If you look into http://repo1.maven.org/maven2/net/lightbody/bmp/browsermob-proxy/2.1.0-beta-6/ you will find there is no JAR for BrowserMob 2.1.0-beta-6 version.

Where should I look for it?

**Comment by jekh** [comment]
The artifact name hasn't changed since beta-5. Take a look at the readme file on the github page to determine which artifact you need (probably browsermob-core-littleproxy).
