### ISSUE TITLE
Proxy autoAuthorization

### ISSUE THREAD

**Issue by blink2004** [lightbody/browsermob-proxy#441]
Hi!

Try authorization with BMP. But not actions. Basic auth window didn't fill login and password
Code:
  BrowserMobProxy proxy = new BrowserMobProxyServer();
  proxy.autoAuthorization("domain", "authLogin", "authPass", AuthType.BASIC);
  proxy.start(0);

**Comment by jekh** [comment]
If I follow you correctly, it sounds like you're expecting a window to be filled with a username and password? Auto Basic Auth simply adds the basic auth header, it doesn't fill in any window with a username and password.

**Comment by dmytrocx75** [comment]
jekh, could you give me an example of the string to put in "domain"?
I tried to write there "ru", "wolf.*", "wolf", "", but got no effect - authorization is not passed.
