### ISSUE TITLE
browsermobProxy with htmlunitdriver returns a blank page if requested url has query string

### ISSUE THREAD

**Issue by jayantsarda** [lightbody/browsermob-proxy#442]
Hi , My Setup:
browsermob version: 2.0.0
htmlunitdriver version: 2.20
httpclient version: 4.5
url under test: https://www.google.com/search?q=webdriver&gws_rd=ssl
capabilities: capabilities.setJavascriptEnabled(true);

When i try to use driver.get(url) , the page source returned is blank

the same code work fine with proxy if i remove the query string. 

could this be a bug?
Note: Chrome and Firefox everything works correctly

**Comment by jekh** [comment]
@jayantsarda: You definitely do not want to use version 2.0. Use the latest 2.1 beta (currently 2.1.0-beta-7) with the `browsermob-core-littleproxy` module.

**Comment by jekh** [comment]
2.0.0 is completely unsupported now. Even using browsermob-core and ProxyServer under 2.1, SSL support is poor. The new interface using the browsermob-core-littleproxy module is the only fully supported way to intercept SSL traffic.

If you're stuck with 2.0.0, I'm afraid you're out of luck.
