### ISSUE TITLE
Browser mob proxy not working properly with Selenium RemoteWebDriver 

### ISSUE THREAD

**Issue by prakashsarav7** [lightbody/browsermob-proxy#446]
Hi Team,

I need to run tests parallely in Selenium Grid in Saucelabs which will be triggered from Jenkins. The proxies of the hub and node will not be known in prior. I'm using the following code.

	BrowserMobProxy proxy = new BrowserMobProxyServer();
	proxy.start(0);
	
	//get the Selenium proxy object
	Proxy selProxy = ClientUtil.createSeleniumProxy(proxy);
	DesiredCapabilities capabilities = new DesiredCapabilities();
	
	/**
	* Setting other capabilities 
	*/
	
	capabilities.setCapability(CapabilityType.PROXY, proxy);
	WebDriver driver = SeleniumFactory.createWebDriver(capabilities);

The browser gets launched but its not loading any pages as it overrides the system proxy settings with the proxy of the browser mob proxy instance. If I change the webdriver proxy instance explicitly, the browsermob proxy instance no more listens to the requests and responses as the webdriver and browser mob proxy instance will run on different ports.
I tried the same from my machine with Sauce connect which also gave the same result. Can I get a detailed solution and sample working code for the same ?

**Comment by prakashsarav7** [comment]
Hi,
Any updates? Please help me on this.

**Comment by jekh** [comment]
Have you reviewed the steps in the README? https://github.com/lightbody/browsermob-proxy#using-with-selenium

**Comment by mpanin** [comment]
I believe that problem here is in the fact that webdriver is being created on remote instance, however proxy is local.
Solution is to use REST API and standalone proxy instance.

**Comment by jekh** [comment]
That sounds like the right solution to me. I'll close this issue.

**Comment by schmidtkp** [comment]
@mpanin Could you elaborate on use of REST API and standalone proxy instance? I see this as a chicken-n-egg problem. If I need to set a Proxy for my target host:port that I have to test against, but first have to set it to a BMP running on a remote selenium node, I won't know what the remote host the Selenium Hub has delegated the test to, therefore, I have no idea where to make the REST API call to first. Further, I then would need to tell BMP to use my creds and pass that auth header downstream to the targeted proxy host:port I really need to hit.

**Comment by mpanin** [comment]
@schmidtkp oh, it's been quite awhile since I had to use browsermob proxy for such things. Here is the thing: when you're running proxy as standalone it becomes a separate entity, meaning you're just starting proxy instance on some machine and expose it externally. Proxy is always there, it's always running, every application could use it since it's independent. Now the only thing you need to do is to provide all the properties to WebDriver and control proxy behavior through REST calls described in REST API section. Also, if you're running ChromeDriver consider examining performance logs - they actually could provide a lot of useful info about requests being made, maybe you'll find using proxy redundant.

**Comment by schmidtkp** [comment]
@mpanin Thanks for the info. The key for me will be if BMP via the REST API's will allow me to set a "proxy chain". If this can be accomplished, then I can set my DesiredCapabilities to use the local instance of the proxy already running on the remote node, create the RemoteWebDriver, after successful creation of the RemoteWebDriver/test session, extract the host the test will run on, call the BMP REST API to set the downstream targeted real proxy to be used (proxy-chain). If I could do that, this would be reasonable solution.

**Comment by Abhinavsoni** [comment]
HI All,

I am also facing the same issue.
I am trying to run tests from my local system and using a selenium grid hub setup.
Browsermob works fine when I run my tests locally, it captures HAR perfectly fine.
But when i run my tests in Grid , the browser opens in node but the URL does not load .
Any help would be highly appreciated.

Thanks
