### ISSUE TITLE
Problem using setChainedProxy

### ISSUE THREAD

**Issue by troncho10** [lightbody/browsermob-proxy#447]
Hello I tried to use the chained proxy option with no luck.
The server just does nothing.
I know the server works because it can blacklist and whitlist websites that worked for me.
but when I set chained proxy even manually with inetsocketaddress.
It just does nothing.
I checked my ip with www.whatismyip.com
and nothing
what am i doing wrong
Thanks

server = new BrowserMobProxyServer(Port); 
		
	    while(true)
	    {
	    Double RandomDouble=Math.floor(Math.random() * salesData.length-1) + 0;
	    int Random=RandomDouble.intValue();
	    String IP;
	    int PORT;
	    IP=salesData[Random].substring(0, salesData[Random].indexOf(":"));
	    PORT=Integer.parseInt(salesData[Random].substring(salesData[Random].indexOf(":")+1));
	    InetSocketAddress Address = new InetSocketAddress(IP, PORT);
	    System.out.println(IP);
	    System.out.println(PORT);
	    if(testConnection(IP))
	    {
	    	server.setChainedProxy(Address);
	    	server.start();
	    	break;
	    }

**Comment by jekh** [comment]
The way you're assigning the chained proxy address is a bit confusing, but as long as a proxy is listening at the InetSocketAddress you specify, calling setChainedProxy does work. Perhaps the address you're setting it to isn't what you think it is?
