### ISSUE TITLE
Issue with Bandwidth Limit

### ISSUE THREAD

**Issue by rushi245** [lightbody/browsermob-proxy#450]
Hi Guys,

I am not able to use Bandwidth limit feature of Browsermob.
Following is my code.

	BrowserMobProxyServer 	proxy = new BrowserMobProxyServer(Port);
    	try {
			proxy.setMitmManager(new CertificateSniffingMitmManager());
		} catch (RootCertificateException e) {
			e.printStackTrace();
		}		
    	proxy.setReadBandwidthLimit(512000);
    	proxy.setWriteBandwidthLimit(512000);

I am getting still actual speed when I check with speedlimit.net.
Am I missing something? Can someone suggest?

**Comment by jekh** [comment]
BMP is an HTTP proxy and so only works on HTTP requests, not direct connections established by Flash or any other applications. There may be HTML speed tests you can try, or just visit a high-bandwidth website and compare page load times.

You shouldn't be eating the RootCertificateException either, but that's a separate problem.

**Comment by rushi245** [comment]
Thanks jekh for you reply.
