### ISSUE TITLE
Couldn't capture browser mob proxy performance data in sauce labs

### ISSUE THREAD

**Issue by ManiKishore** [lightbody/browsermob-proxy#456]
Hi Team,

With the help of doc: https://support.saucelabs.com/customer/portal/articles/2005368-browsermob-with-sauce-connect-4 done below steps:

1. Starting browser proxy-- E:\browsermob-proxy-2.1.0\bin> **browsermob-proxy --port 9000**
2. Creating new port instance In the other cmd: **C:\Users\xxxxxxx>curl -X POST http://localhost:9000/proxy -d port=9001**
3. Connecting sauce connect: **E:\sc-4.3.15-win32\bin>sc -u <username> -k <authkey> -v --pac file://E:/sc-4.3.15-win32/bin/browsermob.js --logfile debuglog.txt**

_browsermob.js:_
**function FindProxyForURL(url, host) {
    if (shExpMatch(host, "*.miso.saucelabs.com") ||
        shExpMatch(host, "saucelabs.com")) {
        // KGP and REST connections. Another proxy can also be specified.
        return "DIRECT";
    }
    // Test HTTP traffic, route it through the local BrowserMob proxy.
    return "PROXY localhost:9001";
}**

Once done above steps configuration in my local, I started trigger the test from local to sauce labs, I couldn't launch the browser: inside my test I called 

BrowserMobProxyServer browserMobProxy = new BrowserMobProxyServer();
browserMobProxy.start();
Proxy proxy = ClientUtil.createSeleniumProxy(browserMobProxy);
WebDriver driver = WebDriverCreator.getDriverWithProxy(browser, proxy); //inside this method adding proxy to chrome remote web driver capability.
browserMobProxy.newHar();

// performing test navigation from login to logout

//finally calculating browser mob proxy values:
Utils.printHarData(browserMobProxy.getHar());
browserMobProxy.stop();

Getting all values as 0, due to url not launch::
Call count : 0 
Size : 0.0 MB 
Total load time : 0 seconds

So please suggest how we can obtain browser mob proxy HAR value using REST API for this selenium remote web driver test cases.[we have around 50 test cases, we need to capture performance data separately for each test case ]

[sauceconnectlog.txt](https://github.com/lightbody/browsermob-proxy/files/270781/sauceconnectlog.txt)

**Comment by jekh** [comment]
I don't know anything about sauce labs, so I can't help with that. But looking at your code, it appears you are both starting a standalone proxy and an embedded mode proxy. You want one or the other, not both. See the readme for information on setting up the proxy in either mode.
