### ISSUE TITLE
Rest API GET limit issue

### ISSUE THREAD

**Issue by nehat09** [lightbody/browsermob-proxy#458]
Hi  Team
I was trying out the browsermob's REST API for 2.1.0 release. I followed the instructions to start and create a new proxy:
$ sh browsermob-proxy -port 9090
...
$ curl -X POST -d 'port=9099' http://localhost:9090/proxy

Then i tried setting the limits by the request:
PUT localhost:9090/proxy/9099/limit?downstreamKbps=512&upstreamKbps=512&downstreamMaxKB=1024&upstreamMaxKB=1024

But when i try to get the limits, the returned values are 0.
GET localhost:9090/proxy/9099/limit    --> returns
{
  "maxUpstreamKB": 0,
  "remainingUpstreamKB": 0,
  "maxDownstreamKB": 0,
  "remainingDownstreamKB": 0
}

When i follow the same steps for browsermob 2.1.0-beta2 and beta6, i get the correct values from the GET request. Can anyone explain the difference in behavior? Which is the expected behavior?

**Comment by jekh** [comment]
Thanks for reporting this, @nehat09. This should now be resolved by #467. I do want to point out that the "remainingUpstream" and "remainingDownstream" fields are no longer informative with the default LittleProxy implementation. Let us know if you still have issues with this. Thanks!
