### ISSUE TITLE
How can I set log limit for browsermob-proxy

### ISSUE THREAD

**Issue by xmhubj** [lightbody/browsermob-proxy#460]
Hi,

In my test with www.newsobserver.com website, I happened to find that BMP captures more than 50,000 HTTP entries in HAR file. This is a rare case, I cannot reproduce it anymore. But I want to set a limit for HTTP entries which can be recorded by BMP.

When I try www.newsobserver.com with Firebug, I can see a message reported by Firebug "Firebug's log limit has been reached. 18 entries not shown".  Is it possible to set a limit like this with BMP?

![newsobserver](https://cloud.githubusercontent.com/assets/15373664/15464445/f38c08cc-2101-11e6-9bbe-f8c15d7f1d2f.jpg)

**Comment by jekh** [comment]
No functionality like this exists in BMP at present, but you can clear the HAR file at any time by calling newHar().
