### ISSUE TITLE
Socks support

### ISSUE THREAD

**Issue by jigarladhava** [lightbody/browsermob-proxy#474]
netty4.1 introduced socks support.
http://netty.io/wiki/new-and-noteworthy-in-4.1.html
"SOCKSx codec that supports version 4, 4a, and 5; see socksx package."
https://github.com/netty/netty/commit/2309a75d15ffbd063b9a710df4fa1ec3c63702f9

I think it would be easy to do some modification  and implement socks support as well.
Thank you.

**Comment by jekh** [comment]
Yep, this is how BMP will pick up SOCKS support. That will happen via LittleProxy, so I'll close this issue, as it's being tracked there.
