### ISSUE TITLE
Using 2.1.1 with Appium, Post Body data is null, is there some variable I need to set?

### ISSUE THREAD

**Issue by Gophergamer** [lightbody/browsermob-proxy#476]
Hi there,

So I'm using Java and integrating this with Appium. I have my mac OSX configured so http proxy's to the port that is set in  "server.start(8888)". Appium is triggering my app in the Xcode simulator(version 7.3.1). For the most part, all Url, queryString..etc is being captured and "GET" requests seem to have the correct query string, but for "POST" calls, the Post Data doesn't seem to be captured. When I output the har file, it shows a "bodySize" but no body data. Is there something specific I need to do to capture the post body? Or is there something different for App based traffic? I understand there is no cookies, since this is App based.

Mac OSX 10.11.5
Pom:
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>4.0.0</version>
		</dependency>
 		<dependency>
        	       <groupId>net.lightbody.bmp</groupId>
        	       <artifactId>browsermob-core</artifactId>
        	       <version>2.1.1</version>
        	<scope>test</scope>
    	</dependency>

Code Snippet:
	static BrowserMobProxy server = new BrowserMobProxyServer();
	server.start(8888);
	server.newHar("pb");
	Proxy proxy = ClientUtil.createSeleniumProxy(server);
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("appium-version", "1.0");
	capabilities.setCapability("platformName", "iOS");
	capabilities.setCapability("platformVersion", "9.3");
	capabilities.setCapability("deviceName", "iPhone 6");
	capabilities.setCapability(CapabilityType.PROXY, proxy);
	capabilities.setCapability("app",itc.getCurrentXmlTest().getParameter("app_loc"));
	wd = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

       ....some appium java code in between to trigger app and do stuff...

        FileOutputStream os = new FileOutputStream("pb.har");
	Har har = server.getHar();
	har.writeTo(os);
        server.stop();

har file Entry:
{...
     "pageref":"Page 0",
     "startedDateTime":"2016-06-10T16:41:08.832-07:00",
     "request":{
          "method":"POST",
          "url":"http://somedomain.comj",
          "httpVersion":"HTTP/1.1",
          "cookies":[
          ],
          "headers":[
          ],
          "queryString":[
          ],
          "headersSize":434,
          "bodySize":270,
          "comment":""
     },...

**Comment by jekh** [comment]
You need to call .enableHarCaptureTypes(...) to capture various types of information in the HAR. They are disabled by default to avoid overwhelming the heap.

**Comment by Gophergamer** [comment]
Thank you so much for that info. That solved the problem. :)
