### ISSUE TITLE
Unable to use setChainedProxy

### ISSUE THREAD

**Issue by ram2691** [lightbody/browsermob-proxy#477]
Hello Sir, I have recently started working on java. I have been trying to set upstream proxy but i am not able to do so. May you please help me with this. on running this code a firefox is opening but not redirecting to the website.
i get this in my console before opening the browser :
312 [main] WARN org.littleshoot.proxy.impl.DefaultHttpProxyServer - Enabled proxy chaining with man in the middle.  These are mutually exclusive - man in the middle will be disabled.
374 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:4444
419 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
533 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:4444

Here is the code : 
`import java.io.StringWriter;
import java.net.Inet4Address;
import java.net.InetSocketAddress;
import java.util.HashMap;
import java.util.Map;

import net.lightbody.bmp.core.har.HarEntry;
import net.lightbody.bmp.proxy.ProxyServer;
import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import org.apache.tools.ant.filters.StringInputStream;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class GetHarLogs {

	public static void main(String[] args) throws Exception {
			
		// start the proxy
		//ProxyServer server = new ProxyServer(4444);
		BrowserMobProxyServer server = new BrowserMobProxyServer(4444); 
		InetSocketAddress address = new InetSocketAddress("127.0.0.1",443);
		server.setChainedProxy(address);
        server.start();
	
        //captures the mouse movements and navigations
		server.setCaptureHeaders(true);
		server.setCaptureContent(true);
		

		// get the Selenium proxy object
		Proxy proxy = server.seleniumProxy();
		// configure it as a desired capability
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.PROXY, proxy);

		// start the browser up
		WebDriver driver = new FirefoxDriver(capabilities);

		// create a new HAR with the label "apple.com"
		server.newHar("amazon.in");

		// open yahoo.com
		driver.get("http://amazon.in/");

		// get the HAR data
		net.lightbody.bmp.core.har.Har har = server.getHar();
		String harText = "";
		harText = har.getLog().getEntries().size()+"";
	
		System.out.print("Har Log : ");
		System.out.println(harText);
		server.stop();
		driver.quit();
	}

}`

**Comment by jekh** [comment]
Chained Proxy + MITM has worked for several releases. Update to the latest, 2.1.1, and retry your test.

**Comment by ram2691** [comment]
Hey I will test it after updating to the latest version !
Rest code is fine ? or do i need to change anything in the code.

**Comment by ram2691** [comment]
after updating the version. I am getting error on the line "server.newHar("amazon.in")" when i run it.
error is :
Exception in thread "main" java.lang.NoSuchMethodError: net.lightbody.bmp.core.har.HarPage.<init>(Ljava/lang/String;Ljava/lang/String;)

**Comment by jekh** [comment]
That looks like a problem with your dependency management system. Make sure you're using Maven, Gradle, or an equivalent dependency management system, and are including the correct artifact (`net.lightbody.bmp:browsermob-core:2.1.1`).
