### ISSUE TITLE
nonProxyHosts support for chained proxy

### ISSUE THREAD

**Issue by wangzhih** [lightbody/browsermob-proxy#494]
I'm using BMP in Embedded Mode. I used setChainedProxy and chainedProxyAuthorization to configure the chained proxy. Question is how to configure the hosts that the requests to them do not need to went through the chained proxy, like this can be configured in any browser? Thanks.

**Comment by jekh** [comment]
There's no way to do this automatically, but it's definitely possible by accessing the lower-level ChainedProxyManager interface from LittleProxy. I explain how to do this in [this answer](https://github.com/lightbody/browsermob-proxy/issues/486#issuecomment-231559425).

Note that you can't use BMP's built-in chainedProxyAuthorization when you're manually setting the LP ChainedProxyManager, so you'll need to implement that yourself if your ChainedProxyManager. See the [BrowserMobProxyServer source code](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java#L330) to see how that's done.
