### ISSUE TITLE
Update Jetty (and other dependencies) to the latest version

### ISSUE THREAD

**Issue by alexnederlof** [lightbody/browsermob-proxy#5]
This product looks really great but I can't use it because of many dependency conflicts. For example, you are still using Jetty 7 while the product I'm working on has Jetty 9.

It would be great if the product would be split-up into a jar that is only for embedded Java and a jar that also allows the web access. This way, the amount of (unused) dependencies you import when running in embedded Java mode will be significantly reduced.

**Comment by jekh** [comment]
I'm going to close this because it should now be resolved as of BMP 2.1 using the browsermob-core module exclusively in embedded mode.
