### ISSUE TITLE
SSL resources loading broken in eclipse

### ISSUE THREAD

**Issue by akosicki** [lightbody/browsermob-proxy#50]
There is a couple of resources in the project classpath, mainly some ssl stuff under the sslSupport package. Those resources are loaded with the ResouceExtractor helper. As long as we are in the simple app that does not uses custom classloaders this works fine. However that does not work any longer in environments like Eclipse where we've got custom classloaders and deal with the custom URLs schemas like "bundleresource://". It would be nice if we allow users to resolve those URLs in the way they need.

In a short words: ssl does not work when bmp is kept in an eclipse plugin

**Comment by jekh** [comment]
@akosicki -- is this still an issue? The sslSupport files should be on the classpath at /sslSupport. If eclipse can't understand the maven src/main/resources project structure, you may need to add that directory to the Eclipse classpath manually.

**Comment by akosicki** [comment]
@jekh, that's still an issue in the latest sources, just checked it. simple fix - https://github.com/akosicki/browsermob-proxy/commit/30c905b7e , It would be nice to have it in the main branch so that I could later use

    ResourceExtractor.setURLResolver(new ResourceExtractor.URLResolver() {
        @Override
        public URL resolve(URL url) {
            if ("bundleresource".equalsIgnoreCase(url.getProtocol())) {
                try {
                    // FileLocator is an Eclipse-specific thingy
                    return FileLocator.resolve(url);
                } catch (IOException e) {
                    return url;
                }
            } else {
                return url;
            }
        }
    });
    // ....
    server = new ProxyServer(9090);
    // ....

**Comment by jekh** [comment]
@akosicki - I just pushed a potential fix to my fork. It's available on the [classpath-resources-fix](https://github.com/jekh/browsermob-proxy/tree/classpath-resources-fix) branch, and here is the updated [SeleniumProxyHandler.java](https://github.com/jekh/browsermob-proxy/blob/57b367e10429eb4ca83e9e2028f8a06b4cfed0c4/browsermob-core/src/main/java/net/lightbody/bmp/proxy/selenium/SeleniumProxyHandler.java) file.

Let me know if that fixes your problem. It will also, hopefully, eliminate the need for standalone clients to have a separate sslSupport directory.

**Comment by akosicki** [comment]
@jekh - ok, let me try it

**Comment by jekh** [comment]
I believe this is fixed, so I'm going to close the issue. Please reopen if you still experience problems with it.
