### ISSUE TITLE
Unable to Launch Application using BrowserMobProxy

### ISSUE THREAD

**Issue by Sahiityaa** [lightbody/browsermob-proxy#501]
Hi,
I used the below code to launch a application using BrowserMobProxy but when I execute the same ...the respective application is not launched instead I get "Unable to Connect" Cannot establish a connection to the server error.
Please help me in resolving this issue
**Java Version:  1.8**
**FireFox Version: 47**
**Selenium Version: 2.53.1**

"**Dependency Updated in POM as:**
       groupId: net.lightbody.bmp
       artifactId: browsermob-core
       version: 2.1.1

Selenium - Java Code:
package test;

import java.io.File;
import java.io.IOException;
import net.lightbody.bmp.core.har.Har;
import net.lightbody.bmp.proxy.ProxyServer;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class FirstSample {

	@SuppressWarnings("deprecation")
	public static void main(String[] args) throws InterruptedException {

		// Start the BrowserMob Proxy
		ProxyServer server = new ProxyServer(9090);
		server.start();

		// Get the Selenium proxy object
		Proxy proxy = server.seleniumProxy();

		// Configure Desired capability for using Proxy Server
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.PROXY, proxy);

		// Start the Browser up
		WebDriver driver = new FirefoxDriver(capabilities);
		// Create a new HAR with the label "StockMarketData"
		server.newHar("hardata");
		// Open the Application
		driver.get("http://www.prnewswire.com");
		Thread.sleep(5000);

		// Get the HAR data
		Har har = server.getHar();
		// Write the HAR Data in a File
		File harFile = new File("D:\\Workspace\\CaptureNetworkTraffic\\output.txt");
		try {
			har.writeTo(harFile);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		// Stop the BrowserMob Proxy Server
		server.stop();

	}
}

**Comment by jekh** [comment]
See the code examples in the [Embedded Mode section of the readme](https://github.com/lightbody/browsermob-proxy#embedded-mode). That will get you going.

I admit the code is buried; a restructuring of the readme is in order!
