### ISSUE TITLE
Switch off 'limits' trouble, by REST API

### ISSUE THREAD

**Issue by antonecma** [lightbody/browsermob-proxy#510]
As we can see, [documentation about REST API method called _/proxy/[port]/limit_](https://github.com/lightbody/browsermob-proxy#rest-api) is telling us that 

> _enable_ - A boolean that enable bandwidth limiter. Optional, by default to "false", but setting any of the properties above will implicitly enable throttling

But when I have used this method, with value **false** in _enable_ param, this is looked like limits is set before had not changed.

I have written some code to reproduce this [issue.](https://gist.github.com/antonecma/6fd3b474e464576e8a09f9d5e1cf93ad)

**Comment by jekh** [comment]
This option is also not supported. You should be able to set the limit to 0 to disable bandwidth limits. If not, a very high value would achieve the same thing. Integer.MAX_VALUE is 2147483647, so setting the limit to that would effectively disable throttling.

Sorry for the confusion here; until the REST API is refactored, I'm not investing any more time in updating its documentation or code. PRs are always welcome if you need an immediate fix, though.
