### ISSUE TITLE
payloadPercentage does not working (REST API)

### ISSUE THREAD

**Issue by antonecma** [lightbody/browsermob-proxy#511]
The issue is that  when we changed value of _payloadPercentage_ nothing changes. Data transmisson time is still fixed. No matter what value of _payloadPercentage_ had posted to _/proxy/[port]/limit_. May be I need to setup both of _downstreamKbps_ and _upstreamKbps_ first?

**Comment by jekh** [comment]
To be honest, I wasn't even aware that payloadPercentage was still listed in the docs. Technically, it would work with the legacy implementation, but I don't recommend that. Instead, just set the upstream and downstream kbps directly.

The REST API rework that is underway will remove this option completely.

**Comment by jekh** [comment]
This option is also not supported. You should be able to set the limit to 0 to disable bandwidth limits. If not, a very high value would achieve the same thing. Integer.MAX_VALUE is 2147483647, so setting the limit to that would effectively disable throttling.

Sorry for the confusion here; until the REST API is refactored, I'm not investing any more time in updating its documentation or code. PRs are always welcome if you need an immediate fix, though.

**Comment by antonecma** [comment]
So, I am thinking  _maxBitsPerSecond_ also will not work for same reason, that you were writing above?

**Comment by jekh** [comment]
Are you having issues with maxBitsPerSecond too?

**Comment by antonecma** [comment]
> Are you having issues with maxBitsPerSecond too?
Yes, this parameter doesn't affect to download/upload speed for me.
