### ISSUE TITLE
ClientUtil.createSeleniumProxy uses wrong interface address

### ISSUE THREAD

**Issue by carlosmunoz** [lightbody/browsermob-proxy#515]
When trying to create a proxy instance for Selenium web driver, the address being used is not the correct one.

When running:

```java
BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start(0, InetAddress.getLoopbackAddress());

Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
```

the result is that the proxy is configured to use the local host address (e.g. dhcp-40-252.example.com) instead of the loopback address (e.g. 127.0.0.1). As a result, selenium could not connect to the proxy.

The workaround was to specify the loopback adress again when creating the selenium proxy (see below).

```java
Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy, InetAddress.getLoopbackAddress());
```

**Comment by jekh** [comment]
This is works-as-designed.
