### ISSUE TITLE
REST API client

### ISSUE THREAD

**Issue by thibaut-sticky** [lightbody/browsermob-proxy#518]
Hi all,

I've looked for, but cannot find any REST API client. I guess the embedded mode use such a thing, isn't it? So I'm surprised to not see it expose.

Today, I'm fine with the embedded mode and my Selenium tests. But, in the future I want to use SauceLab. To use SC and a proxy, I have to use their tunnel. A unique one. So my idea is to host somewhere a standalone browsermob and then instead of `proxy = new BrowserMobProxyServer();` I will do `proxy = new BrowserMobProxyServer("addressStandaloneServer");`

Is it possible?

**Comment by sskorol** [comment]
https://github.com/lightbody/browsermob-proxy/issues/155

**Comment by thibaut-sticky** [comment]
Oh I missed it. Shame on me.
