### ISSUE TITLE
Wrong work of override headers  [REST API]

### ISSUE THREAD

**Issue by antonecma** [lightbody/browsermob-proxy#519]
One more issue from me.
Documentation about _/proxy/[port]/headers_ REST API method says us that

> Set and override HTTP Request headers

But I have noticed [here](https://github.com/lightbody/browsermob-proxy/blob/6f2f9635bf3b06d000f2bc3d70c979471246a6f3/browsermob-rest/src/main/java/net/lightbody/bmp/proxy/bricks/ProxyResource.java#L274), code, for this method, is only adding headers, but never overriding them.

**Comment by sskorol** [comment]
I believe that `addHeader` uses `Map` for storing corresponding items.
From Java basics you may know that any value will be automatically overridden by calling `put`, if provided key already exists.

**Comment by antonecma** [comment]
@sskorol it's very strange. I have described some [bash script](https://gist.github.com/antonecma/bd5a3343f52e8b5570e8f194dd330c5c) for reproduce this issue.

**Comment by sskorol** [comment]
@antonecma not sure then... @jekh should know this better

**Comment by antonecma** [comment]
This method override headers had se by _/proxy/[port]/headers_ REST API method before, but not override headers had setted by browser, curl, etc. 
This method overrides headers, that has set by this method before, but not overrides  headers, that has been set by browser, curl, etc.
` send request to http headers echo server

{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "**curl/7.47.1**", 
    "Via": "1.1 browsermobproxy"
  }
}

 send request to http headers echo server

{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "**curl/7.47.1**,override", 
    "Via": "1.1 browsermobproxy"
  }
}

 send request to http headers echo server

{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "**curl/7.47.1**,FOOBAR", 
    "Via": "1.1 browsermobproxy"
  }
}
`
"**curl/7.47.1**  is still remaining in  the "User-Agent" header.

**Comment by jekh** [comment]
This is another documentation issue, so feel free to submit a PR for the docs, though they will be completely replaced with the new REST API.

In order to remove existing headers using the REST API, you can use a Javascript filter. There's actually a test that shows exactly how to do this, FilterTest.testCanModifyRequestHeadersWithJavascript().
