### ISSUE TITLE
HAR file Validation error while creating using REST CURL requests

### ISSUE THREAD

**Issue by hemanthvenkata** [lightbody/browsermob-proxy#52]
Hi,

After Creating Proxy using a server and generating a HAR file it is working fine through CURL requests but while viewing HAR it is throwing a HAR Validation Error as

Sum of request timings doesn't correspond to the total value: http://google.co.in (request.time: 357 vs. sum: 694), request#: 0, parent page: Foo

After going through the issue I came to know that while calculating the total time it is not using the blocked time for calculating SUM.

As per http://www.softwareishard.com/blog/har-12-spec/ 
entry.time == entry.timings.blocked + entry.timings.dns +
    entry.timings.connect + entry.timings.send + entry.timings.wait +
    entry.timings.receive;

but the generated HAR not summing up the blocked time, As per my understanding

**Comment by jekh** [comment]
There have been some recent changes to the HAR classes which have probably fixed this. Closing this for now, but please reopen if you still see this with the latest code.
