### ISSUE TITLE
mitm-2.1.2.jar in Maven Repository is broken

### ISSUE THREAD

**Issue by dmigowski** [lightbody/browsermob-proxy#523]
Hello,

I used the following dependency to download mitm from Maven:

    <dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>mitm</artifactId>
        <version>2.1.2</version>
    </dependency>

Eclipse succesfully handles the jar file, but when I started my app I got ClassNotFoundExceptions regarding the classes in that jar. I had to extract the jar file and repack it to get stuff working. When I checked the jar file with 7zip zip file validation it complaint about garbage at the end of the file which is maybe the reason for the problem. I can work on for now but maybe there are problems in your build chain you might wnat to inventigate.

**Comment by jekh** [comment]
What exactly are the errors you're facing when using MITM? You need to give more details to enable us to help you solve the problem.

I have not seen any issues with the jar file itself.

**Comment by dmigowski** [comment]
OK, maybe maven just got interrupted by me when downloading the jar file. I believe this should rather be reported as a maven bug...
