### ISSUE TITLE
differences in har created with different browsers

### ISSUE THREAD

**Issue by riccardoroasio** [lightbody/browsermob-proxy#526]
Hi,

I always use firefox with selenium and browsermob to execute syntethic test on websites and retrieve har from browsermob.
Some days ago I tried also with phantomjs and chrome and I found that are created from browsermob navigating website with chrome are different with har created navigating with firefox and phantomjs. 
In attached har differences are in a gif file that is present in the chrome har but not in the other ones.

Checing with firefox network tools the gif is loaded.

Here is the code:

`var webdriverio = require("webdriverio")
    , Proxy = require('browsermob-proxy').Proxy
    , fs = require('fs')
    , proxyHost = 'localhost'
    ;

var argv=process.argv;
if(argv.length<=2){
 console.log("set broser type");
 process.exit(0);
}
var browser_type=argv[2];

var capabilities={};

console.log("browser: "+browser_type);

```
var proxy = new Proxy( { host: proxyHost });
proxy.start(function(err, data) {
            if (!err) {
                // SET AND OVERRIDE HTTP REQUEST HEADERS IF YOU WANT TO 
                var headersToSet = {
                    'User-Agent': 'Bananabot/1.0',
                    'custom-header1': 'custom-header1-value',
                    'custom-header2': 'custom-header2-value'
                }
                proxy.addHeader(data.port, headersToSet, function (err,resp) {
                    if(!err) {
                        proxy.startHAR(data.port,'test',true,true,true, function (err, resp) {
                            if (!err) {
                                // DO WHATEVER WEB INTERACTION YOU WANT USING THE PROXY 
                                doSeleniumStuff(proxyHost + ':' +  data.port, function () {
                                    proxy.getHAR(data.port, function(err, resp) {
                                        if (!err) {
                                            //console.log(resp);
                                            fs.writeFileSync(browser_type+'_output.har', resp, 'utf8');
                                        } else {
                                            console.err('Error getting HAR file: ' + err);
                                        }
                                        proxy.stop(data.port, function() {});
                                    });
                                });
                            } else {
                                console.error('Error starting HAR: ' + err);
                                proxy.stop(data.port, function () {
                                });
                            }
                        });
                    } else {
                         console.error('Error setting the custom headers');
                         proxy.stop(data.port, function () {
                       });
                    }
                });
            } else {
                console.error('Error starting proxy: ' + err);
            }
        });
```

function doSeleniumStuff(proxy, cb) {

// FIREFOX
    if(browser_type=='firefox'){
     capabilities={ browserName: 'firefox', seleniumProtocol: 'WebDriver', proxy: { httpProxy: proxy } };
    }
// CHROME
    else if(browser_type=='chrome'){
     capabilities={ browserName: 'chrome',
        chromeOptions: {
           args: ['disable-web-security','proxy-server='+proxy]
        }
      };
    }
//PHANTOMJS
    else if(browser_type=='phantomjs'){
     capabilities={ browserName: 'phantomjs', seleniumProtocol: 'WebDriver',
                 proxy:{
                        proxyType: 'manual',
                        httpProxy: proxy,
                }
        };
    }
    else{
     console.log("browser "+browser_type+" not managed");
     process.exit();
    }

```
console.log("capabilities: "+JSON.stringify(capabilities));

var browser = webdriverio.remote({
    host: 'localhost'
    , port: 4444
    ,desiredCapabilities:capabilities
});

browser
    .init()
    .url("http://search.yahoo.com")
```

//        .setValue("#yschsp", "javascript")
//        .submitForm("#sf")
        .saveScreenshot('results.png')
        .end().then(cb);
}

`

Am I doing something wrong
[har_files.zip](https://github.com/lightbody/browsermob-proxy/files/403379/har_files.zip)
?

Best Regards,
Riccardo

**Comment by riccardoroasio** [comment]
Hi,

I found that the difference is that chrome gif request is HTTP1 while firefox gif request is http2 that is not yet upported by browsermob i think ... is it correct?

**Comment by riccardoroasio** [comment]
Or maybe is because the response is a 304?

I tried also with firefox 28 and the issue is the same...

I'm a little bit confused!

**Comment by leoforever** [comment]
I am interested  in this too. 
Har generated from bmp is different from what I captured from firebug.

**Comment by jekh** [comment]
It's not surprising that the HAR files created from a browser would be different than those captured through BMP. Browsers have access to additional data and context that BMP can't see.

If you find a deficiency with a BMP-generated HAR, please feel free to open a new issue.
