### ISSUE TITLE
setChainedProxy -> does not work at all

### ISSUE THREAD

**Issue by ogolovanov** [lightbody/browsermob-proxy#530]
Hello!

1) I took simple example from here: https://github.com/lightbody/browsermob-proxy#using-with-selenium
2) changed http://yahoo.com to very simple non-https site
3) set chained proxy via setChainedProxy() method

Result: "Bad Gateway: ..."

If i remove setChainedProxy method, everything works ok.
All tested chained proxy servers work.

What can be the problem?
Thank  you.

Update №1:
I tested absolutely the same configuration with charles proxy - it works well.
Test with browsermob fails - it returns "bad gateway" error instantly.
It seems chained proxy not requested at all.

**Comment by jekh** [comment]
Are you setting the chained proxy after you call .start()? When setting a chained proxy, you need to call the method before calling start(). This is currently not called out anywhere in the documentation or enforced in the code, so that's worthy of a quick PR to remedy. 

In the meantime, try setting the chained proxy before .start() to see if that fixes your problem.

**Comment by ogolovanov** [comment]
Hello.

No, of course i set chained proxy and all other staff before .start() method.

Example java code:

`      BrowserMobProxy proxy = new BrowserMobProxyServer();
        proxy.setChainedProxy(InetSocketAddress.createUnresolved("xxx.xxx.xxx.xxx", 8888));
        proxy.setTrustAllServers(true);
        proxy.setMitmManager(ImpersonatingMitmManager.builder().trustAllServers(true).build());
        proxy.start();

        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        WebDriver driver = new FirefoxDriver(capabilities);
        driver.get("http://yandex.ru/robots.txt");
        Thread.sleep(5000);

        proxy.stop();
        driver.quit();`

Chained proxy - working http/https proxy server.

When i run this code, i see "Bad Gateway: http://yandex.ru/robots.txt" error.
And no request was forwarded to chained proxy - no new records in proxy server logs.
But if i run from the command line on the same machine "curl -x 'https://xxx.xxx.xxx.xxx:8888/' http://yandex.ru/robots.txt" - everything works as expected, there are new records in proxy server logs.

If i remove .setChainedProxy() method - also everything works ok.
Browsermob version: 2.1.2.

**Comment by jekh** [comment]
The problem is that you're using InetSocketAddress.createUnresolved. Use new InetSocketAddres("...", 8888) instead.

**Comment by ogolovanov** [comment]
Hmm, it works)
But i don't understand why it does not work with createUnresolved ))

Thank you.

**Comment by jekh** [comment]
You'll have to ask Oracle about that. Glad it's working though.
