### ISSUE TITLE
How to start browsermob proxy server when I am using proxy to connect to net

### ISSUE THREAD

**Issue by vuyyala** [lightbody/browsermob-proxy#533]
Hi All,
I am using proxy to connect to net so when I am trying to start browsermob proxy server it is unable to get started.How to run the server when I am behind the proxy?

server=Server('path to browsermob-proxy')
server.start()
proxy=server.create_proxy()

**Comment by jekh** [comment]
It looks like you're using the Python wrapper, so you'll have check [that project's documentation](https://github.com/AutomatedTester/browsermob-proxy-py) to see if it's supported. If you were using the Java version, you would want to set the chained proxy using `BrowserMobProxy.setChainedProxy(...)`.
