### ISSUE TITLE
Comparable

### ISSUE THREAD

**Issue by JMVM** [lightbody/browsermob-proxy#534]
Hi there,

I would need **HarEntry** implementing **Comparable** interface, in order to be able to **reverse order** all entries in list from *HarLog*, since I have a periodic request with different values to initial ones when first time call is done.

Obviously I could iterate over list looking for last request which was made, but I think with too many entries reversing could be a good point.

Please could you include it if so?

Thanks

**Comment by jekh** [comment]
You can use `Collections.sort` and provide your own Comparator implementation, so there's no need for HarEntry to implement Comparable.
