### ISSUE TITLE
Unable to use Browsermob with Bouncycastle security provider

### ISSUE THREAD

**Issue by dallmeier** [lightbody/browsermob-proxy#538]
I am using BrowserMob Proxy 2.1.2 to mitm access to ssl sites. For some sites, there are exceptions where the sun security provider complains about invalid padding sizes. To avoid these problems, I downloaded Bouncycastle 1.55, installed it to jre/lib/ext and updated jre/lib/security/java.security to use the bouncy castle provider with priority 1 (get rid of sun). I then started BrowserMob and everything looks fine.

However, when I access an ssl site I get the following exceptions and BrowserMob is unable to proxy ssl content:

`net.lightbody.bmp.mitm.exception.MitmException: Error creating SSLEngine for connection to client to impersonate upstream host: www.toll-collect.de at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.clientSslEngineFor(ImpersonatingMitmManager.java:227) ~[browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ProxyToServerConnection$3.execute(ProxyToServerConnection.java:741) ~[browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow.processCurrentStep(ConnectionFlow.java:128) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow.advance(ConnectionFlow.java:90) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlowStep.onSuccess(ConnectionFlowStep.java:83) ~[browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete(ConnectionFlow.java:149) ~[browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170) [browsermob-dist-2.1.2.jar:na] at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [browsermob-dist-2.1.2.jar:na] at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow.access$000(ConnectionFlow.java:14) [browsermob-dist-2.1.2.jar:na] at org.littleshoot.proxy.impl.ConnectionFlow$1.run(ConnectionFlow.java:124) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [browsermob-dist-2.1.2.jar:na] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) [browsermob-dist-2.1.2.jar:na] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [browsermob-dist-2.1.2.jar:na] at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45] Caused by: com.google.common.util.concurrent.UncheckedExecutionException: net.lightbody.bmp.mitm.exception.ImportException: Unable to read KeyStore from file: keystore7971895431487704013temp at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.getHostnameImpersonatingSslContext(ImpersonatingMitmManager.java:242) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.clientSslEngineFor(ImpersonatingMitmManager.java:223) ~[browsermob-dist-2.1.2.jar:na] ... 22 common frames omitted Caused by: net.lightbody.bmp.mitm.exception.ImportException: Unable to read KeyStore from file: keystore7971895431487704013temp at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.loadKeyStore(DefaultSecurityProviderTool.java:138) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.KeyStoreFileCertificateSource.loadKeyStore(KeyStoreFileCertificateSource.java:128) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.KeyStoreFileCertificateSource.access$0(KeyStoreFileCertificateSource.java:116) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.KeyStoreFileCertificateSource$1.get(KeyStoreFileCertificateSource.java:39) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.KeyStoreFileCertificateSource$1.get(KeyStoreFileCertificateSource.java:1) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.KeyStoreFileCertificateSource.load(KeyStoreFileCertificateSource.java:109) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$2.get(ImpersonatingMitmManager.java:124) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$2.get(ImpersonatingMitmManager.java:1) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.createImpersonatingSslContext(ImpersonatingMitmManager.java:291) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.createImpersonatingSslContext(ImpersonatingMitmManager.java:271) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.access$3(ImpersonatingMitmManager.java:264) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$3.call(ImpersonatingMitmManager.java:245) ~[browsermob-dist-2.1.2.jar:na] at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$3.call(ImpersonatingMitmManager.java:1) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[browsermob-dist-2.1.2.jar:na] at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[browsermob-dist-2.1.2.jar:na] ... 26 common frames omitted Caused by: java.io.IOException: exception decrypting data - java.security.InvalidKeyException: Illegal key size at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.cryptData(Unknown Source) ~[bcprov-jdk15on-155.jar:1.55.0] at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source) ~[bcprov-jdk15on-155.jar:1.55.0] at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_45] at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.loadKeyStore(DefaultSecurityProviderTool.java:136) ~[browsermob-dist-2.1.2.jar:na] ... 45 common frames omitted`

Should using Bouncycastle work together with BrowserMob? If so, am I doing something wrong?

**Comment by jekh** [comment]
Yes, BC and BMP should definitely work together when using BC as the security provider. Most of the MITM code is written with BC, so I'm quite surprised that this doesn't work already.

Thanks for this bug report, I'll see if I can get it to repro locally and get a fix out.

**Comment by dallmeier** [comment]
Let me know if i can help.

Am 06.09.2016 5:10 nachm. schrieb "Jason Hoetger" <notifications@github.com

**Comment by jekh** [comment]
I was able to reproduce this, and tracked down the issue. Even though you're using BouncyCastle as the first security provider, you still need to install the unlimited strength policy files in the JVM. See [this answer](http://www.bouncycastle.org/wiki/display/JA1/Frequently+Asked+Questions#FrequentlyAskedQuestions-1.WhydoIget"java.lang.SecurityException:Unsupportedkeysizeoralgorithmparameters"or"java.security.InvalidKeyException:Illegalkeysize"whenItryusingtheBouncyCastleProvider?) in the BouncyCastle FAQ. I tested with the unlimited strength policy files in my BC-enabled JDK, and I was able to browse HTTPS websites as expected.

Were you able to completely remove the `sun.security.provider.Sun` provider? [BouncyCastle actually recommends against installing BC higher than position 2](http://www.bouncycastle.org/wiki/display/JA1/Provider+Installation), but FWIW I was able to get it to work in position 1, with the Sun provider as number 2.

**Comment by dallmeier** [comment]
Thanks a ton. That solved it for me. Since the error was raised by BrowserMob I did not suspect BouncyCastle and hence did not look at their FAQs.

**Comment by jekh** [comment]
Glad it's working. Did you completely remove the `sun.security.provider.Sun` provider, or did you place that at 2, after BC?

**Comment by Scisaga** [comment]
@dallmeier 
hi, would u kind share some experience about how to solve this issue, many thanks!

**Comment by Rosielover** [comment]
@Scisaga 
I got the same issue and resolved it. If you haven't overcome this issue , pls follow these steps
1. Edit java.security file in Jre., (ex :c:\Program Files\Java\jre7\lib\security\)
2. Insert this line to the bottom line of security.provider.N
security.provider.11=org.bouncycastle.jce.provider.BouncyCastle
3. If it still occurs error like above exception but with  org.bouncycastle.asn1.ASN1GeneralizedTime then you can fix by adding security.provider.12=org.bouncycastle.asn1.ASN1GeneralizedTime in follow.

you can copy java.security to another folder to edit file to avoid access denied.
