### ISSUE TITLE
Capturing of HAR for youtube videos from chrome at the end of duration

### ISSUE THREAD

**Issue by vuyyala** [lightbody/browsermob-proxy#539]
Hi all,
Is there a way to capture HAR for a youtube video at the end of its duration?Through the following code it is capturing the HAR at the start of the video itself.What modifications need to be done if I don't know the duration in advance.

server=Server('path to browsermob-proxy')
server.start()
proxy=server.create_proxy()
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--proxy-server={0}".format(proxy.proxy))
browser = webdriver.Chrome(executable_path="/home/sivakesava/chromedriver",chrome_options = chrome_options)
proxy.new_har("CS")
browser.get("https://www.youtube.com/watch?v=NFQeItqTfZk")
har=proxy.har
print har
browser.quit()
server.stop()

**Comment by jekh** [comment]
Can you be more specific about what the issue you're facing is?

**Comment by vuyyala** [comment]
What I wanted is for a youtube video the above code downloads HAR as soon as page is loaded(video starts playing) but I want the HAR after the video is played.Suppose youtube video is of 5minutes duration the above python script downloads HAR as soon as video starts but I want the HAR for video at the end of 5 minutes.I cannot include a sleep of 5 min because the video may buffer and take longer time.

**Comment by ghost** [comment]
hi all, I have the same problem, have you resolved thie question? Thanks.
