### ISSUE TITLE
Har data from proxy can't be deserialized using net.lightbody.bmp.core.har.Har and Jackson

### ISSUE THREAD

**Issue by vlaadbrain** [lightbody/browsermob-proxy#552]
when trying to deserialize proxy HAR data from a remote proxy, into net.lightbody.bmp.core.har.Har, Jackson 2.8.1 complains about missing default constructor.

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of net.lightbody.bmp.core.har.HarNameVersion: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: java.io.StringReader@4c319d52; line: 1, column: 36](through reference chain: net.lightbody.bmp.core.har.Har["log"]->net.lightbody.bmp.core.har.HarLog["creator"])

Har Objects are missing Jackson annotations to help jackson deserialize.

In addition, the timings structure from the standalone proxy har data (GET http://localhost:8080/proxy/%port%/har)  

contains variables called 
"timings":{"comment":"","send":1,"wait":51,"receive":0,"ssl":-1,"blocked":0,"dns":1,"connect":3}

while the HarTimings object in net.lightbody.bmp.core.har.\* 
has variables with 'Nanos" suffix, the deserialization doesn't work for these... :(    :-1:

**Comment by jekh** [comment]
You say you're trying to deserialize HAR files into BMP's Har objects. This is not supported or recommended. BMP's Har objects are designed to support BMP's use case, which is capturing and then serializing HAR data.
