### ISSUE TITLE
Header Modification for DynaTrace Integration with BMP and Selenium Grid

### ISSUE THREAD

**Issue by glacier6327** [lightbody/browsermob-proxy#554]
When our team was running Selenium tests single threaded on individual VMs it was easy to start a BMP and run our tests through it. We also would update the header information for each page and action since dynatrace was monitoring all our network traffic it would help us register (with dyantrace) and identify actions within the tests.

When we implemented a Selenium Grid, all this was lost.  Now I understand we can run an instance of BMP and point our browsers to it, and generate a har etc... but can we manipluate the header info in the request on its way through he proxy?

Any help is greatly appreciated.

Thanks,

**Comment by jekh** [comment]
Yes, you can use BMP to manipulate headers. Have a look at the HTTP request manipulation section of the readme: https://github.com/lightbody/browsermob-proxy#http-request-manipulation
