### ISSUE TITLE
Force BrowserMobProxy and Selenium Chrome Driver to use QUIC

### ISSUE THREAD

**Issue by SivaKesava1** [lightbody/browsermob-proxy#555]
Hi all, 
        I am working on downloading HAR from Chrome for YouTube through Selenium Python Script.
Code Snippet: 

```
            chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument("--proxy-server={0}".format(url))
    chrome_options.add_argument("--enable-quic")

        self.driver = webdriver.Chrome(chromedriver,chrome_options = chrome_options)

           self.proxy.new_har(args['url'], options={'captureHeaders': True})   // BrowserMobProxy
       self.driver.get(args['url'])
           result = json.dumps(self.proxy.har, ensure_ascii=False)
```

I want QUIC to be used whenever I download HAR but when I look at the packets through Wireshark Selenium driver is using TCP only . Is there a way to force BrowserMobProxy and  Chrome Driver to use QUIC?

**Comment by vuyyala** [comment]
The problem lies with BMP. It does not allow QUIC packets to pass on since it is a HTTP Server and it uses TCP only. Is there any alternative to BMP?

**Comment by jekh** [comment]
BMP doesn't support QUIC. There probably aren't many proxy servers that do support QUIC, as it's pretty much Google- and Chrome-specific. I'm not opposed to adding support for it to LittleProxy (and thus BMP), but it's not a priority at the moment.
