### ISSUE TITLE
BMP is not working with Selenium 3.0

### ISSUE THREAD

**Issue by dnovikau** [lightbody/browsermob-proxy#556]
The following code from example is working fine if to use selenium 2.53.1, and not work if selenium updated to the latest version (3.0.+)

    // start the proxy
    BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0);
    // get the Selenium proxy object
    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
    // configure it as a desired capability
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
    // start the browser up
    WebDriver driver = new FirefoxDriver(capabilities);
    // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
    // create a new HAR with the label "yahoo.com"
    proxy.newHar("yahoo.com");
    // open yahoo.com
    driver.get("http://yahoo.com");
    // get the HAR data
    Har har = proxy.getHar();

Is there any way of using BMP together with selenium 3.0?

**Comment by toberoo** [comment]
I think I am getting the same issue, it fails at proxy.newHar("yahoo.com") . New har throws an exception In initializer error. Still trying to find a solution.

**Comment by Youchen** [comment]
Hi @dnovikau  @toberoo, I am experiencing the same problem with you, Do you have any solution for this? Thanks!

**Comment by jekh** [comment]
BMP does work with Selenium 3 + Firefox, but because of a defect in Selenium 3's WebDriver implementation, you have to use a work-around. See this stackoverflow answer for details: http://stackoverflow.com/a/41373808/4256475

**Comment by Youchen** [comment]
Thanks so much @jekh ! it worked.
