### ISSUE TITLE
Too many connect failed

### ISSUE THREAD

**Issue by leoforever** [lightbody/browsermob-proxy#559]
When I use BMP 2.1.1 and selenium to visit a website, there are a lot of connect failed.
But when I use BMP 2.1.0 it will playback succeed.
I use firebug to get the har and there are no connect.
My system info is:Red Hat Enterprise Linux Server release 7.0 3.10.0-123.el7.x86_64
My test URL is:https://www.mevsnet.net

**Comment by leoforever** [comment]
My system info is:Red Hat Enterprise Linux Server release 7.0  3.10.0-123.el7.x86_64

**Comment by jekh** [comment]
What do the stack traces from the errors look like?
