### ISSUE TITLE
"stop" and "abort" methods of BrowserMobProxyServer doesn't reset "started" field

### ISSUE THREAD

**Issue by Alfira** [lightbody/browsermob-proxy#563]
There is net.lightbody.bmp.BrowserMobProxyServer class having "stop" and "abort" methods.
These methods successfully updates "stopped" class field, but doesn't reset "started" class field to "false". This leads to case, when proxy has status "stopped" is "true" and "started" is "true" at the same time.
Therefore the starting of stopped proxy throws IllegalStateException with message "Proxy server is already started. Not restarting.".

Steps to reproduce:
BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start();
proxy.stop();
proxy.start();

**Comment by jekh** [comment]
This is works-as-designed (and has been covered before, search through all open and closed issues). The proxy does not support stopping and then restarting. Create a new instance of the proxy, bound to the same port if necessary.
