### ISSUE TITLE
Add --version command line option to standalone binary

### ISSUE THREAD

**Issue by lexrj** [lightbody/browsermob-proxy#565]
There's currently no obvious way to tell what version of the binary you have on your path, making it difficult to verify which version you have installed. This makes scripting installation and version verification for updates difficult.

**Comment by jekh** [comment]
Agreed, and I see how this would be very difficult to achieve currently. I went ahead and added a simple `--version` option, which spits out `BrowserMob Proxy <version #>`. It should hopefully get you what you need for now, and once the launcher is refactored as part of the REST API upgrade, I'll include more detailed version and help/usage options. 

I'll merge PR #569 shortly and get it in the next bugfix release.
