### ISSUE TITLE
HTTPS with chained proxy doesn't work?

### ISSUE THREAD

**Issue by Idan37S** [lightbody/browsermob-proxy#567]
Hi,

I'm trying to record https proxy with chained proxy, but it doesn't seem to work.
http recording in the same setup does work, and recording https without the chained proxy also works.

Does bmp support https recording with chained proxy?

**Comment by jekh** [comment]
Yes, BMP supports HTTPS with chained proxies. You may need to use the trustAllServers option, or add specific certificates to the trust store.

If you have more details on the error you're getting, please feel free to post & reopen.

**Comment by Idan37S** [comment]
Thanks!
Using trustAllServers in the MITM manager work it out.
