### ISSUE TITLE
Package a standalone binary that can be installed on the System Path

### ISSUE THREAD

**Issue by lexrj** [lightbody/browsermob-proxy#571]
At present, browsermob-proxy is split between multiple files in a set structure. Attempting to symlink to the executable and run via that symlink leads to the following error:
```
$ browsermob-proxy -port 8080
Error: Could not find or load main class net.lightbody.bmp.proxy.Main
```
In my ideal world, there would be one file that I download that I can then put in a folder that is already on my path (such as `/usr/local/bin`), and have it execute properly. Instead, I need to have the explicit path to the */bin/browsermob-proxy file laid out for me in order to use it.

This is especially problematic when attempting to use browsermob-proxy in a distributed framework. Either browsermob-proxy needs to be bundled with the framework, or users need to clarify where they put the file, rather than being able to simply put it anywhere on the path.

**Comment by lexrj** [comment]
Added context: the distributed framework is in Python, which is why the embedded mode model is less than ideal.

**Comment by jekh** [comment]
This really isn't possible with any Java application. BMP doesn't compile to machine code, it requires a JVM in order to run. It's perfectly possible to run it with a one-liner as long as java is on the path, though:
```sh
java -jar browsermob-dist-2.1.2.jar
```
