### ISSUE TITLE
browsermob does not work with firefox using selenium 3

### ISSUE THREAD

**Issue by perwezalamnewscorp** [lightbody/browsermob-proxy#578]
I am trying to get performance data from firefox using selenium 3 and latest version of browsermob . But it does return any entries . When I run the same piece of code into chrome browser , it works fine and return the entries .

It does not throw any error when running in firefox but does not capture any data . Can you please explain this why it does not work with firefox . Please run the below code in both the browser then you can find the difference .

Code 

 BrowserMobProxy proxy = new BrowserMobProxyServer();
	   
	    proxy.start();

	    // get the Selenium proxy object
	    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

	    // configure it as a desired capability
	    DesiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

	    // start the browser up
	    WebDriver driver = new FirefoxDriver(capabilities);

	    // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
	    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

	    // create a new HAR with the label "yahoo.com"
	    proxy.newHar("SunWebiste");

	    // open yahoo.com
	    driver.get("http://www.thesun.co.uk/");

	    // get the HAR data
	    	    
       List<HarEntry> en=proxy.getHar().getLog().getEntries();       
       System.out.println("Size----"+en.size());
		int key=1; //Key number
		/**Creating the Map Objects for HarEntry to store Key Pair value */
		/***Running the loop for HarEntry */
		for(HarEntry hr:en){

	    System.out.println(hr.getRequest().getUrl());
	    
		}
		
		 proxy.stop();

**Comment by perwezalamnewscorp** [comment]
As you know that selenium 3 has been released recently , Does browser mob support in the platform with all latest implementation in selenium 3 . Now firefox 3 run on geckodriver . Can you please reply me with one working example for firefox browser using selenium 3

**Comment by jekh** [comment]
Selenium 3 and Firefox do not currently support configuring proxies in an intuitive way. Here's the geckodriver issue: https://github.com/mozilla/geckodriver/issues/97 

There are some work-arounds mentioned in the issue. You can also set the proxy on the FirefoxProfile directly:

```java
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("network.proxy.http", "localhost");
profile.setPreference("network.proxy.http_port", proxy.getPort());
profile.setPreference("network.proxy.ssl", "localhost");
profile.setPreference("network.proxy.ssl_port", proxy.getPort());
profile.setPreference("network.proxy.type", 1);

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(FirefoxDriver.PROFILE, profile);
            
driver = new FirefoxDriver(capabilities);
```

Unfortunately that's the best we can do until the upstream issues are fixed.

**Comment by perwezalamnewscorp** [comment]
Thank you so much for your quick response . I tried the above code for proxy but it throwing error "Connection is not secure" . I think it is a certificate issue . It would be good if you could share the complete the get HAR.


Anyway I an wait until the complete fixes are available from firefox side .

Thanks

**Comment by jekh** [comment]
See https://github.com/lightbody/browsermob-proxy#ssl-support
