### ISSUE TITLE
"We cannot execute …java" on Mac

### ISSUE THREAD

**Issue by romank604** [lightbody/browsermob-proxy#579]
I have tried a few rounds of removing and reinstalling Java with reboots along the way, but my attempts to launch Browsermob keep invariably failing with the message

> Error: JAVA_HOME is not defined correctly.
>   We cannot execute /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java

At the same time:
> macbook:bin romank604$ whereis java
> /usr/bin/java
> 
> macbook:bin romank604$ which java
> /usr/bin/java
> 
> macbook:bin romank604$ echo $JAVA_HOME // in ~/.bash_profile
> /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
> 
> macbook:bin romank604$ java -version
> java version "1.8.0_112"
> Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
> Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

On Windows 10 I have no problem launching Browsermob, but I must use a Mac and I am new to MacOS. I did whatever I could find (and understand) via Google and StackOverflow - to no avail. Would appreciate any help, thank you.

**Comment by jekh** [comment]
The startup script is in dire need of simplification. I've got that down for the next major release. In the meantime, you can start BMP on OS X by running `java -jar browsermob-dist-2.1.3.jar` from within the `lib` directory.

**Comment by jekh** [comment]
I did just simplify the startup script, it should work pretty consistently on OS X and Linux now.
