### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#58]
Hi,

I am testing on Mac OS and for some reason I get UnknownHostException on an intranet server (server connected via vpn). Local and external servers are Ok. I am using embedded mode. 

I assume that the issue is because BMP doesn't use /etc/resolv.conf for DNS lookup. And so I tried using /etc/hosts but it also won't work. Can we have a feature to include DNS lookup using DNS servers? Or atleast use /etc/hosts for remapping.

Thanks,
Christopher

**Comment by jekh** [comment]
@josemoO Did you ever get this resolved? You can also try setting the bmp.allowNativednsFallback system property to true, as described in the `Native DNS Resolution` section of the README.md file.

**Comment by claytonneal** [comment]
Where is the beta 8 zip downloadable from?

**Comment by jekh** [comment]
Closing this issue. It should be resolved by using the steps outlined in the comments.

**Comment by breinjhel** [comment]
Thanks @jekh
