### ISSUE TITLE
browsermob 2.1.2 maven not working on OS X

### ISSUE THREAD

**Issue by sajangupta-pt** [lightbody/browsermob-proxy#583]
Not getting the jar file in maven OS X while including in a project using eclipse or IntelliJ Idea. 

![image](https://cloud.githubusercontent.com/assets/23023146/21471885/baf1fff4-cae7-11e6-8bd4-373a4a0aeceb.png)

**Comment by jekh** [comment]
Please have a look at the landing page on github where the README is displayed.
