### ISSUE TITLE
how to set up new browserMob proxy with grid

### ISSUE THREAD

**Issue by jayantsarda** [lightbody/browsermob-proxy#586]
I am using browserMob in embedded mode with dependency as 
`<dependency>
  <groupId>net.lightbody.bmp</groupId>
  <artifactId>browsermob-core</artifactId>
 <version>2.1.4</version>
 <scope>test</scope>
</dependency>`

I could run a local run and could get the HAR entries but when i try running it with remote driver (with Selenium grid) it does not work . The note in the documentation says:

> Note: If you're running running tests on a Selenium grid, you will need to customize the Selenium Proxy object created by createSeleniumProxy() to point to the hostname of the machine that your test is running on. You can also run a standalone BrowserMob Proxy instance on a separate machine and configure the Selenium Proxy object to use that proxy

I tried using proxy.start(0, InetAddress.getLocalHost()); with proxy , but no luck.

In my case i need entries after user interaction on page (like on scroll ), hence i can not use RestAPI .

Can some one guide more on what kind of customization is needed on seleniumProxy object to make it work with grid?

Thanks

**Comment by jayantsarda** [comment]
I also tried below script which opens the website on the remote machine but does not capture the har entries:
`BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start(0);
Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
seleniumProxy.setHttpProxy("HOSTMACHINE_WHERE_TEST_RUNS:5555<port where>");// this is basically the hostmacine and port where selenium server is running
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
	    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
	    System.setProperty("webdriver.chrome.driver", "<path to chrome exe>");
RemoteWebDriver driver = new RemoteWebDriver(new URL("HOSTMACHINE_WHERE_TEST_RUNS:5555/wd/hub"), capabilities);
proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
proxy.newHar("test");
 driver.get("http://www.google.com");
	    Har har = proxy.getHar();
	    System.out.println(har.getLog().getEntries().size());
	    driver.quit();'

**Comment by jekh** [comment]
You need to set the HTTP and HTTPS proxy fields on the Proxy object to the hostname or IP address and the port that BMP is running on. The hostname/IP address is something only you know, based on your network architecture.
