### ISSUE TITLE
PhantomJSTest.java: Unable to Find element with id 'p_13838465-p'

### ISSUE THREAD

**Issue by nd93dives** [lightbody/browsermob-proxy#59]
I am finding that elements are not being found when running browsermob-proxy 2.0-beta-9 with PhantomJSDriver 1.1.0 and Selenium 2.37.1.

I was also able to confirm this locally by adding  driver.findElement(By.id("p_13838465-p")); after line 57 in src/test/java/net/lightbody/bmp/proxy/PhantomJSTest.java and rerunning the unit test. 

I ended up getting a Unable to Find element with id 'p_13838465-p' error.

**Comment by jekh** [comment]
Since this issue hasn't been appearing in the latest builds with the updated phantomjs dependencies, I'm going to close it. @nd93dives - please feel free to reopen if you're still experiencing issues.
