### ISSUE TITLE
Unable to capture Har file for mobile application

### ISSUE THREAD

**Issue by ankitjain082** [lightbody/browsermob-proxy#596]
Hi, I am using browsermob -proxy for record the har file for mobile application with appium.
I am doing below steps for the same:

1) Install the SSL certificate on Android device and set the proxy for device  Wi-Fi.
2) Add dependency in pom.xml for maven project.
3) Start the Appium server.
4) Run the below below code:

public class linktest {
	public AppiumDriver driver = null;
	public static BrowserMobProxyServer server;

	@BeforeClass
	public void setUp() throws MalformedURLException {

		server = new BrowserMobProxyServer();
		server.start(8089);
		int port = server.getPort();
		Proxy proxy = ClientUtil.createSeleniumProxy(server);
		server.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
		server.enableHarCaptureTypes(CaptureType.REQUEST_HEADERS, CaptureType.REQUEST_CONTENT);
		server.enableHarCaptureTypes(CaptureType.REQUEST_HEADERS, CaptureType.RESPONSE_CONTENT);
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability("deviceName", "Test");

		// capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");

		capabilities.setCapability(CapabilityType.PROXY, proxy);
		capabilities.setCapability(CapabilityType.VERSION, "5.1");

		capabilities.setCapability("platformName", "Android");

		capabilities.setCapability("appPackage", "com.myapplication");

		capabilities.setCapability("appActivity", "com.myapplication.MainActivity");
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

		URL url = new URL("http://0.0.0.0:4723/wd/hub");
		driver = new AndroidDriver<MobileElement>(url, capabilities);
		System.out.println("Port started:" + port);
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
	   

	}

	@Test
	public void login() throws InterruptedException, IOException {
		server.newHar("login.har");
		WebElement eleUsernametxt = driver.findElement(By.xpath("//android.widget.EditText[@text='Username']"));

		eleUsernametxt.sendKeys("username");
		Thread.sleep(3000);
		((AppiumDriver<MobileElement>) driver).hideKeyboard();
		WebElement elePasswordtxt = driver.findElement(By.xpath("//android.widget.EditText[@text='••••••••']"));

		elePasswordtxt.click();
		elePasswordtxt.sendKeys("password" + "\n");
		Thread.sleep(3000);
	

		System.out.println();
	}

	@AfterClass
	public void tearDown() throws IOException {
		Har har = server.getHar();
		HarLog log = har.getLog();
		 File harFile = new File("C:/Har/login13.har");
				 har.writeTo(harFile);
		List<HarEntry> entries = new CopyOnWriteArrayList<HarEntry>(log.getEntries());
		System.out.println(entries);
		for (HarEntry entry : entries) {
			System.out.println(entry.getRequest().getUrl());
		}
		server.stop();
		
	}

}
 
When I run this code then unable to login in to the application and got below Output in .har file:

"timings":{"comment":"","wait":0,"send":0,"connect":245,"receive":0,"ssl":-1,"blocked":0,"dns":1},"serverIPAddress":"Server IP Address","comment":"","time":246},{"pageref":"login.har","startedDateTime":"2017-01-12T09:49:37.778Z","request":{"method":"CONNECT","url":"Project BaseURL","httpVersion":"HTTP/1.1","cookies":[],"headers":[],"queryString":[],"headersSize":0,"bodySize":0,"comment":""},"response":{"status":0,"statusText":"","httpVersion":"unknown","cookies":[],"headers":[],"content":{"size":0,"mimeType":"","comment":""},"redirectURL":"","headersSize":-1,"bodySize":-1,"comment":"","_error":"Unable to connect to host"},"cache":{},"timings":{"comment":"","wait":0,"send":0,"connect":109,"receive":0,"ssl":-1,"blocked":0,"dns":0},"serverIPAddress":"52.172.51.158","comment":"","time":110}],"comment":""}}

Can anyone please suggest me how can I record har file for mobile application.

Thanks,
Ankitjain082@gmail.com

**Comment by jekh** [comment]
I don't have any experience with Appium, but the error in the HAR file you posted says "Unable to connect to host". Are you using the right host name? The `url` in your code has an address of 0.0.0.0, which is a wildcard address meaning "listen on all network interfaces"; you can't make a request to 0.0.0.0.

**Comment by jekh** [comment]
Since there's been no updates to this issue in a while, I'll go ahead and close it.

**Comment by InfantAnto** [comment]
I can able to get the list of entries in HAR file.

Steps I've done are:

1) Install Browser mob proxy certificate in device
2) Configure the System IP and port in device proxy settings.
3) App package and App Active should be correct to start the app.

And the step 1 solved the issue with HAR entries. After installing browser mob proxy certificate i can able capture the network traffic requests.

**Comment by hpsaini** [comment]
How to install Browser mob proxy certificates in a device and configure proxy for capturing HAR data.

Regards,
Harman

**Comment by InfantAnto** [comment]
@hpsaini

1) Install the below certificate in your device
https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/resources/sslSupport/ca-certificate-rsa.cer

You need to go to Setting -> Security in your mobile. 
If you don't know where to install in your mobile, kindly search in google then install above certificate.

2) The device and machine(laptop) should be connected with same wifi network. Check machine's IP by typing ifconfig in terminal.

Then set the same IP and port like 8888 in the wifi manual proxy settings. The same port should be given in your browser mob proxy server code.

**Comment by amreesh** [comment]
Thank you so much, it worked by installing the certificate as explained above. Here is my code for your reference:

[BrowserMobTest.java.txt](https://github.com/lightbody/browsermob-proxy/files/1734945/BrowserMobTest.java.txt)

**Comment by InfantAnto** [comment]
@amreesh Sounds good :+1:
