### ISSUE TITLE
how to build a inetAddress and start browsermob-proxy with it?

### ISSUE THREAD

**Issue by WenRui13** [lightbody/browsermob-proxy#597]
Hi, business application usually has been deployed  on a group of host machines. I want to run my test on the specified host , how to do it with browsermob-proxy ?could u show me a example? tks a lot !

**Comment by WenRui13** [comment]
could u show me a example? tks  a lot !

**Comment by jekh** [comment]
I'm unclear on exactly what your question is. Based on the title, it sounds like you're having some basic Java issues. I'd recommend googling for the answers. You can also look through the examples in the readme for info on using BMP.

**Comment by WenRui13** [comment]
I set the server inetAddress as below:
    @Test
    public void testBMP_2() throws Exception {
        BrowserMobProxy mobProxy = new BrowserMobProxyServer();
        InetAddress inetAddress = InetAddress.getByAddress("prom.shop.jd.com", new byte[]{(byte) 211, (byte) 152, 122, (byte) 10});
        mobProxy.start(0,InetAddress.getLocalHost(),inetAddress);
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(mobProxy);

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        WebDriver driver = new FirefoxDriver(capabilities);
        String testUrl = "http://prom.shop.jd.com/promotion/info/info_queryPromotions.action?pageView.evtType=1";
        final String cookieValue = "my cookie,not real.";

        mobProxy.addRequestFilter(new RequestFilter() {
            @Override
            public HttpResponse filterRequest(HttpRequest httpRequest, HttpMessageContents httpMessageContents, HttpMessageInfo httpMessageInfo) {
                httpRequest.headers().add("Cookie", cookieValue);
                return null;
            }
        });

        driver.get(testUrl);

        Thread.sleep(3000);
        Assert.assertTrue(driver.getTitle().contains("已创建的单品促销"));

        System.out.println(mobProxy.getServerBindAddress().getHostName());
        driver.quit();
        mobProxy.stop();
    }


after run it , I got the java.net.SocketException: Cannot assign requested address: bind: ocsp.digicert.com/117.18.237.29:80 and browser give back the info "Bad Gateway: /promotion/info/info_queryPromotions.action?pageView.evtType=1"

**Comment by WenRui13** [comment]
Hi, Jason , I mean that how can I run my test ont the specified host with multi ipaddress.
