### ISSUE TITLE
BrowserMob does not capture post Payload data( getPostData() returns null )

### ISSUE THREAD

**Issue by jayantsarda** [lightbody/browsermob-proxy#598]
Browsermob version (2.1.4)
Embedded Mode

I have set the proxyServer.setHarCaptureTypes(CaptureType.REQUEST_HEADERS, CaptureType.REQUEST_CONTENT) ;

Still the getPostData on harRequest returns null.

My Sample code is pretty much same as example in docs but for my project URL.
` BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0);

    // get the Selenium proxy object
    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

    // configure it as a desired capability
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

    // start the browser up
    WebDriver driver = new FirefoxDriver(capabilities);

    // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

    // create a new HAR with the label "yahoo.com"
    proxy.newHar("MyProject");

    // open yahoo.com
    driver.get("My URL");

    // get the HAR data
  List <HarEntry> entries = proxy.getHar().getEntries().stream().filter(entry -> entry.getRequest().getMethod().equals("POST")).filter(entry -> entry.getRequest().getPostData().getText().contains("abc")).collect(Collectors.toList());`

.getPostData().getText() throws nullPointer exception.

Any Suggestions?

**Comment by jekh** [comment]
Are you using Selenium 3? If so, to use _any_ proxy with Firefox, you need to configure it using `FirefoxProfile`. See [this answer](http://stackoverflow.com/questions/41089511/getting-request-and-response-using-browsermobproxy-selenium-firefox-marionett/41373808#41373808) for a work-around.

**Comment by jayantsarda** [comment]
Its not working for chrome as well ... do we have any workaround for same . Also I have not upgraded to selenium 3 yet ..(that will be next upgrade I will be taking up)

**Comment by jayantsarda** [comment]
Ok .. looks like calling setHarCaptureTypes again in the code overwrites the old capture type set. In our framework we were adding capture type as and when required one after other assuming the this will be cumulative but instead it overwrites the old setHarCaptureType values (thus in my case CaptureType.Request_Content was over written in middle of the test). I guess in old Browsermob (I could be wrong though) used to be cumulative as we were calling setCapture methods one after other and all of those used to work.
proxyServer.setCaptureContent(true);
proxyServer.setCaptureHeaders(true);

Not sure if this is on purpose but toggling one capture type on the fly may be more flexible then just one all the values again and again in between the test

Pls close the issue if project members does not agree :)

**Comment by jekh** [comment]
Use `proxyServer.enableHarCaptureTypes(...)` to turn a capture type on without affecting other capture types. To use an HTTP analogy, `enable...` is like a POST, `set...` is like a PUT. The documentation for those methods explains this pretty well.

**Comment by cglacet** [comment]
How does that translates to the CLI? I'm asking that because I use a python wrapper for this and it simply [interfaces the the CLI](https://browsermob-proxy-py.readthedocs.io/en/stable/client.html). I see that there is something that I already use `captureContent` which is said to be `Boolean, capture content bodies or not. Optional, default to "false"`, but this only captures few things and bodies do not seem to be part of it.

**Comment by cglacet** [comment]
Nevermind I found the answer, I was just passing the parameter to the proxy creation instead of the HAR creation. 

For other python users:
```python
har_options = {'captureContent': True}
proxy.new_har(url, options=har_options)
```
