### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sskuts** [lightbody/browsermob-proxy#60]
Hi,

I've downloaded latest release 9 zip from http://bmp.lightbody.net/ and followed the instructions for using BrowserMobProxy with Selenium.

Tests are executing remotely, so I've raised proxy (using batch from zip) on remote VM. Everything works perfect except cases with capturing big files content (e.g. 50Mb). In such situation I'm getting out of memory exception.

I've tried to set EXTRA_JVM_ARGUMENTS=-Xmx128m in batch file. No luck. I've also increased system java heap size, run hub / nodes with Xms arg, executed sources with this option - the same exception.

Any ideas?

Thanks,
Sergey

**Comment by jekh** [comment]
I'm going to close this since it seems to come down to configuring the JVM settings on the OP's machine. 

For future reference, in 'standalone' mode you can set JVM options using the JAVA_OPTS environment variable, like this (in Windows):
```
C:\browsermob-proxy\bin> set JAVA_OPTS="-Xmx500m"
C:\browsermob-proxy\bin> browsermob-proxy.bat
```
Replace the `500m` with your desired JVM heap size.
