### ISSUE TITLE
Not able to capture detailed HAR data 

### ISSUE THREAD

**Issue by agrotarun** [lightbody/browsermob-proxy#601]
Hi

I am facing some issues in collecting har data with the BrowserMob Proxy. The har file is created, but it does not contain details of individual calls. 
I cloned the latest BrowserMob Proxy and running the code as exactly written in Readme.md. However my har file is empty. Please help me in this regard

Details :- Latest Selenium + Browser Mob + Driver (on Mac)

Har Output :- {"log":{"version":"1.2","creator":{"name":"BrowserMob Proxy","version":"2.1.4","comment":""},"pages":[{"id":"yahoo.com","startedDateTime":"2017-02-02T18:16:00.918Z","title":"yahoo.com","pageTimings":{"comment":""},"comment":""}],"entries":[],"comment":""}}

Code :-
 // start the proxy
    BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0);

    // get the Selenium proxy object
    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

    // configure it as a desired capability
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

    // start the browser up
    WebDriver driver = new FirefoxDriver(capabilities);

    // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

    // create a new HAR with the label "yahoo.com"
    proxy.newHar("yahoo.com");

    // open yahoo.com
    driver.get("http://yahoo.com");
    driver.findElement(By.id("UHSearchWeb")).click();

    // get the HAR data
    Har har = proxy.getHar();

HAR object trace image :-

Thanks,
Tarun
<img width="393" alt="screen shot 2017-02-03 at 12 04 41 am" src="https://cloud.githubusercontent.com/assets/8501577/22582737/9235fc78-ea0e-11e6-8599-1e8114131dce.png">

**Comment by jekh** [comment]
This is most likely caused by a bug in Selenium. See [this answer](http://stackoverflow.com/a/41373808/4256475) on SO for a work-around.

This has been causing a fair amount of confusion lately, so I'll update the docs to reflect this work-around.
