### ISSUE TITLE
404 for https resources accessing https://misspestanas.com

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#605]
Browsermob-proxy is not enable to connect to: https://misspestanas.com/

I'm getting 403 for root resource and 404 for most of other resources, for example:

Found internal error code:403->https://misspestanas.com/es/
Found internal error code:404->https://misspestanas.com/themes/leostyl/css/bootstrap.css
Found internal error code:404->https://misspestanas.com/themes/leostyl/css/product_list.css
Found internal error code:404->https://misspestanas.com/js/jquery/jquery-1.11.0.min.js
....

I'm testing with the last version: 2.1.4. Issue is reproduced with 2.1.1 too.
I'm able to access to the web properly (https://misspestanas.com/) directly from my browser

This is my code:
`	        

           public void test(){		
	     BrowserMobProxyServer proxy;
	    DesiredCapabilities capabilities;		
            WebDriver driver;		
            proxy = new BrowserMobProxyServer();
            proxy.setTrustAllServers(true); 
	    proxy.start(0); 
	    
	    HashSet<CaptureType> enable = new HashSet<CaptureType>();
	    enable.add(CaptureType.REQUEST_HEADERS);
	    enable.add(CaptureType.REQUEST_CONTENT);
	    enable.add(CaptureType.RESPONSE_HEADERS);
	    proxy.enableHarCaptureTypes(enable);
	    HashSet<CaptureType> disable = new HashSet<CaptureType>();
	    disable.add(CaptureType.REQUEST_COOKIES);
	    disable.add(CaptureType.RESPONSE_COOKIES);
	    proxy.disableHarCaptureTypes(disable);
	    
	    //get the Selenium proxy object
	    Proxy selProxy = ClientUtil.createSeleniumProxy(proxy);

	    // configure it as a desired capability
	    capabilities = new DesiredCapabilities();
	    capabilities.setCapability(CapabilityType.PROXY, selProxy);
	    capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS,true);
	    capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR,UnexpectedAlertBehaviour.ACCEPT);

	    
	    ResponseFilter responseFilter = (response, contents, messageInfo) -> {
	    	int code = response.getStatus().code();
			if (code >= 400 && code < 600){
				System.out.println("Found internal error code:"+code + "->"+messageInfo.getOriginalUrl());
	    	}
	    };
		proxy.addFirstHttpFilterFactory(new ResponseFilterAdapter.FilterSource(responseFilter, 4194304)); //4mb. avoid crash with large images

	    FirefoxProfile profile = new FirefoxProfile();
	    try {
			InputStream resource = this.getClass().getClassLoader().getResourceAsStream("webdriver.zip");
			File work = new File("work");
			if (!work.exists()){
				work.mkdirs();
			}
			work.deleteOnExit();
			File file = new File(work,"webdriver.zip");
			Files.copy(resource, file.getAbsoluteFile().toPath(), StandardCopyOption.REPLACE_EXISTING);
			profile.addExtension(file);
		} catch (Exception e) {
			e.printStackTrace();
		}
	    profile.setPreference("browser.cache.disk.enable", false);
	    profile.setPreference("browser.cache.memory.enable", false);
	    profile.setPreference("browser.cache.offline.enable", false);
	    profile.setPreference("network.http.use-cache", false);
	    profile.setPreference("app.update.auto", false);
		profile.setPreference("browser.cache.disk_cache_ssl",false);
		profile.setPreference("security.OCSP.enabled",false);
		profile.setPreference("security.enable.tls",false);
		profile.setPreference("security.OCSP.enabled",0);
	    
	    profile.setAcceptUntrustedCertificates(true);
	    profile.setAssumeUntrustedCertificateIssuer(true);
	    
	    driver = new FirefoxDriver(new FirefoxBinary(),profile,capabilities);
	    
		driver.manage().window().setSize(new Dimension(1024, 768)); 
		driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
		
		/* CALL */
		driver.manage().deleteAllCookies();
		try{
	    	driver.get("https://misspestanas.com"); //load the page
	    }catch(org.openqa.selenium.TimeoutException e){
	    	e.printStackTrace();
	    }
		
		System.out.println();
	}`

**Comment by jekh** [comment]
I'm able to reproduce this issue against this site, but I can find no explanation for it. I don't see any issues on the BMP side. Are you able to repro against any other sites? It's possible that the origin server is getting overloaded or behaving in a non-compliant way.

**Comment by jpereira06** [comment]
No, I'm not able to reproduce this issue in other sites. I have no control over the server but if you access it with your browser it always works properly.

**Comment by jpereira06** [comment]
any news on this?

**Comment by jekh** [comment]
No updates. I still don't see anything wrong on the BMP side. It could be a server-side issue, or it could be some very subtle bug. I'd like to wait and see if the issue comes up on another site.

**Comment by patotskiy** [comment]
Same issue with https://profil.yousee.dk/
Could you please look at this? 
@jekh

**Comment by jekh** [comment]
Without any further information, there's not much I can do about this. I suspect it's the server throttling requests.
