### ISSUE TITLE
Get stuck while getting har records

### ISSUE THREAD

**Issue by yan0621** [lightbody/browsermob-proxy#608]
Hi, 

I am using browsermob + webdriver to catch web contents from a list of urls. To speed things up, I start multiple proxys on one proxyserver and make them work in parallel. The basic workflow looks like this:

```
start proxyserver;
for each url in url_list:
  start a new thread, in each thread:
    get a port;
    create a proxy on proxyserver;
    set up har;
    create a webdrvier browser;
    load page with url;
    quit driver;
    get har content; // **performance issue here**
    shut down proxy;

stops proxyserver after all threads are finished
```

However, I find that some threads get stuck in 'get har content' step. It could stop there for more than 20 minutes. And I am getting lost of such exceptions in logs:

> [INFO  2017-02-15T05:10:21,107 org.littleshoot.proxy.impl.ClientToProxyConnection] (LittleProxy-5-ClientToProxyWorker-0) (AWAITING_INITIAL) [id: 0xc8a7db1b, L:/10.237.131.37:14570 - R:/10.237.150.80:41636]: An IOException occurred on ClientToProxyConnection: Connection reset by peer 

But this workflow works and I can get all the web contents at last, even though I have to wait for a long time.

I am using latest 2.1.4 release version.

Does anybody know what's happening here?

Thanks!

**Comment by jekh** [comment]
How large are the HAR files you're getting?

**Comment by yan0621** [comment]
Files are relatively small. Most of them are less than 100K. Very few are over 500K. But I am trying to get lots of files at the same time, around 20 for each thread, and there are 200~300 counting all working threads. 

I finally gave up getting har contents from proxy directly. Now I only use the proxy to record request urls and fetch content from those urls separately.

**Comment by jekh** [comment]
500k HAR files are fairly large, and probably what was causing the slowdown. Glad you got it working, though. I'll close this issue.
