### ISSUE TITLE
Few of the resources are missing in the har file generated

### ISSUE THREAD

**Issue by dhineshbabu** [lightbody/browsermob-proxy#609]
Hi ,

I am trying to capture har files for one of our business flows that includes multiple page actions. But we are observing that few of the resources are bit presented in the generated har file. Only login page's har file is matching with the resources count in http watch. Can you please assist me in resolving the issue?

Thanks,
Dhinesh

**Comment by jekh** [comment]
We'll need more information. What are you expecting to see, and what is missing? What URL can we repro this issue against? How are you configuring BMP? etc.

**Comment by dhineshbabu** [comment]
Hi,

Please find the attached files. I have added the screenshots of the har files generated from both browser and from bmp as well. Also I have attached the code. Unfortunately i was not able to extract the actual har file from our LAN. 

You can observe that only 15 requests being captured from bmp but the actual count is 75.

Thanks,
Dhinesh
[Screenshot.docx](https://github.com/lightbody/browsermob-proxy/files/788907/Screenshot.docx)
[code.txt](https://github.com/lightbody/browsermob-proxy/files/788908/code.txt)

**Comment by jekh** [comment]
I don't have enough information to reproduce this issue, so I'm going to close it. Feel free to reopen it along with:
1. Steps to reproduce (including a publicly-available URL that we can reproduce against)
2. Information on what you expect vs. what you're seeing
3. Log statements and other information that might be helpful to understand the issue you're facing
4. Screenshots showing the issue, either embedded in the issue or available from a publicly-accessible image hosting site.
