### ISSUE TITLE
BMP server is not capturing ominiture calls

### ISSUE THREAD

**Issue by lnallan** [lightbody/browsermob-proxy#611]
Why BMP server not reading the ominiture calls?
I have enabled all capture types. 

ProxyServer server = new ProxyServer();
		server.start();
		server.newHar("alltests.har");
		server.setTrustAllServers(true);
		server.setCaptureBinaryContent(true);
		server.setCaptureHeaders(true);
		server.setCaptureContent(true);

**Comment by jekh** [comment]
There's no reason BMP would be singling out omniture calls. It does look like you're using the old ProxyServer implementation though. You should upgrade to the latest (see the readme).

Feel free to reopen with additional information and steps to repro if you're still having this issue with the latest version + the BrowserMobProxyServer implementation.
