### ISSUE TITLE
I am unable to use this with npm selenium-webdriver-js

### ISSUE THREAD

**Issue by guptarajatkn** [lightbody/browsermob-proxy#613]
I initiate the session using : 

var Proxy = require('browsermob-proxy').Proxy;
var bProxy = new Proxy();

console.log('\nbProxy : ', bProxy);

bProxy.start([], function (err, data) {
   if (err) {
    console.log('\n\nerr : ', err);
   } else
   console.log('\n\ndata : ', data);
   });
 driver = new selenium.Builder().withCapabilities({
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    "args": ["start-maximized"]
                },
                path: chromedriver.path
            }).setProxy(proxy.manual({ http: "localhost:8080" })).build();

//giving Econnrefused error
//after starting browsermob-proxy.bat server 
//err :  browsermob-proxy returned error

**Comment by jekh** [comment]
You might want to check the BMP logs, etc. Not much information here to work with.
