### ISSUE TITLE
Jar files not published to maven central

### ISSUE THREAD

**Issue by roidelapluie** [lightbody/browsermob-proxy#614]
Hi,

Is it possible to publish jar files to mvn central please? For 2.1.X only pom files are present.

Thanks.

![sob2](https://cloud.githubusercontent.com/assets/291750/23394957/3618d492-fd8c-11e6-8a44-82d055e56d0f.png)

**Comment by jekh** [comment]
Please review the readme file for the artifacts to use. All artifacts are published to Central.

I do need to publish a relocation pom, though.

**Comment by roidelapluie** [comment]
Thanks!
