### ISSUE TITLE
Force Terminating BMP Proxy - Terminates JVM

### ISSUE THREAD

**Issue by baclark774** [lightbody/browsermob-proxy#625]
In some cases during a aborted test case it's necessary to force terminate a running proxy on a particular port in embedded mode. We currently do this with pkill or taskkill depending on the OS it's running on.

But when we kill the port from an external job/task, any job that was in flight with that proxy will crash with a jvm abort "system exit called".

With the embedded proxy, is there any way around this?

**Comment by jekh** [comment]
Not sure I fully understand what you're trying to do, but since BMP runs in a JVM, force-killing the java process is going to kill BMP and anything else running in that JVM. BMP does allow you to gracefully shutdown a server using the stop() method though.
