### ISSUE TITLE
Har to JMX converter

### ISSUE THREAD

**Issue by ankitjain082** [lightbody/browsermob-proxy#631]
Hi,

I am successfully generate the .Har file through BrowserMob but when I try to convert har to JMX using blazemeter then it's showing me error.
It works when I generate the .Har file through charles proxy.
Can you please let me know there is any way to convert .Har file to Jmx with using Browsermob.

Thanks.

**Comment by jekh** [comment]
HAR->JMX isn't supported. I don't see why it shouldn't work, but since it doesn't, I'd welcome a PR to fix whatever the issue is.
