### ISSUE TITLE
How to capture parameters and values in the har file

### ISSUE THREAD

**Issue by ankitjain082** [lightbody/browsermob-proxy#633]
Hi,

Can you please let me know how can I capture parameter value.
I am working on below scenario:

Record .har file for yahoo.com
1) Enter the yahoo.com
2) Click on 'Sign In' button.
3) Enter the valid email ID and click on 'Next' button.
4) Enter the password and click on 'Sign In' button.
5) Open recorded file in har editor.
But unable to find out Login name and password in har file.

**Comment by jekh** [comment]
I'm going to close this issue because there's not enough actionable information in it. Please have a look at the README file and reopen the issue if you can provide more context.
