### ISSUE TITLE
Link dead for browsermob-proxy-2.0-beta-9-bin.zip

### ISSUE THREAD

**Issue by qwertychouskie** [lightbody/browsermob-proxy#634]
https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip gives 403 Forbidden.  I know this seems weird, but is there a working link for this file?  I am trying to troubleshoot [this failed Travis build](https://travis-ci.org/w3c/Mobile-Checker/builds/227048136), and the main difference between it and [this old but working build](https://travis-ci.org/w3c/Mobile-Checker/builds/69915817) seems to be the change from browsermob-proxy-2.0-beta-9-bin.zip to browsermob-proxy-2.0.0-bin.zip, so I would like to try it with beta-9 if possible to eliminate it as a variable.

**Comment by jekh** [comment]
Don't use 2.0-beta-9 - it's ancient! If for some terrible reason you need it, you can to rebuild from source or grab it from the github releases page: https://github.com/lightbody/browsermob-proxy/releases?after=browsermob-proxy-2.1.0-beta-2 . But don't do that!
