### ISSUE TITLE
bmp dose not start in a docker container running on Mesos

### ISSUE THREAD

**Issue by aakazemaa** [lightbody/browsermob-proxy#635]
I installed bmp in a docker container and ran it on my docker engine on my **Mac successfully**.
(The server starts, proxy gets created, etc...)

But when I deployed the same **docker image** into **Mesos**, bmp **fails** to start.

I only see the following after issuing the bmp start command:

_Running BrowserMob Proxy using LittleProxy implementation. To revert to the legacy implementation, run the proxy with the command-line option '--use-littleproxy false'._

**But** there is no _bmp.log_ or _startup messages_.

I tried to start bmp with all possible parameters passed to it.
- start it the in normal way ./browsermob-proxy -port 8080
- or start it with specifying the binding IP address:
   browsermob-proxy-2.1.4/bin/browsermob-proxy -port 8383 -address <the ip of docker container>

bmp dose not start inside a  docker which is deployed on Mesos; but it works on docker engine on mac (or any ubuntu vm).

Please let me know what the issue might be and how it can be remedied or if there can be a workaround. Thanks.

**Comment by jekh** [comment]
I have no experience with mesos, so I'm not sure. I also run BMP in a docker container locally, and I've never had issues with it. Feel free to reopen if you gather more information.
