### ISSUE TITLE
Browsermob POST DATA content is coming in unsupported format

### ISSUE THREAD

**Issue by BharathMamillapalli** [lightbody/browsermob-proxy#636]
**Browsemob Version Used: ** Browsermob 2.1.2

Issue:
I am getting my POST data uploaded to a batch file and getting. Content type of contents is "application/Json".

But I am not able to see any Json text in output of browsermob proxy, it is coming as plain text, I am seeing contents as below :
B\u0001�\u001A88���U\fx\u0006�đ_x��A�GP�Tx^9�Ve�Q���ĕ��\u0014�fi\u0013Lct�\\�\u0002G�Ef���\u0018$4\u0003��~.�\u0001�}6�\u0004\u0000\u0000","comment":""}

Encoding being used is gzip for the POST data, but I am able to see contents when I use Charles proxy, but I am not able to see contents in browsermob output.

I have tried using Gzip decompressor method present in Browser mob source code, but I am not getting any text content to see my gzipped content.

Please help me out how to get my POST content as normal Json text file instead of some encoded format.
If any additional information required for solving issue, please ask me.

**Comment by maninderjeet** [comment]
hi,
I'm also facing same issue. Did you get any solution for this ?
