### ISSUE TITLE
POST data params missing - ClonedInputStream problem

### ISSUE THREAD

**Issue by danielalexiuc** [lightbody/browsermob-proxy#64]
For some POST requests, the POST params do not appear. The problem happens here:

    BrowserMobHttpClient.java (line 715):
    final String content = new String(req.getCopy().toByteArray(), "UTF-8");

At this point, req.getCopy() is empty, again only for SOME post requests, I'm not sure what triggers it. If I debug and try to read the input stream at this point, the data is actually there, but it is just not getting populated into the copy. After I do this during my debug session...

    IOUtils.toString(req.getInputStreamEntity().getContent())

...the copy seems to be populated with data, and everything works correctly.

**Comment by jekh** [comment]
This issue should be completely resolved with LittleProxy. I'm going to close the issue. @danielalexiuc - can you open a new issue if you still experience this problem with the LP implementation?
