### ISSUE TITLE
Using QueryStringDecoder.class from netty breaks the order of query string parameters

### ISSUE THREAD

**Issue by evgenijvorobey** [lightbody/browsermob-proxy#645]
Hi, 
if netty doesn't fix the [issue](https://github.com/netty/netty/issues/6812), is it possible to use other external library to avoid breaking the order of the params(with other structure storing the elements).

**Comment by jekh** [comment]
As mentioned in the netty issue, the order of query string parameters isn't guaranteed. Since BMP uses LP, which uses netty, this behavior won't be changed unless netty decides to change their parser.
