### ISSUE TITLE
Don't use MITM for some hosts

### ISSUE THREAD

**Issue by patotskiy** [lightbody/browsermob-proxy#653]
Hi All, 
Is it possible not to apply MITM for facebook.com or twitter.com? If I decrypt these calls, I not able to login into my application.

**Comment by patotskiy** [comment]
Any updates?

**Comment by jekh** [comment]
It's not possible for BMP to determine a priori what site a TLS connection is trying to connect to unless it terminates TLS. However, you can have the browser bypass the proxy (i.e. not send requests to BMP) for specific domains.

**Comment by youchen** [comment]
Just note here for future readers.
The following may be configured on Firefox WebDriver for bypassing the BMP.
`firefoxProfile.setPreference("network.proxy.no_proxies_on", "facebook.com");`
