### ISSUE TITLE
Browsermob set upstream proxy as PAC (Automatic Configuration Script) file

### ISSUE THREAD

**Issue by kallolghose** [lightbody/browsermob-proxy#659]
Hi, 

I am using browsermob behind a corporate proxy. And the corporate proxy used a PAC file. So wanted to ask is there a way to use browsermob behind a PAC file.

Found some links regarding the same saying to use **setChainedProxyManager** but did not get any example to use it. 

Please tell me what would the best approach to use browsermob behind a PAC file.

Thanks in advance !!!

**Comment by jekh** [comment]
BMP doesn't understand PAC, so you'd have to write the code to parse it yourself. Should be fairly straightforward, though, as the PAC files are quite simple.
