### ISSUE TITLE
Invalid URL escaping

### ISSUE THREAD

**Issue by nirvdrum** [lightbody/browsermob-proxy#66]
BMP does its own URL escaping and seems to be very aggressive about it.  There's a reference to a JIRA issue, but it's for a tracker I don't think anyone has access to any longer.  And the comment seems a bit out of date:

https://github.com/lightbody/browsermob-proxy/blob/browsermob-proxy-2.0-beta-9/src/main/java/net/lightbody/bmp/proxy/http/BrowserMobHttpClient.java#L324-L338

I just ran into a problem where that bit of code converted a "~" in the URL path to "%7E".  CloudFront apparently does an exact match and determined the encoded URL wasn't the same and sent me back a 404.

I can fix this easily enough, but since this was deliberately added I didn't want to blindly change it.  A couple questions I have are:

- Why are these characters specially handled?
- Why not use a standard URL escape utility?
- Since the common use case is requests from browsers, can't we trust them to send properly encoded URLs?

**Comment by jekh** [comment]
@romovs -- does using LittleProxy solve this issue with URL escaping?

**Comment by romovs** [comment]
Yes, it works fine now with LittleProxy.
