### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by taraa62** [lightbody/browsermob-proxy#661]
Hello
I want to run a proxy server like http / https but I have nothing to do.

Tried to generate keys by the program itself - KeyStore Explorer
Https://n8felton.wordpress.com/2015/06/22/creating-a-java-keystore-jks-for-papercut-with-keystore-explorer/

And your utilities like LittleProxyDefaultConfigExample.java
When I set up a batch proxy server on the BMP, then the https page is not loaded, therefore, I see the request goes, but there is no pesponse.

Help check https certificates.

My test project -
https://drive.google.com/file/d/0B0_abTcm0_TESnBYMEJWaWlxNDQ/view?usp=sharing

**Comment by jekh** [comment]
See the README for details; you need to have your browser/other client trust the BMP root CA.

**Comment by PAVITHRA001** [comment]
> See the README for details; you need to have your browser/other client trust the BMP root CA.

Even I am getting the same issue.Can you elaborate on this reply that would be helpful
