### ISSUE TITLE
C# Is it possible to use the setChainedProxy() function in C# with browsermob

### ISSUE THREAD

**Issue by JvB94** [lightbody/browsermob-proxy#678]
Hi guys,

I need to  use the setChainedProxy() function. I'm using the Browsermob.NET Library (https://github.com/AutomatedTester/AutomatedTester.BrowserMob) but cant find any function in it and I also dont know how i could give a Proxy as an argument to the .exe which is opened with the browsermob-proxy.bat. Im using browsermob to capture traffic which is sent in selenium browser. So in general i need to know how its possible to forward the traffic which is sent to browsermob, to another proxy and then to the target page. It must be C#, but there i cant find the setChainedProxy function

**Comment by jekh** [comment]
I am not sure, as I don't maintain the C# wrapper. You might try asking with them, or just submitting a PR. setChainedProxy() is relatively new, so it probably just hasn't been added to that wrapper.

**Comment by axtens** [comment]
It's something I'd like to add to my fork of their project, but time isn't on my side at the moment. Also, I haven't found out how to make my fork into a nuget package. 

There doesn't seem to be much activity on the project, so you might be forced to fork/clone and make your own changes.
