### ISSUE TITLE
Public release containing #666 is needed

### ISSUE THREAD

**Issue by shs96c** [lightbody/browsermob-proxy#681]
Guava 23 removed `HostAndPort.getHostText`. Guava 20 contains the replacement method (`getHost`), so people still inexplicably using Java 7 can continue to use BMP.

Lots of people shy away from using snapshot or beta releases. Can we please have a public release so that people can upgrade their guava versions?

**Comment by asolntsev** [comment]
Please, release it! We all need it!...

**Comment by asolntsev** [comment]
@jekh Have you any plans to release a next version soon?

**Comment by jekh** [comment]
Yes, a great idea. I'll release one this weekend.

**Comment by krnkazaryan** [comment]
I just can not connect to the site.
I do the following
"proxy = new BrowserMobProxyServer();
proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
proxy.start(0);
int seleniumProxy = proxy.getPort();
FirefoxProfile profile = new FirefoxProfile();
	 profile.setPreference("network.proxy.http", "localhost");
	 profile.setPreference("network.proxy.http_port", seleniumProxy);
	profile.setPreference("network.proxy.ssl", "localhost");
	 profile.setPreference("network.proxy.ssl_port", seleniumProxy);
	 profile.setPreference("network.proxy.type", 1);
	profile.setPreference("network.proxy.no_proxies_on", "");
DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability(FirefoxDriver.PROFILE, profile);
FirefoxOptions options = new FirefoxOptions(capabilities);
 proxy.newHar(domain);
selenium.get(url);
Har har = proxy.getHar();
FileOutputStream fos = new FileOutputStream(strFilePath);
har.writeTo(fos);
Thread.sleep(25000);
selenium.quit();
proxy.stop();"


An error appears on the line "selenium.get(url);"

As a result, the browser writes that the connection was dropped

**Comment by xtj7** [comment]
Yes, a new release would be very much appreciated 😃

**Comment by asolntsev** [comment]
@jekh have you had a chance to release?

**Comment by asolntsev** [comment]
@jekh Can I help with this release somehow?

**Comment by jekh** [comment]
@asolntsev Just keep pushing me to do it :) This Saturday I will push out the release though.

**Comment by asolntsev** [comment]
@jekh How is going on? 
Still, can I help somehow?

**Comment by jekh** [comment]
Done! 2.1.5 has been released, with updated guava (now 23) support.

**Comment by asolntsev** [comment]
@jekh Cool! Thank you. 

P.S. Is it ok that MBP 2.1.5 uses pretty old version of littleproxy: `net.lightbody.bmp:littleproxy:1.1.0-beta-bmp-17`? There is much more newer version: `org.littleshoot:littleproxy:1.1.2`

**Comment by jekh** [comment]
Yes, the version bundled with BMP is current LP plus the fix for Guava 22. So it's actually more current than the LP release.

**Comment by asolntsev** [comment]
@jekh Hm... It doesn't seem so...

With the latest `littleproxy 1.1.2`, I am getting the following error:

```
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
	at org.littleshoot.proxy.impl.ProxyToServerConnection.addressFor(ProxyToServerConnection.java:961)
```

While `littleproxy 1.1.0-beta-bmp-17` works fine for me.

**Comment by jekh** [comment]
That's exactly right. Use the BMP version, which is more current than the official LP release.

**Comment by asolntsev** [comment]
@jekh well, thanks for sharing the knowledge :)
Maybe it's better to increase its version number to `1.1.3` or something like this?

**Comment by jekh** [comment]
The idea is not to conflate the two. It would only be an issue if you added an explicit dependency on LP, so I'd recommend not doing that.

**Comment by asolntsev** [comment]
@jekh Yes, it's right: it can only be an issue when somebody explicitly sets LP dependency. And I am that man: I like to use the latest versions of all dependencies, and I regularly update them. 

When I see `1.1.0-beta-bmp-17` and `1.1.2`, I choose the latter because it seems to be the latest. It's really confusing.  

Generally, it doesn't seem to be a good idea to use some "beta" dependency in production, right?
