### ISSUE TITLE
On Guava : NoSuchMethodError: com.google.common.net.HostAndPort.fromHost

### ISSUE THREAD

**Issue by mvipulbharat** [lightbody/browsermob-proxy#685]
I have updated to Guava 22  but still get this error

**Comment by pbellchambers** [comment]
Also getting this issue.

**Comment by shyster** [comment]
it's issue in org.littleshoot.proxy + guava
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
	at org.littleshoot.proxy.impl.ProxyToServerConnection.addressFor

**Comment by seanf** [comment]
Probably related to #398 and #638. See also #681.

**Comment by jekh** [comment]
This issue should be solved with the 2.1.5 release.

**Comment by dmytrocx75** [comment]
What's the decision of this problem?

**Comment by jekh** [comment]
Use 2.1.5 and everything should work just fine.

**Comment by dmytrocx75** [comment]
Not quite. I got the proxy working only with versions 20-22 of guava. I described it here: [Issues with BrowserMob Proxy and Selenium](https://stackoverflow.com/questions/47223626/)
