### ISSUE TITLE
Cannot access the proxy server on embedded mode

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#69]
Hi,

When using embedded mode I cant seem to access the proxy server. It throws Http Error 403 Forbidden. Is this a limitation in embedded mode? The reason I need this is that I am using a remote webdriver and I need to use the proxy server that the embedded mode created to be used remotely.

**Comment by jekh** [comment]
I'm going to close this since embedded mode has been working. @breinjhel - if you are still having problems, please reopen and post more information and some test code.

**Comment by breinjhel** [comment]
@jekh Ok. Thanks.
