### ISSUE TITLE
Use another proxy

### ISSUE THREAD

**Issue by hnhnarek** [lightbody/browsermob-proxy#695]
Can I tell browsermob-proxy to use an external proxy?
The problem is I want to capture requests and use another proxy to change ipaddress. Is it possible?

**Comment by richardpenman** [comment]
Was also wondering about this - checked the source code and did not find a way

**Comment by hnhnarek** [comment]
> Was also wondering about this - checked the source code and did not find a way
seems there is no way to do that, so I've used mitmproxt (https://mitmproxy.org/), it solved my problem

**Comment by hnhnarek** [comment]
seems there is no way to do that with browsermobproxy, so I've used mitmproxt (https://mitmproxy.org/), it solved my problem
also check [simple python code for mitmproxy](https://gist.github.com/hnhnarek/99537629b5632e79e30b203fc5320b01)

**Comment by bezda** [comment]
`browseMobProxy.setChainedProxy()`
