### ISSUE TITLE
browsermob-proxy having issues with JAVA 9

### ISSUE THREAD

**Issue by Corefinder89** [lightbody/browsermob-proxy#724]
In Java 9, there is an issue with browsermob proxy as it fails to collect the HTTP responses as HTTP archive object. So, basically when I do a proxy.new_har('some data') and after that, if I try to dump the data as a JSON object via json.dumps(proxy.har, ensure_ascii=false) it ends up giving me a python exception as "Nothing to decode". After much debugging, I cam out with the conclusion that the proxy is not collecting the HTTP archive data because of which it is failing in JAVA 9 version. After downgrading the JAVA version to 8 it resolved the issue. Can this issue be rectified for the upcoming JAVA versions?

**Comment by ericbeland** [comment]
@Corefinder89 We have a new fork of the BrowserMob proxy with support up to Java 11. Please feel free to give it a shot!
[BrowserUp Testing Proxy](https://github.com/browserup/browserup-proxy)

**Comment by Corefinder89** [comment]
Thanks @ericbeland. Sure i will give it a try
