### ISSUE TITLE
Need help to setup Browsermob proxy with Appium

### ISSUE THREAD

**Issue by selenUser** [lightbody/browsermob-proxy#747]
I want to get Har file for android native app, and with this setup I'm getting empty file.
I installed certificate on my device, then create by java code my appium server, create browsermob proxy and start android driver.

Thanks for help !
appium code:
`AppiumServiceBuilder appiumServiceBuilder = new AppiumServiceBuilder()
                .withIPAddress("127.0.0.1")
                .usingPort(port)
                .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, String.valueOf(bpPort))
                .withLogFile(logFile);`

browsermob code:
`proxy = new BrowserMobProxyServer();
        proxy.start();
        seleniumProxy = ClientUtil.createSeleniumProxy(proxy);`

android driver code:
`browserMobProxy.getProxy().enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
        browserMobProxy.getProxy().enableHarCaptureTypes(CaptureType.REQUEST_HEADERS, CaptureType.REQUEST_CONTENT);
        browserMobProxy.getProxy().enableHarCaptureTypes(CaptureType.RESPONSE_HEADERS, CaptureType.RESPONSE_CONTENT);
        browserMobProxy.getProxy().setHarCaptureTypes(CaptureType.getHeaderCaptureTypes());
        browserMobProxy.setHarRef("har_" + Thread.currentThread().getId());
        browserMobProxy.getProxy().newHar(browserMobProxy.getHarRef());

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceManager.getDeviceName());
        capabilities.setCapability(MobileCapabilityType.UDID, deviceManager.getDeviceUdid());
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 60 * 30);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
        capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, currentPackageName);
        capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, currentActivityName);
        capabilities.setCapability(CapabilityType.PROXY, browserMobProxy.getSeleniumProxy());
        capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        capabilities.setCapability("unlockType", "pin");
        capabilities.setCapability("unlockKey", "****");

        URL serverAddress = new URL("http://127.0.0.1:" + port + "/wd/hub");
        androidDriver = new AndroidDriver(serverAddress , capabilities);`

**Comment by selenUser** [comment]
@jekh can you please help ?

**Comment by maninderjeet** [comment]
@selenUser For appium you can't set proxy in desired capabilities.
You have to modifying your wifi setting to Add manual Proxy(add browser mob proxy host and port in that) and then you can capture requests with appium.
