### ISSUE TITLE
proxy recognised as AdBlocker when running on Docker

### ISSUE THREAD

**Issue by dnphung** [lightbody/browsermob-proxy#750]
**Selenium/hub 3.7.1**
**Selenium/node-firefox-debug:3.7.1**
**org.seleniumhq.selenium selenium-java version: 3.8.1**
**browsermob-core version: 2.1.5**

Hi!

When using browsermob proxy, firefox cannot play the video player. It says that an AdBlocker has been detected. If I am not initialising browsermob proxy the video player can be played normally. 

Any hints?

Thanks in advance!

**Comment by CRC-Mismatch** [comment]
You forgot the most important of all information: what/where are you trying to access, that is failing?

**Comment by dnphung** [comment]
This issue is closed. The problem was the connection via websocket. As browsermob proxy is not supporting websockets right now. The video player under test recognized it as an adblocker.
