### ISSUE TITLE
responseFilter contents are null when chrome devtools shows the response body

### ISSUE THREAD

**Issue by ryan-snyder** [lightbody/browsermob-proxy#762]
I am running BrowserMobProxy with selenium for testing. Part of the testing requires checking to see if a value is being returned from an api call. The problem though is that while chrome devtools shows the value being returned in the response, my responeFilter has the HttpMessageContents as null. 

Versions: 
* Selenium 3.12.0
* browsermob-core: 2.1.5

Sample Code:
```
public void filterResponse(io.netty.handler.codec.http.HttpResponse response, HttpMessageContents contents,HttpMessageInfo message) {
				if(message.getOriginalUrl().endsWith("/some/api/endpoint")) {
                                       String value = contents.getTextContents();
                                 }
```
In chrome  devtools, while running my tests this api call returns some json with the value I want in it. I also have a request filter that checks some values too, and the request filter works fine.

Code to set up proxy:
```
                BrowserMobProxy proxy = new BrowserMobProxyServer();
		proxy.start(0);
		Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
		ChromeOptions options = new ChromeOptions();
		options.setCapability(CapabilityType.PROXY, seleniumProxy);
		options.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		options.setAcceptInsecureCerts(true);
```

**Comment by alexander-m-ivanov** [comment]
@ryan-snyder , I see you closed this issue yourself. Do you have a solution to this problem as I asked the same question in the Repo several days ago?

**Comment by ryan-snyder** [comment]
@alexander-m-ivanov I honestly can't remember since it was a year ago. We aren't using selenium anymore and I believe we abandoned the above due to the amount of effort but I could be wrong.
