### ISSUE TITLE
"There is something wrong with the proxy server, or the address is incorrect."

### ISSUE THREAD

**Issue by ronald4545** [lightbody/browsermob-proxy#777]
I get the error below just running the sample code [from the README](https://github.com/lightbody/browsermob-proxy#using-with-selenium) in a clean project.

Weird thing is it works on my personal computer but not my company computer. And I made sure that I was not in any VPN or had any exisiting proxy settings. Does anyone have any idea why this happens?

![screen shot 2018-08-20 at 3 50 03 pm](https://user-images.githubusercontent.com/11577485/44606994-f28fca00-a7bc-11e8-80dd-fc994a719b1b.png)

**Comment by ronald4545** [comment]
And on my company computer, I could run the standalone browsermob proxy only when I do "sudo ./browsermob-proxy"
If I don't do sudo, I get the same error above

**Comment by thomasKuntermannDiva-e** [comment]
found the solution for that issue for MacOS users:
- edit /etc/hosts via "sudo nano /etc/hosts"
- add your Mac HOSTNAME (with ".local") to the entries "127.0.0.1" and "::1"
- press CTRL + o and leave with CTRL + x
- restart DNS serice: "sudo killall -HUP mDNSResponder"

that was happening, when working with an active VPN connection to my companies network.

**
127.0.0.1       localhost,mbpro-username.local
255.255.255.255 broadcasthost
::1             localhost,mbpro-username.local
**

**Comment by ronald4545** [comment]
Thanks!
