### ISSUE TITLE
Browser-mob stopped working with Selenium-Java

### ISSUE THREAD

**Issue by vlohana** [lightbody/browsermob-proxy#795]
Below are the dependencies downloaded 

<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-core</artifactId>
			<version>2.1.5</version>
		</dependency>

Chrom Version : 70.0.3538.110

The above versions we working perfectly fine but the same stopped working for me  I am getting "This site can’t be reached" 
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

The same code was working perfectly fine for me 2-3 days back I have made no modifications on the code since then and I was amazed the same is not working all of the sudden 

Can somebody help me on this. 

On code level I am not getting any exception

I have also tried the same on the Firefox browser as well and the behavior is same on it as well 

BrowserDriverClass {
public BrowserMobProxy getProxyServer() {
		BrowserMobProxy proxy = new BrowserMobProxyServer();
//		proxy.setTrustAllServers(true);
		// above line is needed for application with invalid certificates
		/*proxy.setConnectTimeout(180000, TimeUnit.HOURS);
		proxy.setIdleConnectionTimeout(180000, TimeUnit.HOURS);*/
//		proxy.setHarCaptureTypes(CaptureType.getAllContentCaptureTypes());
		proxy.start();
		return proxy;
	}

ublic Proxy getSeleniumProxy(BrowserMobProxy proxyServer) throws UnknownHostException {
		Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxyServer);
		 String hostIp;
		 try {
			hostIp = InetAddress.getLocalHost().getHostAddress();
			logger.info("host ip: "+hostIp+ ";" + proxyServer.getPort());
			seleniumProxy.setHttpProxy(hostIp+":" + proxyServer.getPort());
//			seleniumProxy.setSslProxy(hostIp+":" + proxyServer.getPort());
			return seleniumProxy;
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
		return seleniumProxy;
	
	}

public driver getChromeDriver(String URL) {
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
				options.setExperimentalOption("prefs", chromePrefs);
		
		BrowserMobProxy proxy = getProxyServer();
		Proxy seleniumProxy = getSeleniumProxy(proxy);
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, seleniumProxy);
		capabilities.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, false);
		
		//options.addArguments("--proxy-server=localhost:9099");
		options.merge(capabilities);
		proxy.enableHarCaptureTypes(
				CaptureType.REQUEST_COOKIES,
				CaptureType.REQUEST_HEADERS,
				CaptureType.REQUEST_CONTENT, 
				CaptureType.REQUEST_BINARY_CONTENT,
				CaptureType.RESPONSE_HEADERS,
				CaptureType.RESPONSE_COOKIES,
				CaptureType.RESPONSE_CONTENT,
				CaptureType.RESPONSE_BINARY_CONTENT
				
				);
		WebDriver driver = new ChromeDriver(bldr.build(), options);
		logger.info("Har recording started....");
		proxy.newHar();
		driver.get(url);
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		return proxy;

}

Not sure what just happened all of a sudden anyone else also facing the same issue

**Comment by vlohana** [comment]
Issue Got Resolved by itself I guess something to do with Company  VPN now I can access the url

**Comment by swastikasinghal** [comment]
then close the issue?

**Comment by vlohana** [comment]
Issue Got Resolved by itself I guess something to do with Company VPN now I can access the url

Closing
