### ISSUE TITLE
scala(java) selenium browsermob-proxy : no har generated

### ISSUE THREAD

**Issue by andreabisello** [lightbody/browsermob-proxy#803]
Hi.

i'm running some selenium based test on websites and everything works well both with firefox and with chrome.

i'm trying to use browsermobproxy : i already able to is in python, but i need to use in a scala project (scala also accept java code)

as you can see in the screenshot, chrome are using the proxy (i think) but no har are saved.

can someone help me?

![image](https://user-images.githubusercontent.com/2149815/51395189-841d2100-1b3c-11e9-95aa-fad0af204a28.png)

this is the code

```
val proxy = new BrowserMobProxyServer()
    proxy.start(0)
    Thread.sleep(5000)

    val seleniumProxy = ClientUtil.createSeleniumProxy(proxy)

    val coptions = new ChromeOptions()
    coptions.setProxy(seleniumProxy)
    implicit var webDriver: WebDriver = new ChromeDriver()
    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT)
    proxy.newHar("github")
    webDriver.get("https://www.github.com")
    val har = proxy.getHar()
    print(har.getLog())
    println(har)
    Thread.sleep(5000)
    webDriver.close()
    proxy.stop()
```

**Comment by andreabisello** [comment]
i understand  the problem,
the browser is not using the proxy,
so the har generated is empty.

i think chrome will try to use the proxy but if not available , it avoid to use it.

the problem was related to multiple network interfaces.

i open another ticket.

**Comment by sergius** [comment]
Hi Andrea,

Did you manage to solve this issue? I'm having something very similar and can't find a solution for several days now. Please give me a hint where to look and what can be done.

Many thanks

**Comment by andreabisello** [comment]
i saved the sources,
even i moved to puppeteer.

i solved the problem hard-coding the network interfaces because i was not able to understand what was the REAL network interfaces

due i don't have the intellij ide anymore and i'm cannot format the code i put some screenshot

![image](https://user-images.githubusercontent.com/2149815/76123909-e7e10280-5ff9-11ea-98d2-39b15d82df6e.png)

![image](https://user-images.githubusercontent.com/2149815/76123927-f29b9780-5ff9-11ea-9443-8c08a476d21e.png)
