### ISSUE TITLE
https websites using BrowserMob proxy with Selenium does not work

### ISSUE THREAD

**Issue by rathodkinjal** [lightbody/browsermob-proxy#82]
I was trying to use the code in the section "Using  with Selenium" posted on https://github.com/lightbody/browsermob-proxy to load any https website (https://www.yahoo.com) on my Mac. I see an error message like this "
Oops.

Something went wrong.

Firefox can't load this page for some reason.
"

On the console I get an error message as seen below:

INFO: javax.net.ssl.SSLHandshakeException: Received fatal alert: unrecognized_name when requesting https://www.yahoo.com/
Aug 03, 2014 10:55:23 PM net.lightbody.bmp.proxy.util.Log info
INFO: javax.net.ssl.SSLHandshakeException: Received fatal alert: unrecognized_name when requesting https://www.yahoo.com/favicon.ico
Aug 03, 2014 10:55:24 PM net.lightbody.bmp.proxy.util.Log info
INFO: javax.net.ssl.SSLHandshakeException: Received fatal alert: unrecognized_name when requesting https://www.yahoo.com/favicon.ico

**Comment by AndreBaumeier** [comment]
same issue here with browsermob via maven:

```
       <dependency>
            <groupId>net.lightbody.bmp</groupId>
            <artifactId>browsermob-proxy</artifactId>
            <version>2.0.0</version>
        </dependency>
```

**Comment by metasonic** [comment]
Hey guys,
Had this issue for a really long time, untill I moved the browsermob proxy library first in the libs list, for some reason it works like that.

**Comment by sachin6757** [comment]
@metasonic can u please explain where u copy browsermob proxy library to which libs list?

**Comment by metasonic** [comment]
@sachin6757 
Please see the attached image.
I'm using intelij right now, but it's similar in eclipse as well, you have the option to order your dependencies, the trick is to have browsermob proxy first, or in front of the selenium one.
![order](https://cloud.githubusercontent.com/assets/6897242/25499061/df05e584-2b92-11e7-814e-2397c7eaf975.JPG)

Poke me if you need more info

**Comment by Sourabh25** [comment]
@sachin6757 Could you please explain more on this. This same solution is working for me but I am not understanding the reason
