### ISSUE TITLE
Unable to open the url in chrome using selenium, It shows "This page isn’t working"

### ISSUE THREAD

**Issue by MonalisaT** [lightbody/browsermob-proxy#830]
<img width="1440" alt="Screen Shot 2019-08-12 at 5 35 38 PM" src="https://user-images.githubusercontent.com/54027535/62864451-68bc7200-bd29-11e9-9fbd-aa3ffc4708eb.png">
I am using selenium 3.141.5 and chrome 75. While running the test the browser is getting launched with "The Page isn't working". Could you please let me know if anything is missing from my end ?

**Comment by ericbeland** [comment]
Hi MonaLisaT, did the test work previously? Is it an intermittent problem?

**Comment by MonalisaT** [comment]
@ericbeland  nope, this is the first time I am running the test using browsermobproxy. Please guide me if any config is missing. Also I have gone through the readme file for server related setup.

**Comment by MonalisaT** [comment]
seleniumProxy.setHttpProxy(proxy.getClientBindAddress().getHostAddress() +":" + proxy.getPort());
This solved the issue.
