### ISSUE TITLE
ProxyServer class should try to find a free port by itself if nothing is specified

### ISSUE THREAD

**Issue by d0x** [lightbody/browsermob-proxy#98]
On our build server it would be handy if browsermob finds a free port by itself.
Since we are using the `public org.openqa.selenium.Proxy seleniumProxy()`-Method we are not dealing with the chosen port anyway.

I think thats a small change here:
https://github.com/lightbody/browsermob-proxy/blob/master/src/main/java/net/lightbody/bmp/proxy/ProxyServer.java#L66

Would you accept that?

I found this snipped how to find a free port. But i don't really now what it implies...
```
    private int findFreePort()
    {
        try (ServerSocket socket = new ServerSocket(0))
        {
            socket.setReuseAddress(true);
            return socket.getLocalPort();
        }
        catch (IOException e)
        {
            throw new IllegalStateException("Can't acquire free port", e);
        }
    }
```

Best Regards,
Christian.

**Comment by jekh** [comment]
I'm going to close this since it is basically works-as-designed and @cowwoc listed a solution to the original problem. @d0x - Feel free to reopen if you're still having issues.
